### ISSUE TITLE
Push segues

### ISSUE THREAD

**Issue by CalebeNP** [lkzhao/Hero#1]
Is there any plan to add push segues support?

**Comment by lkzhao** [comment]
Are you trying to push a another view controller in a UINavigationController stack?
Than can be achieved by setting 'isHeroEnabled' on the navigationController and you are good to go.

**Comment by CalebeNP** [comment]
@lkzhao wow! Thanks! I think it should be in the README.md to help other.

Amazing lib! 👏👏👏

**Comment by bishalg** [comment]
Yep, setting isHeroEnabled work for Navigation Controller but now I have lost the swipe to back ( from left edge ) to go back to previous view-controller ! 
How can I keep swipe to back on VC ?

**Comment by ergunkocak** [comment]
`pod 'SwipeBack', '~> 1.1'`

**Comment by StainlessStlRat** [comment]
> pod 'SwipeBack', '~> 1.1'

This is nice, but then you lose the shared transition animation on the way back
