### ISSUE TITLE
Default push/pop/present/dismiss HeroDefaultAnimationType 

### ISSUE THREAD

**Issue by fruitcoder** [lkzhao/Hero#100]
It would be really nice to have a way to tell Hero that every push transition should be `.zoom` and every pop transition should be `zoomOut` (for example). The same applies to show and dismiss transitions even though it makes more sense to me that a navigation controller should always have the same kind of push/pop transitions.

Those default animation types should be set on `Hero.shared` like `Hero.shared.setDefaultAnimationForPushOperation(_: Hero.HeroDefaultAnimationType). Whenever there is a push operation and `setDefaultAnimationForNextTransition` wasn't called before the transition, the default transition would be applied.

**Comment by lkzhao** [comment]
Just uploaded a commit with 3 new APIs

```swift
extension UIViewController {
  /// default hero animation type for presenting & dismissing modally
  public var heroModalAnimationType: HeroDefaultAnimationType
}
extension UINavigationController {
  /// default hero animation type for push and pop within the navigation controller
  public var heroNavigationAnimationType: HeroDefaultAnimationType
}
extension UITabBarController {
  /// default hero animation type for switching tabs within the tab bar controller
  public var heroTabBarAnimationType: HeroDefaultAnimationType
}
```

**Comment by fruitcoder** [comment]
Wow, thanks for the fast reply, could you add a distinction between push/pop and present/dismiss?
i.e.
```
extension UIViewController {
  /// default hero animation type for presenting
  public var heroModalPresentationAnimationType: HeroDefaultAnimationType
  /// default hero animation type for dismissal
  public var heroModalDismissalAnimationType: HeroDefaultAnimationType
}
extension UINavigationController {
  /// default hero animation type for push within the navigation controller
  public var heroNavigationPushAnimationType: HeroDefaultAnimationType
  /// default hero animation type for pop within the navigation controller
  public var heroNavigationPopAnimationType: HeroDefaultAnimationType
}
```

I think especially for push/pop and present/dismiss it is natural to use reverse animations like zoom/zoomOut or slideUp/slideDown to provide context of where you came from :)

**Comment by fruitcoder** [comment]
I saw you actually already mentioned this in #86

**Comment by lkzhao** [comment]
you can set it to be:
```swift
heroModalAnimationType = .selectBy(presenting:.push(direction:.left), dismissing:.pull(direction:.right))
```

**Comment by fruitcoder** [comment]
Perfect! I think you can close #86 as well
