### ISSUE TITLE
Reset modifiers after transition

### ISSUE THREAD

**Issue by fruitcoder** [lkzhao/Hero#101]
I currently have a problem with a view controller that contains some cells. For the (navigation controller) transition I set `.scale` and `.position` modifiers on the selected cell. When I return to the previous view controller and select another cell both cells are animated during the transition because the first selected cell still has its hero modifiers set. To prevent this I reset the modifiers manually in `heroDidEndTransition()` but I don't want every view controller to handle this. 

Did you already handle this case somewhere in your example code?

A simple solution might be to add a `.reset` modifier which could set the `heroModifiers` to `[]` after the transition. Or have another modifier `.resetTo([HeroModifier]?)` where you could specify which modifiers you want to keep after the transition.

**Comment by lkzhao** [comment]
we can have this `.reset` modifier implemented. 

However, many times we don't want to reset these modifiers until the dismiss transition is completed. 

You can actually implement this in a HeroPlugin. something like:
```swift
extension HeroModifier {
  public static func reset() -> HeroModifier {
    return HeroModifier { targetState in
      targetState["reset"] = true
    }
  }
}
public class ResetPlugin: HeroPlugin {
  public override func clean() {
    for toView in context.toViews {
      if context[toView]?["reset"] == true {
        toView.heroModifiers = nil
      }
    }
  }
}
```

and enable the plugin somewhere via
```swift
ResetPlugin.isEnabled = true
```

**Comment by fruitcoder** [comment]
This shows that I should definitely look into Plugin ;) thanks
