### ISSUE TITLE
Weird memory leak, view retained in animatedViews

### ISSUE THREAD

**Issue by fruitcoder** [lkzhao/Hero#103]
I just noticed in my app, that a view didn't get released properly after I started using Hero for one of the transitions. Here is my setup for this situation:

I have view controller A which pushes view controller B (in a navigation controller).
I use `AsyncDisplayKit` for vc B, so it's a subclass of `ASViewController` (shouldn't matter, just for completeness). 
In vc B I add a container view to its view (an `_ASDisplayNode` instance) and a `PlayerViewController` is added as a child view controller to vc B whose view (basically a player) lives inside the container view. The container view also has a `UIImageView` subview.

The transition is from vc A's image view to vc B's image view (which is a subview of container view). This works like a charm, the idea is that the image is shown while the video is loading.

Now when I go back to vc A I noticed that the sound of the video was still playing and the memory debugger showed me that the child `PlayerViewController` was actually released but all of its views and the container view were still in memory. The debugger gave me this:

<img width="1315" alt="screen shot 2017-02-17 at 10 21 17" src="https://cloud.githubusercontent.com/assets/5515849/23060039/4f0c147a-f4fc-11e6-8a54-2d4e0865342b.png">

Even though I believe this is totally unrelated to ASDK I noticed it so the `_ASDisplayView` makes sense.

**Comment by lkzhao** [comment]
Sry, forgot to release that variable at the end of the transition.

Should be fixed with this: https://github.com/lkzhao/Hero/commit/7423512ff521ebd1ebff9d216f5890fad51200c1

**Comment by fruitcoder** [comment]
Just checked out your commit. Works now 👍
