### ISSUE TITLE
xcode 8.2.1 and swift 3 error /Hero-master 2/Sources/UIKit+Hero.swift:45:3: error: Large Tuple Violation: Tuples should have at most 3 members. (large_tuple)

### ISSUE THREAD

**Issue by chitaranjan** [lkzhao/Hero#104]
i am facing error while running the sample project for ios.

**Comment by BilalReffas** [comment]
Please use a short title instead of a error message when you fill issues. It's a swiftlint message. Just add this comment  
```
// swiftlint:disable:next large_tuple
```   
before this function
```swift
  var components:(r:CGFloat, g: CGFloat, b: CGFloat, a: CGFloat) 
```

It should work then 🎉

**Comment by chitaranjan** [comment]
kk thanks

**Comment by masgharneya** [comment]
I'm not able to build this project through carthage because I have swiftlint installed. Do we want to disable the large_tuple check in Hero?

**Comment by BilalReffas** [comment]
Just uninstall swiftlint before you build Hero you can install it again after that
