### ISSUE TITLE
Cancelling a transition and redoing it triggers an exception

### ISSUE THREAD

**Issue by BR41N-FCK** [lkzhao/Hero#105]
I've been playing around with the examples provided with the Hero framework. I have found a bug in the "apple product" example. Not sure if it's a bug in the example itself or the framework. Steps to reproduce:

1. Go to the "apple product" example.
2. Slide your finger right to left as if you wanted to go to the second VC and then go back (left to right) as if you changed your mind - all in one motion (you basically go nowhere - the first black iPhone 7 VC is still present).
3. Again, slide right to left.
4. An exception is triggered.

Tested with 
Xcode 8.2.1
iPhone 6
iOS 10.2.1

**Comment by lkzhao** [comment]
Not seeing this on the latest master. Can you check again?

**Comment by BR41N-FCK** [comment]
Yep. It's gone.
