### ISSUE TITLE
Tapping on a TableView cell does not start the transition

### ISSUE THREAD

**Issue by BR41N-FCK** [lkzhao/Hero#106]
In the provided sample project selecting a row in the table view (the first thing that appears) does not immediately cause the views to transition. Instead, you have to touch the screen again (location is irrelevant) to trigger the transition. The bug is pretty random. Sometimes if you select a cell and wait long enough it will eventually transition, other times it won't. Sometimes not scrolling the table view helps. Start the app and immediately select the topmost cell and it will transition, but it isn't always the case. The didSelectRow method is always called but the animation does not occur until you touch the screen for the second time.

Xcode 8.2.1
iPhone 6
iOS 10.2.1

**Comment by lkzhao** [comment]
https://github.com/lkzhao/Hero/issues/79

We can implement a fix. But that won't be pretty.

**Comment by BR41N-FCK** [comment]
Can you explain what the root cause of this behavior is?

**Comment by lkzhao** [comment]
Just a bug in iOS.

**Comment by lkzhao** [comment]
fixed in the latest master

**Comment by dipkasyap** [comment]
Issue is same on colleciton view !
