### ISSUE TITLE
0.3.2:  .overCurrentContext doesn't show underlying view

### ISSUE THREAD

**Issue by nasht** [lkzhao/Hero#107]
Hi there!

First off - just a note to say I'm a huge fan of this library.  It's been super useful - so massive thanks for all your hard work  👍 

My issue: I'm doing a [.fade] with a partial transparency on a controller using .overCurrentContext presentation style.

This was behaving exactly as I hoped using 0.3.1 (it was showing the controller below with a dark veil on top) , but it looks like in 0.3.2 we're back to a plain black background.. 

Any idea what's changed?

Thanks!

**Comment by lkzhao** [comment]
OverCurrentContext is not supported yet. I am surprised that it worked on 0.3.1. But even if it does work, I wouldn't recommend using 0.3.1 with .overCurrentContext. Hero does not keep necessary information to make everything work as intended. I will have this implemented maybe in a few days. Note that .overFullScreen is already supported. Please use that if that works for you.

**Comment by lkzhao** [comment]
#37 Duplicate

**Comment by Micke5** [comment]
Hi Man!
First of all this library is awesome! 👍 
The .overCurrentContext feature to have clear background would be amazing! 😃
