### ISSUE TITLE
push zoom and pop zoomOut?

### ISSUE THREAD

**Issue by bphenriques** [lkzhao/Hero#109]
Hello,

How can I push a view controller zooming, and popping zooming out?

I managed to animate a zoom using:
```swift
        Hero.shared.setDefaultAnimationForNextTransition(.zoom)
        Hero.shared.setContainerColorForNextTransition(.lightGray)
        hero_replaceViewController(with: controller)
```

But haven't managed to pop using the same logic:
```swift
        Hero.shared.setDefaultAnimationForNextTransition(.zoomOut)
        Hero.shared.setContainerColorForNextTransition(.lightGray)
        hero_replaceViewController(with: controller)
```

All my classes have isHeroEnabled = true

Thank you

**Comment by lkzhao** [comment]
Weird, this should work. Can you provide an example project so I can test to see what's wrong.

**Comment by bphenriques** [comment]
Sure thing. In your examples, you are replacing variations of a view controller. On this project we are using different view controllers (e.g. tableViewController A has a list of Cats (previews), and viewController B has the details of such cat).

I'll sent to you a example project as soon as possible.

**Comment by lkzhao** [comment]
@bphenriques Are you still having trouble with this?

Keep in mind that you can also use
```swift
navigationController?.heroNavigationAnimationType = 
  .selectBy(presenting: .zoom(direction: .left), dismissing: .zoomOut(direction: .right))
```

**Comment by bphenriques** [comment]
@lkzhao It has been solved! It was an issue on our end ! :)

**Comment by lkzhao** [comment]
Ok.👍🏼
