### ISSUE TITLE
issue with heroID being updated inside collectionview cells

### ISSUE THREAD

**Issue by imfractured** [lkzhao/Hero#110]
I'm using IGListKit to show a set of collection cells. My cells are just squares with an image view.  I use the image url as the heroID since its easy to track and dynamically update when a new image is set. It seems after an update has occurred, the subsequent hero animations are offset by the number of cells in the collection view that were inserted or added. You get a ghosting effect of two + cells animating back to their original positions when returning back from the presented view. Is there a way to clear out or nil a heroID or reset the cached mapping?

**Comment by lkzhao** [comment]
Can you check if the latest master fixes it? It might be related to https://github.com/lkzhao/Hero/issues/97

**Comment by imfractured** [comment]
Unfortunately its still happening, it seems like the heroIDs / objects are cached somehow even after prepare for reuse is called and the heroid is set to nil. Like #97 it only seems to happen when transitioning back to the previous view that presented the target controller. I can add a video or demo project if that may help? BTW Thanks so much for the excellent animation framework, its super slick!!!

**Comment by lkzhao** [comment]
Demo project would be nice!

**Comment by lkzhao** [comment]
Are you using the following to checkout the latest version:

pod "Hero", :git=>"https://github.com/lkzhao/Hero.git"

Cuz the newest version is not on the cocoapods spec yet.

**Comment by lkzhao** [comment]
Will close this for now. Feel free to reopen if you are still seeing the issue.
