### ISSUE TITLE
Default transition in UINavigationController with heroId?

### ISSUE THREAD

**Issue by Dimillian** [lkzhao/Hero#111]
So I have a UINavigationController, I used push and pop segue, I have some heroId, the custom animation works fine, but it also play the push animation, but I only want the hero transition. Should I disable manually the navigation controller transition manually each time with         Hero.shared.disableDefaultAnimationForNextTransition()?

Thanks!

**Comment by lkzhao** [comment]
Nope. You can set the heroNavigationAnimationType to .fade or .none on that navigation controller.

**Comment by Dimillian** [comment]
Ah I see, thanks !
