### ISSUE TITLE
UIImageView with different contentsRect on its layer

### ISSUE THREAD

**Issue by delannoyk** [lkzhao/Hero#114]
Hi!

I really *really* love this framework!
I wanted to try it out with a more complex animation though and migrate an existing transition in my app that uses an UIImageView in which its layer has a `contentsRect = CGRect(x: 0, y: -0.2, width: 1, height: 1)`. This imageView transitions to an UIImageView that has a default contentsRect (0,0,1,1).

Now if an animation could work with that only specific property by using the `.useLayerRenderSnapshot`, it only works if the image view it transitions from has the same frame of the one it transitions to (if I understand correctly) or it will get stretched.

In my case the UIImageView also grows from a small frame to a fullscreen image, and has its contentMode set to `scaleAspectFill`.

I couldn't find any quick workaround to this problem but I'm quite new in this code base.
Would you have something in mind that I could use?

Thanks!

**Comment by lkzhao** [comment]
animating contentsRect is not supported in 0.3.2. I just pushed a commit, please check if it works. Note that if you want to animate the content rect, you shouldn't `.useLayerRenderSnapshot`. Snapshots are not able to animate its contentsRect.

**Comment by delannoyk** [comment]
@lkzhao Thank you for your answer!

Unfortunately I already tried your additions with a fork but it didn't work 🙁
Also, I noticed that views (`toViews`) that don't have a match in the presenting controller but animate with modifiers such as .translate appears behind the snapshot. It also happens in the example app: I added a view in the 2nd view controller of `MusicPlayer.storyboard` that is supposed to go over everything:
<img width="415" alt="screen shot 2017-02-23 at 5 48 05 pm" src="https://cloud.githubusercontent.com/assets/1777691/23282699/66135e3c-f9f0-11e6-882b-8b693ccc1fe4.png">
with a translate modifier (`translate(0, 300)`) and it has weird glitch where the view goes behind everything that has a match and after the animation completes, it comes back at the front. I was trying to try out the `Usage Example 1` in the README. Although this should probably be in a separate issue, or maybe I'm using it wrong?

**Comment by lkzhao** [comment]
Use `.useGlobalCoordinateSpace` modifier on that pink view will solve that issue. This is because local coordinate space is used when views that are not matched.

**Comment by lkzhao** [comment]
Sorry, forgot one thing when implementing the contentsRect animation. Please check now.

**Comment by delannoyk** [comment]
> Use .useGlobalCoordinateSpace modifier on that pink view will solve that issue. This is because local coordinate space is used when views that are not matched.

Awesome that works! Thanks.

> Sorry, forgot one thing when implementing the contentsRect animation. Please check now.

Same thing.

**Comment by lkzhao** [comment]
Can you provide me with an example project?

**Comment by delannoyk** [comment]
Sure! Thank you for taking the time to look into this.
Here's the project: https://github.com/delannoyk/HeroContentsRect

Tap the image to present the next view controller, swipe down on the 2nd view controller to dismiss.

**Comment by lkzhao** [comment]
Should be fixed in 0.3.3

**Comment by delannoyk** [comment]
@lkzhao That is awesome man, thank you!
