### ISSUE TITLE
Impossible to start animation with Hero!!

### ISSUE THREAD

**Issue by Douvi** [lkzhao/Hero#117]
I suppose I'm missing something but I do not know what!!
I try to reproduce the Basic storyboard you set as example but without success

can you take a look of my git please:
https://github.com/Douvi/TestHero

**Comment by lkzhao** [comment]
You have to set the `isHeroEnabled` property to true on the navigation controller.

**Comment by patchthecode** [comment]
You should put this is documentation. This took me a while to figure out.

**Comment by lkzhao** [comment]
@patchthecode  it is in the usage guide [https://github.com/lkzhao/Hero/wiki/Usage-Guide#uinavigationcontroller--uitabbarcontroller]

**Comment by patchthecode** [comment]
Ah. ok my bad. I guess i missed it as well.

**Comment by Douvi** [comment]
yep It's working after added `isHeroEnabled` into my navigation controller

**Comment by lkzhao** [comment]
@patchthecode I have updated the README with a FAQ section. If there is anything else unclear or hard to find. Please let me know so that I can add them to the FAQ.

**Comment by patchthecode** [comment]
@lkzhao understood. Will do.
