### ISSUE TITLE
spring example...

### ISSUE THREAD

**Issue by imougy** [lkzhao/Hero#118]
First, brilliant work! Congratulations!
I tried setting hero modifier to `scale(0.4) spring(100, 30) ` on a UILabel but it doesn't do anything. I debugged the library and everything seems fine!
Am I missing something?

**Comment by lkzhao** [comment]
Do you have `isHeroEnabled` set to true on your destination VC or navigation Controller?

Your damping might be too high to see the actual effect. Try something like `spring(100,10)`.

**Comment by imougy** [comment]
I tried that and yes I have other type of modifiers working fine! It is really weird.

**Comment by imougy** [comment]
Here is a small movie for the animation.
https://www.dropbox.com/s/zjirla1bsvkcx9k/transition.mov?dl=0

Here is my settings.
![image](https://cloud.githubusercontent.com/assets/3361440/23322006/cfc1edb6-fa96-11e6-9c8e-44324ae43623.png)

**Comment by lkzhao** [comment]
So it is not working for you only when you combine spring with scale modifier?

**Comment by imougy** [comment]
It is working now, I think I was missing the useGlobalCoordinateSpace.
Again, beyond awesome.

**Comment by lkzhao** [comment]
Thats great!
