### ISSUE TITLE
Question: How to i animate only one item in a UITableView?

### ISSUE THREAD

**Issue by patchthecode** [lkzhao/Hero#119]
I have a UITableView with many items in it.

When I tap on an item, only one gets animated unto the second viewController. All is well.
But
When I tap on the back button, because all the cells on the previous screen has the same heroID, all the cells gets animated when moving back. 
Is there a way to only make one cell animate when i tap the back button?

**Comment by patchthecode** [comment]
Nevermind. Found the answer.
I can set the values in viewDidLoad.

**Comment by v-ken** [comment]
@patchthecode Can you elaborate on how you solved this?
I assumed you set the `heroID` value of the destination view in its `viewDidLoad`?

Doesn't seem to be working for me.

**Comment by patchthecode** [comment]
@v-ken in the UITableView function

```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
```

i set the heroID of each cell to be the `indexPath.row` number. This made each cell to have a unique heroID.

Then when i select the cell, i pass the hero ID to the new viewController.
So when i tab back to the previous controller, only one heroID will animate.
hope this helps

**Comment by v-ken** [comment]
Ahh ok! Thanks!
