### ISSUE TITLE
Adding transitions from storyboard

### ISSUE THREAD

**Issue by aloisdeniel** [lkzhao/Hero#120]
It would be great to be able to add ViewController transitions (`heroModalAnimationType`, `heroNavigationAnimationType`, `heroTabBarAnimationType`) from user defined runtime attributes (just like modifiers).

**Comment by lkzhao** [comment]
Yes, we can have this implemented. But it will also be a string typed value.

**Comment by aloisdeniel** [comment]
Yes, as a string like `heroModalAnimationType `=`cover(up)` it would be just fine!

**Comment by lkzhaoSC** [comment]
Implemented in the latest master.

**Comment by lkzhao** [comment]
Implemented in the latest master.

**Comment by aloisdeniel** [comment]
You're the best! Thanks :)

**Comment by patchthecode** [comment]
@aloisdeniel its added.. but how do we use it on story board?
