### ISSUE TITLE
hero_presentOnTop no interactivity?

### ISSUE THREAD

**Issue by aventurella** [lkzhao/Hero#121]
I have a `UIActivityIndicatorView` in a view controller. when I call `hero_presentOnTop` I see my view on top of my current view controller, but the `UIActivityIndicator` does not animate despite it being set to animate.

Is there something else I need to do?

My guess is the `.useNoSnapshot` modifier is going to come into play.

**Comment by lkzhao** [comment]
Sorry, that API is not supported. It is actually left over before implementing the `.overFullScreen` Support. You should set the modalPresentationStyle of your UIActivityIndicatorView VC to be `.overFullScreen` and the present it modally.

**Comment by lkzhao** [comment]
And yes, if you want your `UIActivityIndicator` to animate during the transition. You should use the `.useNoSnapshot` modifier.
