### ISSUE TITLE
Transition get stuck in the middle of the animation.

### ISSUE THREAD

**Issue by cstars135** [lkzhao/Hero#123]
Hero.shared.end() has executed, but the animation view do not disappear.
![image](https://cloud.githubusercontent.com/assets/5800672/23347197/5e80ad94-fcdb-11e6-904a-49f42d5b3301.png)
This problem do not appear everytime ,but  it is very frequently

**Comment by lkzhao** [comment]
Not seeing this in the example project. Check if you called Hero.shared.update after you called Hero.shared.end. If not, then can you provide a demo project?

**Comment by lkzhao** [comment]
closing out old issues, feel free to reopen
