### ISSUE TITLE
Push drop shadow when working inside UINavigationController

### ISSUE THREAD

**Issue by ayoze** [lkzhao/Hero#124]
Hello,
I'm trying to make a custom push animation (objective C + storyboard, FYI). Everything works almost great... the animation is performed correctly but I see the native drop shadow from the push UINavigationController animation over my current views. 
Does anybody know how to prevent this?

Thanks!

**Comment by lkzhao** [comment]
Set your navigation controller's heroNavigationAnimationType to .fade

**Comment by ayoze** [comment]
Can it be done from ObjC? I don't think so... the property heroNavigationAnimationType is not available in the UINavigationController extension exposed in the -Swift.h umbrella.

**Comment by lkzhao** [comment]
Ah, I see. I will make it avaliable to objc in the next version.

**Comment by ayoze** [comment]
Thanks in advance!
I tried to make it available (since I dont know Swift yet) but may not be very easy since some enum's are not supported in Objective C, right?

**Comment by lkzhao** [comment]
Yes, associateType is not supported in objc. we will have to make this a
enum-like class just like the HeroModifier.

**Comment by ayoze** [comment]
Cool :) 
Let me know if I can help with anything

**Comment by lkzhao** [comment]
In the latest master. You can use heroNavigationAnimationTypeString to assign a value.

**Comment by ayoze** [comment]
Many thanks, i'll give it a try!

**Comment by ayoze** [comment]
Hello again,
I am getting a bunch of compilation errors now. Here is a screenshot:
<img width="1110" alt="captura de pantalla 2017-03-03 a las 9 47 43" src="https://cloud.githubusercontent.com/assets/1452175/23544256/9076ad3a-fff6-11e6-80da-396d645f3f37.png">

**Comment by ayoze** [comment]
I think you just forgot to modify the podspec to include the Kaleidoscope *.swift files.

**Comment by ayoze** [comment]
Yes, I created a Local podspec including those files and everything worked now in objC ! :)
btw, "none" can not be set as HeroDefaultAnimationType via string? I'm using "fade" but with "none" it says this key does not exist.
