### ISSUE TITLE
Custom transition makes the UICollectionView's content hide below navigation bar.

### ISSUE THREAD

**Issue by StarWars** [lkzhao/Hero#125]
Hi @lkzhao first of all - thanks for the great tool.

I found an issue that is related to the UICollectionView content insets calculations. 
According to this [stackoverflow thread](http://stackoverflow.com/questions/20312765/navigation-controller-top-layout-guide-not-honored-with-custom-transition) a lot of developers need to hack around the system's improper topLayoutGuide value when using custom transition.

The problem exists in your library as well. When you use push transition on the UINavigationController with the UICollectionViewController as the target, you'll notice that it's content hides below the UINavigationBar.

The topLayoutGuide.length returns the _status bar height_ instead of the _(status bar + navigation bar) height_.
The problem DOES NOT exist if the default system push animation is used.

Best,
Mike

**Comment by lzhaosc** [comment]
Can you provide me with a specific case demo?

**Comment by lkzhao** [comment]
Can you provide me with a case demo?

**Comment by StarWars** [comment]
@lkzhao I believe the real culprit is not your Hero library but my UINavigationBar configuration. This is the line causing problem: `navigationBar.setBackgroundImage`. 
This issue can be closed :) Thanks!

**Comment by StarWars** [comment]
The problem is created when you call `navigationBar.setBackgroundImage`. You can try setting that value in any configuration of your choice, to see that it causes the `UICollectionView` to hide below the navigation bar.

**Comment by lkzhao** [comment]
Hero uses the source's view's frame and apply it to the destination view. If you have the source view's frame set correctly, should be working. Try inserting a break point inside hero and check to see if your source view's frame is correct.
