### ISSUE TITLE
TabBar Animations is jerky V 0.3.3

### ISSUE THREAD

**Issue by ajaybeniwal** [lkzhao/Hero#126]
Im trying to use hero animation on tab bar controller with push animation type , but the animation kind of jerks if the next view controller is empty like a empty ui view controller with no other controls (Think as of blank white screen)

**Comment by lkzhao** [comment]
Not sure why. Can you post a video or sample project?

**Comment by ajaybeniwal** [comment]
Sorry i cannot share the project
I posted a video on dropbox 
https://www.dropbox.com/s/0juzcy4orc1994f/Screen%20Recording.mov?dl=0

**Comment by lkzhao** [comment]
Ok. It is because your view controller's background is transparent. Set it to white will fix the problem.

**Comment by ajaybeniwal** [comment]
Thanks works after setting background color
