### ISSUE TITLE
I am not able to setup transition

### ISSUE THREAD

**Issue by czater** [lkzhao/Hero#127]
Hello!

I am following your instruction and setup heroID for my 2 VC (same for both) and enable Hero in storyboard, but there is no transition and I am pretty sure I am missing something...
I just want ZoomSlide transition between 2 VC and pass data between them so I think I can't use hero_dismissViewController, so how should I do this? Can you help me?

**Comment by lkzhao** [comment]
if you just want zoomSlide. you don't need heroID.

**Comment by czater** [comment]
Okey, so how should I setup this? If I do nothing (except import Hero) I have standard, iOS transition :/
I am sure I am missing something but I don't know whaaat :/

**Comment by czater** [comment]
works!
