### ISSUE TITLE
Can transitions happen in the same ViewController

### ISSUE THREAD

**Issue by otymartin** [lkzhao/Hero#128]
@lkzhao 
Take for example the `basic` example with `blue, purple and green` squares. It transforms when you go from `VC-1` to `VC-2`. But can the same transition happen within `VC-1`. So when you press `next`, it transforms, no segue!

I want replicate this button transition/transformation.
![giphy](https://cloud.githubusercontent.com/assets/2222881/23531548/e82a9c26-ff74-11e6-9156-044a34d91692.gif)

**Comment by otymartin** [comment]
Update** I managed to do it with the [Interpolate](https://github.com/marmelroy/Interpolate) repo but would be cool to support this here unless its out of focus.

**Comment by lkzhao** [comment]
Will be implemented post 1.0.
https://github.com/lkzhao/Hero/issues/95

**Comment by otymartin** [comment]
@lkzhao nice 🙌
