### ISSUE TITLE
Many errors appearing at compilation 

### ISSUE THREAD

**Issue by charvoa** [lkzhao/Hero#131]
Using Xcode 8.2.1 and Swift 3.0 I got many errors like this : 

- Use of undeclared type 'ExprNode'
- Use of unresolved identifier 'get' 
- Use of unresolved identifier 'Lexer' 
- Use of unresolved identifier 'Parser' 

I have no idea where it could come from . 

Thanks for your help !

**Comment by lkzhao** [comment]
Should be fixed now. Sorry.
