### ISSUE TITLE
weird white artefacts during transitions in the example project

### ISSUE THREAD

**Issue by imcery** [lkzhao/Hero#133]
After compiling the example project HeroVerticalCityGuideExample in the simulator some weird white artefacts do appear during transitions, check the video https://drive.google.com/file/d/0B-AwWBgR9IXWbW5aWlk2eTZqVkU/view?usp=sharing

**Comment by lkzhaoSC** [comment]
see readme. iphone 7 simulator is not supported

**Comment by lkzhao** [comment]
see readme. iPhone 7 simulator is not supported.
