### ISSUE TITLE
Changing type and target of transition on unwind/way back

### ISSUE THREAD

**Issue by freak4pc** [lkzhao/Hero#135]
I'm trying to create the following situation

1. List of items, the container has "product{ID}" as heroID 
2. When the list is tapped a detail view for the item is opened sharing the same heroID.

Up to here all good,
The problem is on the "way back" there are two options

1. Dismiss regularly, which would just default to unwinding with the same animation as they share a heroID

2. The user can tap "add to cart", which I would want to use a different animation (transition the container "into" the cart with an `arc`). 

What would be the correct way to change the animation behavior based on business logic in this case?

Many thanks!
Shai.

**Comment by lkzhao** [comment]
Before calling dismiss. Set your detailed view heroID to nil. Then set its heroModifiers to .source("cart")

**Comment by freak4pc** [comment]
Works pretty great! Thanks for the assistance :) I have another issue with a bug related to animating MKMapView, should I make another issue or is it fine to ask here?

**Comment by lkzhao** [comment]
Another issue is probably better.
