### ISSUE TITLE
Unable to build Example - Exit code 1

### ISSUE THREAD

**Issue by grantkemp** [lkzhao/Hero#137]
Using the latest version of Xcode Release we are unable to build the example projects. 
We tried
1. `pod install`
2. `pod update`
But we still get the same error: 

```
Linting Swift files at path ..
No lintable files found at path '..'
Command /bin/sh failed with exit code 1
```

![image](https://cloud.githubusercontent.com/assets/751115/23662850/b8260db2-0348-11e7-87de-422ad96a1aa9.png)

```
more detailed error: 
Loading configuration from '../.swiftlint.yml'
configuration error: 'unused_closure_parameter' is not a valid rule identifier
configuration error: 'weak_delegate' is not a valid rule identifier
configuration error: 'large_tuple' is not a valid rule identifier
Valid rule identifiers:
trailing_newline
opening_brace
custom_rules
empty_count
comma
colon
force_cast
type_name
trailing_semicolon
force_try
force_unwrapping
function_body_length
nesting
variable_name
conditional_binding_cascade
function_parameter_count
operator_whitespace
control_statement
legacy_constant
line_length
return_arrow_whitespace
trailing_whitespace
closing_brace
statement_position
type_body_length
todo
legacy_constructor
cyclomatic_complexity
missing_docs
valid_docs
file_length
leading_whitespace
legacy_cggeometry_functions
Linting Swift files at path ..
No lintable files found at path '..'
Command /bin/sh failed with exit code 1

```

**Comment by grantkemp** [comment]
It looks like its the requirement ot install Swiftlint in order to use the library.   can we maybe shift to using the cocoapods version of the module so it doesn't require installing a seperate program into the mac to use this library?

**Comment by grantkemp** [comment]
When I update the build script to use the syntax specified on the swift lint page - it still seems to create an error.  I would log a bug there- but there are over 150+ issues at the moment.

**Comment by lkzhao** [comment]
closing out old issues, feel free to reopen
