### ISSUE TITLE
hero_replaceViewController cannot be canceled while using gesture recognizer

### ISSUE THREAD

**Issue by pbaltarejo** [lkzhao/Hero#139]
I'm trying to develop infinit scroll between viewControllers while preserving to the user the sense of being in the same navigation place.
I based my code into your example 'AppleHomePage' and I found a couple of problems with the use of `hero_replaceViewController` in conjunction with a gesture recogniser.
First, if the user don't complete the gesture as expected the method cannot be rolled-back, in fact, it's adding multiple view controllers and breaking the navigation.
Second is the fact that is also animating the title on the navigation bar.

I attached a sample project that shows exactly this. Just try to scroll between left and right view controllers without tapping out.
[ContinuousViewControllerScroll.zip](https://github.com/lkzhao/Hero/files/827572/ContinuousViewControllerScroll.zip)

Thanks :)

**Comment by lkzhao** [comment]
Thanks for the demo. I will see if I can fix this. But the `hero_replaceViewController`  rely on some hacks in the UINavigationController since UINavigationController doesn't really support this.
