### ISSUE TITLE
Bug when using a UIStackView with a HeroID

### ISSUE THREAD

**Issue by PSchu** [lkzhao/Hero#14]
Hi,

i found a bug when using your library with an UIStackView.
On the Start of the Animation the UIStackView gets bigger.
![simulator screen shot 04 01 2017 16 59 14](https://cloud.githubusercontent.com/assets/4762376/21648807/93d06be4-d29f-11e6-85a6-25528d55871f.png)
![simulator screen shot 04 01 2017 16 59 16](https://cloud.githubusercontent.com/assets/4762376/21648808/951e2e1e-d29f-11e6-994f-5a4345f0f4c8.png)

I created an Example Project: [HeroStackViewExample](https://github.com/PSchu/HeroStackViewExample)

**Comment by lkzhao** [comment]
For some reason, the API provided by apple:
```swift
stackView.snapshotView(afterScreenUpdates: true)
```
is broken. Returning a snapshot that looks different.

I updated your example to demo this:
https://github.com/PSchu/HeroStackViewExample/pull/1

Not sure how to fix this. 😂

**Comment by lkzhao** [comment]
Should be fixed in v0.0.5
