### ISSUE TITLE
hero_replaceViewController don't want the navigationbar animation

### ISSUE THREAD

**Issue by auqarius** [lkzhao/Hero#140]
Notice that when grid to list or list to grid, cell or item animation is perfect.
But in my project I need to make it like one page, so i don't need the navigation bar animation .
How can I do this? 
The pic is view controller pushing.
![grid to list](https://cloud.githubusercontent.com/assets/7312889/23779295/977e6562-057a-11e7-97cb-b576a95a6ef8.png)

**Comment by lkzhao** [comment]
Thats the default UIKit behavior. You can however, replace the entire UINavigationController with another one containing the gridView.

**Comment by lkzhao** [comment]
closing out old issues, feel free to reopen
