### ISSUE TITLE
is the interactivePopGestureRecognizer disabled?

### ISSUE THREAD

**Issue by gitcrosstrack** [lkzhao/Hero#143]
it seems that using hero on navigation controller breaks the interactive pop/back gesture slide, can I re-enable it easily? When I want to swipe back , nothing happens ..

**Comment by gitcrosstrack** [comment]
@jlongster

**Comment by gitcrosstrack** [comment]
@lkzhao 求大神指点，现在项目在用，但是手势返回就没了

**Comment by lkzhao** [comment]
If you use custom transition in UIKit, NavController's gesture will be gone. you can setup an interactive transition by adding your own gesture recognizer. Follow the interactive transition tutorial to see how it works with Hero. I promise you it won't be hard. Probably 10 lines to make it work.

**Comment by gitcrosstrack** [comment]
`func handlePan(gestureRecognizer:UIScreenEdgePanGestureRecognizer) {
        // calculate the progress based on how far the user moved
        //let translation = panGR.translation(in: nil)
        var progress = gestureRecognizer.translation(in: self.view).x / self.view.bounds.width
        progress = min(1.0, max(0.0, progress))
        
        switch gestureRecognizer.state {
        case .began:
            // begin the transition as normal
            //dismiss(animated: true, completion: nil)
            popViewController(animated: true)
        case .changed:
            if let _ = self.delegate as? Hero{
                Hero.shared.update(progress: Double(progress))
            }
        default:
            if let _ = self.delegate as? Hero{
                if progress > 0.5 {
                    Hero.shared.end()
                } else {
                   Hero.shared.cancel()
                }
            }
            // end or cancel the transition based on the progress and user's touch velocity
            
        }
    }
`
yeah，I do make it work using the tutorial code ,but it looks a little weird .When I swipe very quickly over many pages, it sometimes just stuck with two pages blending together  .Maybe next version can provide a more native way

**Comment by ThoseGuysInTown** [comment]
Simply adding 
`self.navigationController?.interactivePopGestureRecognizer?.delegate = nil`
to the view controller that is being popped worked for me.
