### ISSUE TITLE
I dont understand how to change Default Animations

### ISSUE THREAD

**Issue by LarsWith** [lkzhao/Hero#144]
I am trying to change the normal "push" animation to the zoom and zoomOut one.

My app looks like this:

**tabVC -> navigationController -> VC1 -> VC2** 

What I want to do now is when I segue from **VC1** to **VC2** I want to do a zoom animation, and when I go back to **VC1** from **VC2** I want to do a zoomOut animation.

I fire my current push segue like this: `performSegue(withIdentifier: x, sender: x)` so how do I change the transition animation to `zoom` and `zoomOut`?

**Comment by lkzhao** [comment]
You can use the following code:
```swift
heroModalAnimationType = .selectBy(presenting: .zoom, dismissing: .zoomOut)
```

**Comment by lkzhao** [comment]
Opps, there is a bug in 0.3.4. Will fix this in the next version
