### ISSUE TITLE
use of unresolved identifier CGPoint

### ISSUE THREAD

**Issue by kiwo12345** [lkzhao/Hero#146]
I just downloaded **v0.3.4** and did a manual install.
Now I get the error: `use of unresolved identifier CGPoint`

Line 35, 37, and UIColor in line 59

`HeroModifier+HeroStringConvertible.swift`

**Comment by lkzhao** [comment]
Should be fixed.

**Comment by lkzhao** [comment]
Thanks for reporting!!
