### ISSUE TITLE
Is it possible to animate cell during dragging in collection view?

### ISSUE THREAD

**Issue by czater** [lkzhao/Hero#150]
Hello!
So when I go in my CollectionVC, cascade animation appears on all visible cell, but when I dragging from top to bottom, there is no more animation. Is it possible to animating while dragging? 
Ex. Open CollectionVC -> there is 30 cells (from 100 in section) that animate -> drag down -> new cells appears but with no animation.

**Comment by lkzhao** [comment]
@czater Hero is not a collection view animation library. It just handles transitions between view controllers.

**Comment by czater** [comment]
ok
