### ISSUE TITLE
How to get the total duration of the current transition?

### ISSUE THREAD

**Issue by hmvr414** [lkzhao/Hero#152]
I got many views in the hierarchy with modifiers like .delay and .duration,
How to know what will be the total duration of the transition before presenting/dismissing?

**Comment by lkzhao** [comment]
You can get it from Hero.shared.totalDuration after the transition starts. (for transitions within UINavigationController, this might be delayed)

There is the `durationMatchLongest` modifier for you to match the duration with the longest one.

**Comment by hmvr414** [comment]
Is there a way to modify this duration? for example finish the transition in 500ms if the user cancels a pan gesture
