### ISSUE TITLE
ContainerView Support

### ISSUE THREAD

**Issue by mustangred** [lkzhao/Hero#153]
I have a container view within a view controller, and in the container view I switch view controllers programatically based on UIButton clicks. How do I get Hero to work in this context? 

I have been using Hero in other places and it works great. Thanks.

**Comment by lkzhao** [comment]
That will be a feature after 1.0. 

Currently, you can insert a hero enabled UITabBarController with a hidden tabbar as your container view.

**Comment by staticdreams** [comment]
+1 
I'm also interested in this feature. Thank you @lkzhao

**Comment by bleeckerj** [comment]
Ditto. I'd be happy to help if given guidance.

**Comment by abbasmousavi** [comment]
+1

**Comment by nativix** [comment]
+1
