### ISSUE TITLE
navigationController.push animation

### ISSUE THREAD

**Issue by Yoloabdo** [lkzhao/Hero#154]
I've tried to make hero transition in pushing controller into a navigation and i'd love to know if there's a way because it doesn't work with me at all, thanks

**Comment by martnst** [comment]
AFAIK that's not officially supported by now.

**Comment by lkzhaoSC** [comment]
Set isHeroEnabled to true on your UINavigationController(or self.navigationController)

**Comment by martnst** [comment]
Some documentation about the would be very helpful.

**Comment by lkzhao** [comment]
@martnst It is mentioned in the FAQ section on the readme. And also in the [Usage Guide Page](https://github.com/lkzhao/Hero/wiki/Usage-Guide)

**Comment by Yoloabdo** [comment]
Solved by enabling hero on the UINavigationController, thanks all
