### ISSUE TITLE
Whiteflash happens on other simulators besides 7 Plus

### ISSUE THREAD

**Issue by ddralves** [lkzhao/Hero#157]
Hi,

So I have experienced an issue where Modal Transition Animations cause flashing on the Simulator, even if you use another Simulator besides iPhone 7 Plus as per previously recorded issue. But when I run app on an actual phone, the flashing disappears and one can see the animation.

Any reason why this is happening.

My code is like this:

```
@IBAction func goRedPressed(_ sender: UIButton) {
        
        let redVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "VC1") as! ViewController
        
        redVC.isHeroEnabled = true
        redVC.heroModalAnimationType = .auto
        self.hero_replaceViewController(with: redVC)
    }
```

If something is wrong my side please let me know.

Using Xcode Version 8.2.1 (8C1002) with Simulators 10.2

**Comment by mrfarukturgut** [comment]
Having same issue. It happens well on the iPhone SE Simulator but on the iPhone 7 Simulator, it flashes twice and does the segue. btw, I have set these `animationType`'s on storyboard, to the `navigationController` between root and target VC.

**Comment by mrfarukturgut** [comment]
@ddralves see this, [133](https://github.com/lkzhao/Hero/issues/133)

**Comment by ddralves** [comment]
Hi :)

So I made a medium post about the framework and I addressed this issue inside the post.

The trick is that the .auto call does not work. You have to use the method calls like .zoomSlide and then it works. Like this:

`@IBAction func goGreenPressed(_ sender: UIButton) {
let greenVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "VC2") as! ViewController
greenVC.isHeroEnabled = true
greenVC.heroModalAnimationType = .zoomSlide(direction: HeroDefaultAnimationType.Direction.left)
self.hero_replaceViewController(with: greenVC)
}`

Here is the link to my article. Discusses this a bit more: [https://medium.com/the-code-community/hello-x-cool-swift-3-transition-framework-ddada37db819](url)

I hope that Xcode 8.3 and the new 10.3 simulators resolve this issue. Seems like it is from Apple's side.
