### ISSUE TITLE
On the use of obj-c problems！

### ISSUE THREAD

**Issue by lz990377023** [lkzhao/Hero#159]
Hey, I used the hero in the obj-c environment, found heroModifiers can not be used as a property of the UI object, there are good suggestions?

**Comment by aloisdeniel** [comment]
As a workaround, you can use the ´heroModifiersString' (originally thought for storyboards). That's what I did for my [Xamarin binding](https://github.com/aloisdeniel/Xam.Hero).

**Comment by lz990377023** [comment]
@aloisdeniel Thank you for the advice, but the use of heroModifierString will be some trouble, there are more properties obj-c can not be used. May not be able to use the hero, but the hero is indeed a very good project.
