### ISSUE TITLE
hidesBottomBarWhenPushed bug

### ISSUE THREAD

**Issue by harri121** [lkzhao/Hero#160]
Hey, 
first of all, awesome framework!

I have a problem when I push a view controller with hidesBottomBarWhenPushed = true
with a custom animation.
The bottom bar behaves as if the animation was the default push animation.
It slides to the left and while this animation is in progress the pushed view controller has a bottom inset  (height of the tab bar) which suddenly goes to zero as soon as the animation is finished.
Is there a way to make this work as expected?

**Comment by marcosgriselli** [comment]
@harri121 did you find a solution for this?

**Comment by harri121** [comment]
@marcosgriselli Unfortunately no..

**Comment by datcjordan** [comment]
Having the same problem here.. Any solution?

**Comment by pcalcagnino** [comment]
Same here. Possible workaround?

**Comment by ivanmkc** [comment]
Same problem here.

**Comment by chuwito** [comment]
I solved using this workaround. I hope that helps!
https://stackoverflow.com/a/44707169

**Comment by zvonicek** [comment]
I have this problem too.
