### ISSUE TITLE
Allow `heroEnabled` on view level

### ISSUE THREAD

**Issue by angelolloqui** [lkzhao/Hero#163]
When dealing with tables/collection views, it would be very handy to have a property on the view level that allows to mark a view as `heroEnabled` or not. This way, we could do things like:

```
class TableViewCell: UITableViewCell {
    override var isHeroEnabled: Bool { return isSelected }
}
```

Which could be used to automatically disable cells that are not the one currently selected and make transitions work automatically.

A different approach could be to allow customization of the `flattenedViewHierarchy` but since it is done inside an extension I think this will not compile (open extensions are not allowed AFAIK):

```
class TableViewCell: UITableViewCell {

    override var flattenedViewHierarchy: [UIView] {
        if isSelected {
            return super.flattenedViewHierarchy
        } else {
            return []
        }
    }
}
```

This change could also allow to increase performance by not enabling views that are not animated and have many subviews.

**Comment by angelolloqui** [comment]
By the way, the resulting `` could be:

```
public var flattenedViewHierarchy: [UIView] {
    if #available(iOS 9.0, *) {
      return (isHidden && (superview is UICollectionView || superview is UIStackView)) || !isHeroEnabled ? [] : ([self] + subviews.flatMap { $0.flattenedViewHierarchy })
    }
    return (isHidden && (superview is UICollectionView)) || !isHeroEnabled ? [] : ([self] + subviews.flatMap { $0.flattenedViewHierarchy })
  }
```

And the View extension property something like:

```
@IBInspectable public var isHeroEnabled: Bool {
    get { return objc_getAssociatedObject(self, &AssociatedKeys.heroEnabled) as? Bool ?? true }
    set { objc_setAssociatedObject(self, &AssociatedKeys.heroEnabled, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) }
  }
```

**Comment by angelolloqui** [comment]
Added #169

**Comment by bre7** [comment]
Shouldn't it be marked as `open` ?

**Comment by lkzhao** [comment]
@bre7 it is defined in an extension. not possible to override in future of swift.
you can do the following
```swift
override var isSelected {
  didSet {
    isHeroEnabled = isSelected
  }
}

**Comment by bre7** [comment]
I just edited the pod in my project ;)
