### ISSUE TITLE
HeroTabBarAnimation would cause crash if switch tabs quickly

### ISSUE THREAD

**Issue by xnth97** [lkzhao/Hero#166]
Hi, 

I added tab bar animation in Storyboard, and I found that if you quickly switch between tabs, especially switching to another tab before the animation finishes, there is possibility that the tabBarController would display nothing, or even the app would crash.

This can happen in the example that you provided. Here's a screenshot of the example that lost all content in tabBarController after some quick switches.
![img_7590](https://cloud.githubusercontent.com/assets/6781789/24578797/08e6ff9a-1730-11e7-8e9d-ba60360071cd.PNG)

When causing crash, I found that the problem is due to the 338th line of Hero.swift, `transitionContainer = context.containerView`. I didn't have time to deeply look into the code so I cannot provide further help. Sorry about that.

Thanks for bringing out Hero. It's awesome.

**Comment by EzDream** [comment]
I also have this problem @lkzhao

**Comment by EzDream** [comment]
@xnth97 Hi, guy, I have spent a day fix this bug, see that.

**Comment by anfriis** [comment]
I have an issue that is properly related to this, on the newest commit on master `e84209f3538...`. 
I have a modal view controller (vc) that is being dismissed to a vc inside a tab bar. In the vc's `viewWillAppear` method, I am setting the `selectedIndex` on the tab bar, to switch to another tab, and that causes the app to behave very weirdly and a restart is necessary.
I have solved it by temporary setting `isHeroEnabled` on the tab bar, before switching tab, and then enabling it after the switch is done

**Comment by ylmw0131** [comment]
A great concept product but sadly with many bugs.
