### ISSUE TITLE
React Native Help Wanted!!!

### ISSUE THREAD

**Issue by lkzhao** [lkzhao/Hero#17]
It would be so cool if this framework can work with [React Native](https://facebook.github.io/react-native/). 

Since **React Native** already have declarative view informations upon each `render` call (before creating the views). I am visioning that with **React Native**, **Hero** can handle all animations through out the App. If the component has Hero enabled. Then on each `render` call, **Hero** can do a comparison and animate the changes.
This is what I originally had in mind when building **Hero**. Handling animations for state change through out the App. View controllers can tell **Hero** to animate to another state without transitioning to another view controller. but that requires building some other declarative state holder.

I have worked with **React** about a year ago. Loved their framework but hated the animation aspect of it. I think animation has always been a weak point for it. Would be very useful if **React Native** and work with **Hero**.

First step of course, is just to support view controller transitions in React Native. But I have no experience working with it.
What do you guys think? Is anyone familiar with it?

**Comment by lkzhao** [comment]
Not in plan anymore. Hero has become quite coupled with UIKit and View Controllers. Would be hard to integrate with React Native. Will close this for now.

**Comment by n8stowell82** [comment]
I would love to see a port of this for react native.  Would be willing to help however I can!

**Comment by hfossli** [comment]
We would also like to contribute

**Comment by mikehobi** [comment]
@lkzhao Would Hero be able to integrate with the work done by Wix?: https://github.com/wix/react-native-navigation, a lib that implements `UIViewController` into the react native stack
