### ISSUE TITLE
Dismissing an ViewController runs the same animation as the one used for Presenting it.

### ISSUE THREAD

**Issue by TerrickMansur** [lkzhao/Hero#174]
When you present an Modal or push a ViewController with an animation, you would expect the reversed of the animation would play when you or dismissing the model or popping the view. But this is not the case.

Not sure if this was by design, but it would be great to have a reverseMode where you can tell Hero to do the reversed animation when dismissing or popping the view.

**Comment by sam899** [comment]
+1

**Comment by TerrickMansur** [comment]
@sam899 I created a pull request that creates this feature. You can check at the code I wrote to include this feature if yo like.

**Comment by lkzhao** [comment]
closing out old issues, feel free to reopen
