### ISSUE TITLE
Start animation after heroModifiers has been applied

### ISSUE THREAD

**Issue by gorozco58** [lkzhao/Hero#182]
I am trying to perform the next animation:
I have an UICollectionViewCell I want to apply rotation and cornerRadius and start the animation after the modifiers has been applied. is it possible ? 
I need to start the animation with the modifiers and then start the animation. I don't want to apply the modifiers and transition at same time.

Thanks :)

**Comment by atom2ueki** [comment]
@gorozco58 so far as I know, `Hero` only handle the transition in-between two view controllers, like the case you described, sounds like doing animation transition first, then switch to another view controller, you can try to apply [animate withDuration](https://developer.apple.com/reference/uikit/uiview/1622515-animate) first, then trigger segue to destination view controller with hero modifier

**Comment by lkzhao** [comment]
Closing old issues, feel free to reopen.
