### ISSUE TITLE
Video Player example dismiss transition

### ISSUE THREAD

**Issue by otymartin** [lkzhao/Hero#184]
@lkzhao 
Hey, Wondering if this is possible currently.
Take the video player example. As you pan to dismiss the video player, currently the VideoPlayerView becomes opaque revealing the background image from the tableView cell and the video stops playing.

I'd like to mimic the snapchat transition where the VideoPlayerView would maintain its alpha and visual content (video keeps playing) while the user is panning it around and only reveal the original tableView/CollecitonView cell on completion from dismissal. 

Not sure if this is related to #21 but how can I achieve this?

**Comment by tooolbox** [comment]
@otymartin Did you ever get this working?

**Comment by otymartin** [comment]
@tooolbox  nope
