### ISSUE TITLE
Hero animations cause views to appear on top of all other views.

### ISSUE THREAD

**Issue by t2davis** [lkzhao/Hero#187]
I've noticed that when dismissing a view controller to a view with cells that have their own hero modifiers, if those cells are underneath other views, they immediately appear on top of all other views until the hero animation is finished.

Example: 
I have a collection view directly under another `title` view (initial view). 
When I scroll the collection view so that cells are under the title view and select a cell (brings me to secondary view), upon transitioning back to the initial view each cell appears over the title view while it's hero modifier (scale, fade) are applied. Then the flash back underneath the title view.

I can upload a video of this behaviour if helpful.

**Comment by atom2ueki** [comment]
@t2davis can you provide your full code with the video you mentioned on this part ?

**Comment by stevejcox** [comment]
I think this is related to what I am seeing, I've posted an example
https://github.com/lkzhao/Hero/issues/199

**Comment by aronse** [comment]
I'm having the exact same issue. Is there any workaround?

**Comment by stevejcox** [comment]
@aronse Nothing that I have found that works consistently. Using zPosition has provided mixed success.

**Comment by lkzhao** [comment]
Try using these two in combination. `.beginWith(modifiers:[.zPosition(10)]), .useGlobalCoordinateSpace`

The **beginWith** modifier apply the modifier at the begining of the animation. It doesn't animate the zPosition from 0 to 10.
The **useGlobalCoordinateSpace** modifier ensure that the view is inserted into the top container view.

**Comment by stevejcox** [comment]
@lkzhao Thanks Luke, that doesn't seem to work for me. Updated my [demo here](https://www.dropbox.com/s/quyhpjoaxirltp5/HeroTest.zip?dl=0)

From what I can tell, Hero seems to be honoring the zPosition if the heroID exists in both the 'from' and 'to' views. If The item doesn't exist in one of them it seems to drop them to the bottom during the transition.

Again, I could be doing something very wrong on this. Hopefully the example illustrates it

**Comment by stevejcox** [comment]
@aronse @t2davis did you guys ever find a work-around at all?

**Comment by t2davis** [comment]
@stevejcox  No i couldn't get it to behave properly so I stripped some of the animations out.

**Comment by t2davis** [comment]
![bug](https://cloud.githubusercontent.com/assets/11417268/26332598/89ffc19e-3f0c-11e7-8acd-1e8873040804.gif)

**Comment by baims** [comment]
@aronse @t2davis @lkzhao did you guys solve this issue ?

**Comment by Rotemy** [comment]
need to reopen, see issue #454

**Comment by citizencoder23** [comment]
Can anyone show me example project with using zPosition? I can't use it. It's not work
