### ISSUE TITLE
Crash on fast translation within navigationController

### ISSUE THREAD

**Issue by istarchenkov** [lkzhao/Hero#188]
// When animating within navigationController, we have to dispatch later into the main queue.
        // otherwise snapshots will be pure white. Possibly a bug with UIKit
        DispatchQueue.main.async {
          self.animate()
        }

this async dispatch cause crash in case when you start translation and try to end in really short amount of time (for example when use pan gesture to animate translation, if you swipe screen really fast then this crash appear, probably because of async execution)

**Comment by istarchenkov** [comment]
to solve this I have to execute end/cancel async either

DispatchQueue.main.async {
      Hero.shared.end()
}

**Comment by lkzhao** [comment]
https://github.com/lkzhao/Hero/issues/203
