### ISSUE TITLE
Any way to disable fade effect with view while transition in 0.3.x?

### ISSUE THREAD

**Issue by spensko** [lkzhao/Hero#189]
Hi!

I'm still using 0.1.7 because there are no 'fade' effect while transition from collection/tableview cells to another controller, but exists in 0.3.x versions. 

Hero 0.1.7 https://youtu.be/ZUaKYfXxsP0
Hero 0.3.6 https://youtu.be/WRVcWnabvPc

as you can see with 0.3.6 small card have fade while scaling. Can it be disabled?

**Comment by benediktreichert** [comment]
Did you try `<yourView>.heroModifiers = [.forceNonFade]` ?

**Comment by spensko** [comment]
I've setted for collection view cell

`
cell.heroID = ....
cell. heroModifiers = [.forceNonFade]
`

also tried to set in destination view controller
`view.heroModifiers = [.forceNonFade]
view.heroID = ...`

doesn't help

**Comment by otymartin** [comment]
Yeah @lkzhao please address this

**Comment by spensko** [comment]
@lkzhao Looks like problem has been resolved in last alpha release?

**Comment by spensko** [comment]
setting cell.heroModifiers = [.forceNonFade] solve the problem
