### ISSUE TITLE
Stackview with Autolayout Issues

### ISSUE THREAD

**Issue by felix-dumit** [lkzhao/Hero#19]
Probably related to https://github.com/lkzhao/Hero/issues/14

I updated the basic example to use StackViews and had a few issues:

1) I had to set the autolayout priority to 999 for the height constraint in a horizontal stackview and for the width constraint in a vertical stackview, otherwise, it would complain about an ambiguous layout.

2) The animations still look a bit off, you can see from the image below, in the 1st animation, all labels jump after the screen initially loads. The 2nd animation just doesn't look right.

![HELLO](https://media.giphy.com/media/l0HlVuAONSwsncOUo/giphy.gif)

I have the code I used up here:
https://github.com/felix-dumit/Hero/tree/stackview-autolayout

Thanks for this lib I think it's really awesome!

**Comment by lkzhao** [comment]
@felix-dumit 
Thanks for such a detailed report. 

I put up a fix. Can you rebase your example to branch `stack-view-fix-2` and check if it actually fixes it?

**Comment by felix-dumit** [comment]
@lkzhao Yes it's working fine now! 👍 

I haven't tested yet on the project I was trying to integrate, where I first noticed the issue.
I also had an issue with a `UIVisualEffectView` getting broken and just displaying a black background. 
I'll give that another test and in case it's still happening I'll try to give you a simple reproducible example.

**Comment by lkzhao** [comment]
Oh that, UIVisualEffectView has always been problematic. 🤦🏻‍♂️ No easy way to snapshot them and maintain the effect live.
Help me open up another issue. I will see what I can do.
