### ISSUE TITLE
Animating inside a single View Controller

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [lkzhao/Hero#191]
Hi,

May I ask if the library is already capable to handle what I want to achieve. If not, any tips or suggestions on what can I do to achieve this.

Thank you so much!

**Comment by magin** [comment]
+1

**Comment by sam899** [comment]
+1 to this too

I have managed to achieve this by making the following method public:
`public func transition(from: UIViewController, to: UIViewController, in view: UIView, completion: ((Bool) -> Void)? = nil)`

However, I'm not sure if this is the best way

**Comment by abbasmousavi** [comment]
+1
