### ISSUE TITLE
Duration of template/default transitions

### ISSUE THREAD

**Issue by v-ken** [lkzhao/Hero#192]
Hi, first of all, thanks for the amazing library.

Just wondering if it was possible to set the duration of the template/default transitions?
e.g. Fade duration when setting `heroModalAnimationType = .fade`

**Comment by lkzhao** [comment]
all that does is set `destinationViewController.view.heroModifiers = [.fade]`

You can manually set `destinationViewController.view.heroModifiers = [.fade, .duration(5.0)]`

**Comment by lkzhao** [comment]
Cleaning Old Issues. Feel free to reopen.
