### ISSUE TITLE
Animations not working on Simulator in iOS 10.2

### ISSUE THREAD

**Issue by BalestraPatrick** [lkzhao/Hero#2]
Hey! Amazing library, it looks stunning. 👏 
I was testing it out on the Simulator but it looks like the animations are not working correctly in Xcode 8.2. Is it a bug or maybe something that should be mentioned in the README?

Testing on the device works perfectly! 😄

**Comment by lkzhao** [comment]
Try iPhone 6s simulators.there is a bug problem with iPhone 7 simulators. All iPhone 7 simulators won't work at the moment.

https://forums.developer.apple.com/thread/63438

**Comment by BalestraPatrick** [comment]
Ah, I see. Nothing to do with Hero then, I can close this!

**Comment by lkzhao** [comment]
Thanks for being this up. I forgot to put it in the Readme.
