### ISSUE TITLE
User interaction blocked until animation finished

### ISSUE THREAD

**Issue by giann** [lkzhao/Hero#201]
I have a background view were things are animated by Hero.
However I don't want to wait for those animations for my front view to be interacted with.

Is this possible ?

**Comment by srijan12345** [comment]
haha it's threading issue. Make it work team.

**Comment by lkzhao** [comment]
There is the new `isUserInteractionEnabled` property on `HeroTransition` object. Set that to true and you will be able to interact with your views. Keep in mind that only views with `.userNoSnapshot` will be interactable. And you will have to be careful not to transition within transition.
