### ISSUE TITLE
viewWillAppear / viewWillDisappear will be called when doing interactive transition

### ISSUE THREAD

**Issue by PatrickSCLin** [lkzhao/Hero#204]
Is because view is added / removed by hero at this moment ?

How do I detect that view is operated by hero or parent ?

**Comment by lkzhao** [comment]
Think this is expected. Transition will trigger a `viewWillDisappear` when your view controller is being dismissed. And if your interactive transition cancels, `viewWillAppear` will be called. This is also true for other transitions.

**Comment by PatrickSCLin** [comment]
Can I detect viewWillApear is called by Hero ?

I have done something in this method but I don't expect it runs when hero transition is running
