### ISSUE TITLE
Views with hero child elements partially out of screen not animated properly

### ISSUE THREAD

**Issue by angelolloqui** [lkzhao/Hero#205]
I have  list like this. 

When I click on a cell at the bottom that is partially displayed, the views that are out of bounds are not animated, resulting in a broken animation effect.

The issue is in the `HeroContext`, when it processes the views it ignores any view which bounds do not intersect with the container. 
https://github.com/lkzhao/Hero/blob/master/Sources/HeroContext.swift#L49

This is often a good check that will save some valuable CPU cycles by trimming the view list, but in other cases (like mine) you might want to animate something that comes from out of the screen into its proper place. 

I am considering to remove the check, but I am not sure if the performance implications are worth the extra flexibility given. Any thoughts? any other way we can solve this on request without modifying the default behavior?

**Comment by lkzhao** [comment]
Hmm, I understand. Will add a property to the new `HeroTransition` class to disable this behavior.

**Comment by lkzhao** [comment]
fixed by this commit: 
https://github.com/lkzhao/Hero/commit/7f64094e2e6ffb40396a20ec976dc43a5426247b

You can now use `.forceAnimate` modifier to force an out-of-screen view to animate.
