### ISSUE TITLE
Retain UILabel's text during and after interactive transition.

### ISSUE THREAD

**Issue by perteadrian** [lkzhao/Hero#206]
Hi, I've got some label's that I am transitioning interactively using Hero. 
Here is the view that the transition starts: 
![screen shot 2017-05-20 at 15 56 21](https://cloud.githubusercontent.com/assets/15149863/26276066/20f05af0-3d78-11e7-9a3d-0bb4ebd4fd99.png)
The interaction is a UIPanGestureRecognizer from the white view(up direction) and goes to this view:
![screen shot 2017-05-20 at 16 06 20](https://cloud.githubusercontent.com/assets/15149863/26276063/083551c8-3d78-11e7-9f0d-abd0bf330d2b.png)

How can I retain the label' text value and display it here?
Those 3 views(right now, today and tomorrow) are in a headerView of a collection view.

**Comment by perteraul** [comment]
Here's a video of myself replicating the bug: 
https://youtu.be/pTmJBJHXOHc

**Comment by lkzhao** [comment]
Sorry if this is too late. You will have to pass your data to your second VC. Hero doesn't understand the content of your views.

**Comment by lkzhao** [comment]
Cleaning Old Issues. Feel free to reopen.
