### ISSUE TITLE
heroNavigationAnimationType (.none) doesn't work

### ISSUE THREAD

**Issue by NikKovIos** [lkzhao/Hero#207]
Hello, sorry if i did misunderstand docs. They said: `Push animation is shown along side my custom animation. This is the default animation for navigation controller provided by Hero. To disable the push animation, set heroNavigationAnimationType to .fade or .none on the navigation controller.`

So i set heroNavigationAnimationType as none in storyboard for UINavigationController.
The structure is: UINavigationController -> VC1 -(pushSegue)> VC2

And when i press the button at VC1 in order to push VC2, then see a standard animation of pushing.

When i used a .fade type - everything forks correctly, but i got unnecessary for me blinking effect.

**Comment by pcalcagnino** [comment]
Same problem here. Any workaround?

**Comment by lkzhao** [comment]
Might be a bug. will take a look.

**Comment by lkzhao** [comment]
Can you provide an example project? or verify if it has been fixed for `1.0.0-alpha.1`. Couldn't reproduce on my end.

**Comment by RayanSaeed** [comment]
The issue is still present @lkzhao

**Comment by zuil7** [comment]
Hi i tried it also seem that heroNavigationAnimationType is not working. 

here is my sample code. i wanted to override the default animation. Is this correct?

        self.navigationController?.heroNavigationAnimationType = .cover(direction: .up)
        self.navigationController?.pushViewController(vc, animated: true)

**Comment by RayanSaeed** [comment]
No, actually we are talking about this issue right here #140

**Comment by leeprobert** [comment]
I get a warning in the console when I try to assign 'none' to my Navigation Controller in Interface Builder: "none doesn't exist in HeroDefaultAnimationType"
