### ISSUE TITLE
Crossfade animation bug with duplicated views

### ISSUE THREAD

**Issue by love4soul** [lkzhao/Hero#208]
Hi,

I have a problem with animating imageView using heroID - https://gyazo.com/4a045afed3798df9bc515426dd85b106. 
Image view on the first screen is contained in the CollectionView, on the second screen it is just image view with constraints.

**Comment by lkzhao** [comment]
try the release-1.0 branch

**Comment by lkzhao** [comment]
```ruby
pod "Hero", :git => 'https://github.com/lkzhao/Hero.git', :branch => "release-1.0"
```

**Comment by chili-ios** [comment]
@lkzhao , works like a charm, thanks!

**Comment by love4soul** [comment]
@lkzhao , works like a charm, thanks!
