### ISSUE TITLE
Views with transforms applied not beginning and ending transitions properly

### ISSUE THREAD

**Issue by tpj3duke** [lkzhao/Hero#209]
Source UIViews that have a transform applied to them are having their frames changed at the beginning of a transition, and also on completion when reverting back to that state. This causes a distinct jump when initializing a transition, as well as when the source 
view is returned to its default state, and is a jarring experience.

What should happen, is the source view that has a transform on it, should animate smoothly to the destination view, without any jumping.

I have attached an example project below with the bug, as well as videos of what is supposed to happen, and what is happening.

[Archive.zip](https://github.com/lkzhao/Hero/files/1027475/Archive.zip)

**Comment by lkzhao** [comment]
Think this is fixed. Not entirely sure. Feel free to reopen if the problem still exist.

**Comment by tpj3duke** [comment]
@lkzhao indeed it was fixed, thanks so much!
