### ISSUE TITLE
Actually transfer views

### ISSUE THREAD

**Issue by futuretap** [lkzhao/Hero#21]
I really like the elegance of your API and the approach of associating pairs of views using the heroID. Sometimes, there are situations where I want to actually transfer a specific view instance from one view controller to another. This is needed for complex views with opaque state such as `MKMapView` or `EAGLView`. I'd love to see support for such use cases!

I would envision to associate pairs of container views with a similar heroID mechanism and then insert the view into the paired container view at the start of the transition. Of course it's a bit tricky to install new constraints etc. so we'd need an `afterTransfer` configuration block or something similar where we could setup constraints.

I'm sure this would be a very useful addition! What do you think?

**Comment by lkzhao** [comment]
I would like to support this as well. I had thought about the idea of actually animating the original views when I built Hero. No good solutions came up during that time, So I decided to make Hero simple.

At this point, I am still not sure whats the best way of doing this.

I thought about having a `transferable` modifier. and some delegate callback on the view controller like this:
```swift
func targetStateForTransferable(view:UIView) -> HeroTargetState?
```

Suppose we have two view controllers: **A** & **B**
**A** can have an AVPlayerView with the modifier `transferable`.
When transitioning to **B**, Hero can ask **B** if it can accept the AVPlayerView. If **B** returns a non-nil **HeroTargetState**, then Hero can animate according to it. **B** can also keep the reference of the AVPlayerView at this time.

There is a delegate callback already when the transition is ended.
```swift
func heroDidEndTransition()
```
Thats where **B** can setup its constraints.

I am currently adding `HeroTargetState` to the framework. It basically holds view state informations and can be constructed from `HeroModifiers`.

Let me know what you think about this solution.
Luke

**Comment by futuretap** [comment]
So you would keep the `transferable` view in the `A.view` hierarchy for the duration of the transition and let **B** take it over and insert it in its view hierarchy after the transition is finished, right?

Sounds reasonable though it might be useful to support the other way as well to transfer the view at the beginning of the transition. In my concrete use case this is needed because **B** needs to control the map view during the transition. This might also be needed to achieve a specific view layering during the transition.

**Comment by lkzhao** [comment]
The view will not be in **A** nor **B**'s view hierarchy. It will be in a container view that Hero uses internally. But **B** can control its properties any time during the transition.

**Comment by futuretap** [comment]
OK, makes sense.

**Comment by lkzhao** [comment]
**B** will have to manually insert the view when the transition finishes. Since Hero won't be able to know the location to insert nor the layout system that **B** uses. But during the transition Hero handles the layout for you. It animates from what **A** has to the targetState that **B** gave.

This will probably be build into a **HeroPlugin**. Not into the main Hero components.
In fact, currently you can control animation like this by building a custom **HeroPlugin** yourself. I haven't written any documentations on **HeroPlugin** yet since it is still under development. But the feature is there and you can play around with it.

**Comment by lkzhao** [comment]
@futuretap This is implemented in 0.1.5. Checkout the new video player example in the example project. I will have documentation available soon.

**Comment by jwardle** [comment]
Can you document this? I am looking at the example code for the VideoPlayer transition in v1.1.0 and I cannot see it transitioning the actual live view of the AVVideoPlayer... the cell in the Examples Scene shows a UIImageView as the source view for the videoPlayer. You skip the opening scene so it appears as if the movie has started, but doesn't actually transfer any views between VCs.

**Comment by VanHoutte1337** [comment]
Any update on this? Has this feature been implemented?
