### ISSUE TITLE
Spring in hero modifire

### ISSUE THREAD

**Issue by chinmaykdas** [lkzhao/Hero#213]
Here i am trying some damping effect using hero modifire but when i am using the spring effect, the animation is too slow. we also can not fix the time because it is auto calculated. other modifires are working well in the project. 

Ex Code: .spring(stiffness: 0.5, damping: 0.3)

This is very slow. Please fix this.

**Comment by lkzhao** [comment]
0.5 and 0.3 is too small. Hero feed these number into CASpringAnimation. So something like `.spring(stiffness: 150, damping: 20)` would be a good number.

**Comment by lkzhao** [comment]
Cleaning Old Issues. Feel free to reopen.
