### ISSUE TITLE
Interactive Transition Tutorial Broken

### ISSUE THREAD

**Issue by GoldenJoe** [lkzhao/Hero#215]
In the sample app, the controller seems to dismiss immediately, making a new project and following the sample code, I can confirm that the call to `dismiss(animated: true, completion: nil)` simply dismisses the controller immediately.

The tutorial and code is found at:
http://lkzhao.com/2017/02/05/hero-interactive-transition.html

Additionally, it isn't clear how to really use interactive Hero transitions with a NavigationController, or what the difference is between using `Hero.shared.apply` vs setting `heroModifiers` on a view.

**Comment by iosdevben** [comment]
You need to set isHeroEnabled to true on the viewController that you wish to dismiss interactively.
