### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb)

### ISSUE THREAD

**Issue by haansplosion** [lkzhao/Hero#216]
Hi there, after updating to the latest version of Hero I am getting the error

```
fatal error: unexpectedly found nil while unwrapping an Optional value (lldb) 
```

On line 24 of **Lexer.swift:**
```
("\\-?[0-9.]+", { .number(Float($0)!, $1) }),
```
<img width="1443" alt="screen shot 2017-06-10 at 6 51 25 pm" src="https://user-images.githubusercontent.com/6058393/27001455-d260c608-4e0d-11e7-8d3b-ba0423b885ed.png">

**_Xcode - Version 8.3.3 (8E3004b)
Swift 3_**

**Comment by tmcelroy1** [comment]
I have the same issue. Did you ever resolve this issue?

**Comment by lkzhao** [comment]
Mind sending me your heroModifierString? looks like you have something like `.scale(.)`. where the float number is missing.
