### ISSUE TITLE
Different heroModifiers for present/dismiss?

### ISSUE THREAD

**Issue by GoldenJoe** [lkzhao/Hero#220]
Is there a way to apply different heroModifiers depending on whether a view is presented or dismissed?

Example:
`// Move in from the right when pushed`
`view.heroModifiers = [.translate(x: 50, y: 0, z: 0)]`

`// Exit to the left when popped`
`view.heroModifiers = [.translate(x: -50, y: 0, z: 0)]`

**Comment by LcTwisk** [comment]
I think you could either set the heroModifiers in `viewWillAppear` or `viewWillDisappear`. Or implement the `HeroViewControllerDelegate` as shown below

```
extension ViewController: HeroViewControllerDelegate {
    func heroWillStartAnimatingTo(viewController: UIViewController) {
        view.heroModifiers = [.translate(x: 50, y: 0, z: 0)]
    }
    
    func heroWillStartAnimatingFrom(viewController: UIViewController) {
        view.heroModifiers = [.translate(x: -50, y: 0, z: 0)]
    }
}
```

**Comment by lkzhao** [comment]
`1.0.0-alpha.1` now provides `.whenPresenting` & `.whenDismissing` modifiers.
