### ISSUE TITLE
This class is not key value coding-compliant for the key heroID

### ISSUE THREAD

**Issue by tayo119** [lkzhao/Hero#223]
Hi
I'm having problems with heroID 
Console says:
Failed to set (heroID) user defined inspected property on (UIButton): [<UIButton 0x100f1a700> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key heroID.

IsHeroEnabled on UIViewController is On 
and I have heroID's on the components, I don't know why is not working.

I try to import Basic.storyboard from examples to my project and is not working  either.

![captura de pantalla 2017-06-15 a las 11 14 35](https://user-images.githubusercontent.com/25578846/27175832-b811bb20-51c0-11e7-8f08-c84d7cf6b3e5.png)
![captura de pantalla 2017-06-15 a las 11 14 51](https://user-images.githubusercontent.com/25578846/27175831-b80bdf20-51c0-11e7-8e21-6b6959f53e88.png)

**Comment by DevHuangjb** [comment]
i also meet the problem ..how to solve the issue?
