### ISSUE TITLE
tranform to a tabbarviewcontroller, crash

### ISSUE THREAD

**Issue by AaronYin0514** [lkzhao/Hero#224]
Hero.swift, line 319

tabbarviewcontroller default selectedIndex is 9223372036854775807

if let tabBarController = vc as? UITabBarController,
       let viewControllers = tabBarController.viewControllers,
       tabBarController.selectedIndex < viewControllers.count,
       let delegate = tabBarController.viewControllers?[tabBarController.selectedIndex] as? HeroViewControllerDelegate {
      closure(delegate)
    }

**Comment by lkzhao** [comment]
should be fixed in the `develop` branch

**Comment by lkzhao** [comment]
https://github.com/lkzhao/Hero/issues/226
