### ISSUE TITLE
hero_unwindToViewController(with: UIViewController) Not working?

### ISSUE THREAD

**Issue by JoniVR** [lkzhao/Hero#225]
Is it possible that there is a bug with hero_unwindToViewController(with: UIViewController)?
It doesn't seem to work for me.. Could just be me, the Viewcontroller is loaded in the view hierarchy so that should not be the problem. I also did set the identifier in storyboard.

Here's a snippet of the code I'm using.

```
let LoginVC = storyboard?.instantiateViewController(withIdentifier: "Login")
hero_unwindToViewController(LoginVC!)
```

Thankyou for this awesome library btw. 😁

**Comment by lkzhao** [comment]
The loginVC must be the same instance that is already in your view controller stack. if your call `storyboard?.instantiateViewController(withIdentifier:)`, then you are initializing a new one.

One potential solution would be use something like: `hero_unwindToViewController(withClass: LoginViewController.self)`

**Comment by JoniVR** [comment]
Thanks for the reply, I tried what you suggested before, but then the animation doesn't seem to work for me (it's just using the default animation). 

Here are some of the lines I'm using: 

```
Hero.shared.setDefaultAnimationForNextTransition(.zoomOut)
Hero.shared.disableDefaultAnimationForNextTransition()
hero_unwindToViewController(withClass: LoginVC.self)
```

I tried with and without `Hero.shared.disableDefaultAnimationForNextTransition()` but that doesn't seem to make a difference.

**Comment by lkzhao** [comment]
Can you tell me more about what is the view controller hierarchy looks like?

The current implementation of `hero_unwindToViewController` requires that the `presentedViewController` of the `LoginVC` to have `isHeroEnabled` set to true.

If you are using `UINavigationController`, then the navigation controller's `isHeroEnabled` has to be true.

**Comment by JoniVR** [comment]
It's a system where we're using `keychain` & `Firebase`, basically a user logs in, we save the userID to `keychain` so the user can stay logged in (even when the app is closed and restarted).

So when we launch the app the user is taken directly into the app (without passing through the `LoginVC`), in that case, when the user logs out,  I am presenting the `LoginVC` with `Hero` animations (this part works). In case the user was logged out when launching the app, the `LoginVC` will become the `rootViewController` (set in Appdelegate), and in that case when the user logs in and then wants to log out I want to be able to get back to the `LoginVC` (which I don't dismiss), this is the part that is not working.

Hope this helps, let me know if it's still unclear to you, hoping this helps the library and doesn't take up too much of your time.

**Comment by lkzhao** [comment]
If you have LoginVC -> VCA -> VCB. And you want to unwind from B to LoginVC. You will need VCA to have isHeroEnabled set to true. Can you verify that?


A better solution would be to replace your rootViewController with LoginVC every time the user logs out. And once they login, replace the rootViewController with your normal VC.
```swift

    // any vc, once logged out
    let loginVC = LoginVC()
    HeroTransition().transition(from: self, to: loginVC, in: UIApplication.shared.keyWindow!) { (finished) in
      UIApplication.shared.keyWindow!.rootViewController = loginVC
    }


    // Login VC, once logged in
    let homeVC = homeVC()
    HeroTransition().transition(from: self, to: homeVC, in: UIApplication.shared.keyWindow!) { (finished) in
      UIApplication.shared.keyWindow!.rootViewController = homeVC
    }
```

**Comment by lkzhao** [comment]
Note that this transition API is made public only in the master branch. Not yet released on cocoapods. 

```
pod 'Hero', :git => 'https://github.com/lkzhao/Hero.git'
```

It is what `hero_replaceViewController` use internally.

**Comment by lkzhao** [comment]
Try it and let me know how it goes.

To configure your default animation. You can configure it through the HeroTransition object.
```
    let homeVC = viewController(forStoryboardName: "Basic")
    let transition = HeroTransition()
    transition.defaultAnimation = .fade
    transition.containerColor = .white
    transition.transition(from: self, to: homeVC, in: UIApplication.shared.keyWindow!) { (finished) in
      UIApplication.shared.keyWindow!.rootViewController = homeVC
    }
```

I will update the documentation with these new changes in the following weeks.

**Comment by JoniVR** [comment]
@lkzhao I'll try it out when I get the time, thanks for all the effort, much appreciated. I'll keep you updated!

**Comment by JoniVR** [comment]
Hi, 
just wanted to update you on the situation, I spent some time on trying to get what you suggested to work, but the project couldn't recognise it, even after rebooting.. so I had to revert...

I did try the following, the system works, but the hero animation does not work, it just gives me the default dismiss animation. (we just set a global boolean wheter LoginVC is active or not, which does effectively work, might not be the cleanest but it's for testing anyways)

The code is the following: 
    
```
        let sb = UIStoryboard(name: "Main", bundle: nil)
        let loginVC = sb.instantiateViewController(withIdentifier: "Login")
        Hero.shared.disableDefaultAnimationForNextTransition()
        Hero.shared.setDefaultAnimationForNextTransition(.zoomOut)
        loginVC.heroModalAnimationType = .zoomOut
        self.heroModalAnimationType = .zoomOut
        self.isHeroEnabled = true
        loginVC.isHeroEnabled = true
        
        if Config.LOGINVCACTIVE {
            
            hero_unwindToViewController(withClass: Login.self)
            print("UNWIND")
        } else {
            
            self.present(loginVC, animated: false, completion: nil)
            print("PRESENT")
        }
    }
```

So the problem is that when it should "unwind", it does unwind but without the animation (just using the default) any idea on this one? If I could get this to work then it would be fixed in that way. 

Thanks again! Sorry for the wait!

**Comment by JoniVR** [comment]
Ok, little update, I fixed the issue. 

The problem was that the VC that was executing this code was part of a `UITabBarController`.
In order to make it work, I had to use `isHeroEnabled = true` inside my `UITabBarController` then I just used `hero_unwindToViewController(withClass: Login.self)` and it worked flawlessly!

Thanks for your time!
Hope this may help other people in the future.
