### ISSUE TITLE
UITabBarController loosing VCs

### ISSUE THREAD

**Issue by hernangonzalez** [lkzhao/Hero#226]
Looks like tapping quickly to switch tabs while an animation is in progress causes the lost of all the controllers. I ended up with a white screen for all the tabs.

**Comment by hernangonzalez** [comment]
Is there a way to disable user interaction while in progress here, or forcing it to complete before triggering a new one?

**Comment by wakakajp** [comment]
a same issueO.O

**Comment by lkzhao** [comment]
Fixed in the `develop` branch.

**Comment by hernangonzalez** [comment]
thanks @lkzhao do you have an idea and when you'll make a new release?

**Comment by lkzhao** [comment]
Should be soon. maybe by the end of this week. I am doing a major cleanup internally to prepare for the real 1.0 release. want to be more developer friendly and support iOS 11 as well.
