### ISSUE TITLE
Objective-c How to define `heroModifiers`?

### ISSUE THREAD

**Issue by wwdc14** [lkzhao/Hero#227]
If `heroModifiers` have multiple parameters should be defined, can provide examples?

**Comment by lkzhao** [comment]
Maybe write a swift wrapper?
```swift
func applyXXXXHeroModifiers(to view:UIView) {
    view.heroModifiers = [.whenDismissing(.scale(0.5))]
}
```

 I will be deprecating string & Objc support soon when swift 4 comes out.

**Comment by wwdc14** [comment]
非常感谢你解答了我的疑惑！看来我也要对swift进行支持！再次感谢你的开源库！

**Comment by lkzhao** [comment]
不客气！
