### ISSUE TITLE
CAMediaTimingFunction extension has internal access level

### ISSUE THREAD

**Issue by xaverlohmueller** [lkzhao/Hero#228]
The extension to `CAMediaTimingFunction` (in `CAMediaTimingFunction+Hero.swift`) can't be accessed from outside the pod because it has `internal` access level.

<img width="865" alt="bildschirmfoto 2017-06-28 um 12 38 38" src="https://user-images.githubusercontent.com/16212751/27633324-fa3d115a-5bfe-11e7-84bb-d55b82cfeaf3.png">

Is this intentional?

**Comment by lkzhao** [comment]
Not intensional. Will be fixed.

**Comment by xaverlohmueller** [comment]
❤️ Thanks for your quick reply!

**Comment by lkzhao** [comment]
fixed: https://github.com/lkzhao/Hero/commit/1bf3d6bea9358f15ba350ec789a8cdc3626b7a9f

**Comment by leeprobert** [comment]
Should this work in Alpha because I get the same error.
![casestudyone_storyboard](https://user-images.githubusercontent.com/151336/30655746-c9a7946c-9e29-11e7-8864-1c25100ddef6.png)
