### ISSUE TITLE
Hero call animate() crash.

### ISSUE THREAD

**Issue by mahomealex** [lkzhao/Hero#229]
crash at:context.unhide(view: toView), because both fromViewController and toViewController is nil. should add a basic protection.

How to produce: Start any transaction and setup a pangesture to go back, then pan quickly, it's about 1 in 10 or 20, then you will get it. thanks.

**Comment by PatrickSCLin** [comment]
duplicate ?

**Comment by PatrickSCLin** [comment]
#203
