### ISSUE TITLE
Transition to a CollectionView

### ISSUE THREAD

**Issue by stevejcox** [lkzhao/Hero#230]
Hi there,

Having an issue where I am navigating to a screen with a CollectionView. I have cells that have heroID's attached, however the cells are not loaded prior to the transition. Is there a right way of delaying Hero to capture the snapshots?

The data is available, so it's not a case of waiting for a network request.

Thanks,
Steve

**Comment by stevejcox** [comment]
Got it working using: .useLayerRenderSnapshot

**Comment by ergunkocak** [comment]
.useLayerRenderSnapshot causes black boxes in transparent places of target view :(
