### ISSUE TITLE
extendedLayoutIncludesOpaqueBars cause previous ViewController has wrong layout

### ISSUE THREAD

**Issue by PatrickSCLin** [lkzhao/Hero#233]
after push a new ViewController which has set extendedLayoutIncludesOpaqueBars = true (make view is fullscreen)

I got wrong layout if I pop viewController, all previous viewControllers just reduce 44px,

**Comment by andreamazz** [comment]
I'm having the same issue. Opaque navigation bar, when pushing a new view controller that requires extended edges and popping back, the previous layout is shifted 44px (the navigationbar height) down.

**Comment by remithaunay** [comment]
@lkzhao Hello, I also reproduced it, could you please reopen this issue ? If you have any solutions/fixes, could you tell us ?
