### ISSUE TITLE
Cell animation view overlaps tabbar

### ISSUE THREAD

**Issue by protspace** [lkzhao/Hero#235]
I'm wondering if there any way to avoid tabbar overlapping during this case when cell is partly visible?

https://www.dropbox.com/s/wy62ktq29hw8rnl/IMG_6976.MOV

**Comment by lkzhao** [comment]
You can apply some heroModifiers to the tabbar and make it appears at the top. Try this first:
 `[.useGlobalCoordinateSpace, .forceAnimate]`

**Comment by protspace** [comment]
thanks @lkzhao it helped!

**Comment by StarWars** [comment]
@lkzhao it doesn't seem to work on iOS 11. Any ideas what modifiers should I try?

**Comment by StarWars** [comment]
I just reviewed other issues and one of the suggestions that helps to fix overlapping was the following: ` .beginWith([.zPosition(10)])`
So the working solution for the views overlapping tab bar is adding the following modifiers to the tabbar:
`[.useGlobalCoordinateSpace, .forceAnimate, .beginWith([.zPosition(10)])]`

**Comment by barankaansert** [comment]
I have same issue, anyone solve this problem ? 

when i use [.useGlobalCoordinateSpace, .forceAnimate, .beginWith([.zPosition(10)])] modifiers, whole screen has fade animation and background color of this screen is gone.

**Comment by EgorkZe** [comment]
So, I also get this flickering, can anyone help tp solve problem??
