### ISSUE TITLE
Wrong frame for UIView in UIScrollView

### ISSUE THREAD

**Issue by andrealufino** [lkzhao/Hero#237]
Hello guys. This library in incredible! Congratulations!
I'm using it in an app and I'm trying to make a transition similar to the City Guide in the example. The problem is that the first view is embedded into a UIScrollView that can be zoomed. When I tap on this view the effect is perfect, but when I come back the view is animated with wrong size because of the zoom of the parent view. I hope I explained good the problem. Here a little scheme to understand the hierarchy. 

#### VC1
UIView
-- UIScrollView
---- UIView (contentView)
------ UIView (heroID = "hero")

#### VC2
UIView
-- UIView (heroID = "hero")

**Comment by andrealufino** [comment]
![aboutus 1](https://user-images.githubusercontent.com/758939/28183444-c53e159a-680f-11e7-8d57-0a7a75421083.gif)
This is the first scenario where everything is working fine. `zoomScale` is 1 here

![aboutus 2](https://user-images.githubusercontent.com/758939/28183456-d8b69264-680f-11e7-9cf4-6d566e281871.gif)
This is when `zoomScale` is different from 1

**Comment by lkzhao** [comment]
Can you send me a demo project so I can better help you debug?

**Comment by andrealufino** [comment]
Hello @lkzhao and thanks for your answer. Here it is a simple project : https://github.com/andrealufino/HeroScrollViewTest

**Comment by andrealufino** [comment]
I've just updated the issue adding a detail I forgot before. Between the `UIScrollView` and the `UIView` to animate there is a `contentView`.

**Comment by andrealufino** [comment]
Another information that I missed is that I'm using the cocoapod library, version 0.3.6. I tried installing 1.0.0 alpha 3, but nothing changed.

**Comment by lkzhao** [comment]
This is an unimplemented feature. Basically when a view is matched, its superview's transform is not captured by Hero. In your case the contentView has the scaled transform but your cell doesn't. So when Hero matched the cell, it doesn't see that it has been transformed. 

I will see if I can do something with it. Sounds like something that would be useful.

**Comment by lkzhao** [comment]
Should be fixed in the latest master.

**Comment by andrealufino** [comment]
Yes, it's perfectly fixed. I tried it and everything seems to be ok. Great work!

**Comment by sagarmahindrakarshipr** [comment]
its still not working in my case, I have collectionView and in didselect I am enabling the hero ID to cell but next time its is automatically getting another adjacent cell's content
