### ISSUE TITLE
Should I import the cocoapods version or the one on the master branch? 

### ISSUE THREAD

**Issue by andrealufino** [lkzhao/Hero#239]
Which version of Hero should we use if we want to have the most stable version? The one on the cocoapods or the one that is on the master branch. Maybe there should be an indication about this in the README.

**Comment by lkzhao** [comment]
Most stable version should always be the one on cocoapods. There might be new fixes and patches that are not yet available in the cocoapods version but exists in the master branch. But keep in mind that I might break the master branch sometimes.

**Comment by andrealufino** [comment]
Ok, clear. Do you plan to publish the master branch on the cocoapods soon? I need to use it in production and I want the most stable version possible

**Comment by brandy2015** [comment]
Expecting  the master branch on the cocoapods soon.
