### ISSUE TITLE
Buddy Build - Build Failed

### ISSUE THREAD

**Issue by otymartin** [lkzhao/Hero#24]
Im using buddybuild.com and it keeps spitting out this error causing the build to fail.

```swift
** BUILD FAILED **
170
    The following build commands failed:
171
    	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
172
    	CompileSwift normal x86_64 /tmp/sandbox/workspace/Pods/Hero/Hero/CAMediaTimingFunction+Hero.swift
173
    	CompileSwift normal x86_64 /tmp/sandbox/workspace/Pods/Hero/Hero/HeroDefaultAnimatorViewContext.swift
174
    (3 failures)

**Comment by lkzhao** [comment]
Probably related to #7
I am using swift 3.0.2 with no problem. What's the swift version that buddybuild uses?

**Comment by otymartin** [comment]
@lkzhao `SWIFT_VERSION=3.0`

**Comment by lkzhao** [comment]
Does buddy build support v3.0.2? I would try that. Please let me know if that works

**Comment by otymartin** [comment]
@lkzhao Yes it appears to work with the latest Xcode version.
