### ISSUE TITLE
Issues with keyboard at transition

### ISSUE THREAD

**Issue by luisfelipesv** [lkzhao/Hero#241]
I have two kind of issues

### First issue
I'm trying to present a `UIViewController` and show the keyboard when it loads or at `viewWillAppear()`. I also have a constraint that changes when the keyboard appears. But with the transition animation I have two issues, the first one is that the constraint doesn't update until the transition animation ended and the second one is the the keyboard is dismissed at the end of the transition too. This happens when I present and when I dismiss the view, both of the `UIViewControllers` that have `UITextFields` have the same code. Here's the code and a gif example. :

```swift
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillShow), name: Notification.Name.UIKeyboardWillShow, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide), name: Notification.Name.UIKeyboardWillHide, object: nil)
        
        firstNameField.becomeFirstResponder()
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        NotificationCenter.default.removeObserver(self, name: Notification.Name.UIKeyboardWillShow, object: nil)
        NotificationCenter.default.removeObserver(self, name: Notification.Name.UIKeyboardWillHide, object: nil)
        
    }
    
    
    // MARK: - Custom functions
    
    // MARK: Keyboard
    
    func keyboardWillShow(notif: Notification){
        keyboardWillMove(notif: notif, hidding: false)
    }
    
    
    func keyboardWillHide(notif: Notification){
        keyboardWillMove(notif: notif, hidding: true)
    }
    
    func keyboardWillMove(notif: Notification, hidding: Bool){
        let userInfo = notif.userInfo!
        
        let animationDuration = userInfo[UIKeyboardAnimationDurationUserInfoKey] as! Double
        let keyboardEndFrame = userInfo[UIKeyboardFrameEndUserInfoKey] as! CGRect
        let convertedKeyboardEndFrame = view.convert(keyboardEndFrame, from: view.window)
        let rawAnimationCurve = notif.userInfo![UIKeyboardAnimationCurveUserInfoKey] as! UInt
        let animationCurve = UIViewAnimationOptions.init(rawValue: rawAnimationCurve)
        
        bottomLayoutConstraint.constant = hidding ? 20 : view.bounds.maxY - convertedKeyboardEndFrame.minY + 16
        
        //view.layoutIfNeeded()
        
        UIView.animate(withDuration: animationDuration, delay: 0.0, options: [.beginFromCurrentState, animationCurve], animations: {
            self.view.layoutIfNeeded()
        }, completion: nil)
        
    }

```

![ezgif-4-e0cf147ba1](https://user-images.githubusercontent.com/9010947/28442504-d43c3852-6d6d-11e7-98dc-222904e09b88.gif)

### Second issue

While looking for ways to solve that problem I decided to show the keyboard after the transition ended, and that was working well until I present a `UIViewController` from the `UIViewController` that was showing the keyboard, the keyboard kind of jumps up and down in a weird way, The code is the same as above except of `firstNameField.becomeFirstResponder()` that is now located inside `viewDidAppear()`. Here's the gif example now.

![ezgif-4-e921f8bc6e](https://user-images.githubusercontent.com/9010947/28443131-67468078-6d71-11e7-9868-925c8290d26d.gif)

As you can see the dismiss here looks okay (the only thing that looks weird in the dismiss is the constraint animation and I can solve it by removing the `keyboardWillHide` function). 

Is there a way to present the next vc without the jumping keyboard? or a way to show the keyboard at `viewDidLoad()` or `viewWillAppear()` with the constraint related to the keyboard updated before the transition animation?

Thanks in advance!

**Comment by cemaleker** [comment]
For future reference; 

While completing the transition, hero removes the container view and adds `toView` to the window to finish the transition. When the container view is removed from window hierarchy, the keyboard dismisses automatically. If you don't want the keyboard to hide after transition completes, you should add following delegate method.

    func textViewShouldEndEditing(_ textView: UITextView) -> Bool {
        return !isBeingPresented
    }
