### ISSUE TITLE
Duration for `heroNavigationAnimationType`

### ISSUE THREAD

**Issue by VidurMalik** [lkzhao/Hero#242]
I'm trying to set a `.duration` modifier for a navigation controller default transition:
```swift
destination.isHeroEnabled = true        
self.navigationController?.isHeroEnabled = true
navigationController?.heroNavigationAnimationType = .selectBy(presenting: .slide(direction: .left), dismissing: .slide(direction: .right))
destination.view.heroModifiers = [.duration(50.0)]
```
However, this does not work. Any advice?

**Comment by zvonicek** [comment]
I'm interested in this as well. Especially in combination with `fade` animation.

**Comment by chrisscholly** [comment]
Any advice here?

**Comment by philipengberg** [comment]
@lkzhao can we get an answer on this? This is related as well https://github.com/HeroTransitions/Hero/issues/234

**Comment by alexanderkhitev** [comment]
Hey @philipengberg ! Any news?

**Comment by Archa30** [comment]
can anyone tell how to achieve this?
