### ISSUE TITLE
How to enable default iOS back swipe gesture?

### ISSUE THREAD

**Issue by Banck** [lkzhao/Hero#243]
Hello!
If you use UINavigationController you have back swipe gesture to back to previous controller. But when Hero is enabled I don't have this behaviour. How can I enable default iOS back swipe gesture if Hero is enabled?
Thank you!

**Comment by beneiltis** [comment]
+1

**Comment by beneiltis** [comment]
Any news on this topic?

**Comment by lkzhao** [comment]
UIKit disables the default back gesture if you use any custom transitions. You can unset the navigationControllerDelegate to get back the back gesture. or implement your own back gesture through interactive transition.

**Comment by beneiltis** [comment]
Thanks ikzhao :-)

Inside viewDidLoad() of the destination-ViewController following line does the trick:
`navigationController?.interactivePopGestureRecognizer?.delegate = nil`

**Comment by krishna66vamshi** [comment]
[https://stackoverflow.com/questions/34942571/how-to-enable-back-left-swipe-gesture-in-uinavigationcontroller-after-setting-le/43433530#43433530](url)

**Comment by krishna66vamshi** [comment]
https://stackoverflow.com/questions/34942571/how-to-enable-back-left-swipe-gesture-in-uinavigationcontroller-after-setting-le/43433530#43433530

**Comment by kuyazee** [comment]
#343 works afaik
