### ISSUE TITLE
Transitioning Glitch using hero_replaceViewController 

### ISSUE THREAD

**Issue by morgan-legal** [lkzhao/Hero#244]
Hi Luke!

First of all, well done on the Hero library, it’s pretty amazing 😉

I’m creating an issue because i’ve encountered issues while transitioning between controllers.

To give you an overview (I’ve left out some unnecessary information) of my projet’s interaction with Hero:

I have a root controller, let’s call it HomeVC, which has a "button" presenting a flow of multiple controllers (let’s call them: FlowVC1, FlowVC2 … FlowVCX).

```
HomeVC {
    buttonTapped {
        present(FlowVC1, animated: true, completion: nil)
    }
}
```

**The way the flow works**:
One object to control the actual flow (state machine that will tell us which controller is the next or the previous). It contains all the flow controllers instances. 
To transition to a new controller of the flow the “updateController” method will be triggered. I do not use navigation controller. 
 
```
FlowController: NSObject {

    private var flowVC1 = MyVC1()
    private var flowVC2 = MyVC2()
    ...
    private var flowVCX = MyVCX()

    private func updateController(from fromVC: UIViewController, to toVC: UIViewController) {
        from.hero_replaceViewController(with: toVC)
    }    
}
```

**The issue i’m facing**:
Let’s say I’m on FlowVC1, clicking on the “next” button to present the FlowVC2, the method “updateController(from: FlowVC1, to: FlowVC2)” is triggered. The transition happens and for some unknown reason FlowVC2’s “viewDidAppear” is triggered multiple times (the method hero_replaceViewController is only triggered one time). Triggered 3 times actually using the version 0.3.6 and 2 times using the latest 1.0.0.alpha-4 (i’m using Carthage for dependencies). 
Actually the problem is not really coming from the number of viewDidAppears but from the fact that my HomeVC (the root controller, presenting the first controller of the flow) seems to have joined the party. Right after the first viewDidAppear of the FlowVC2, the HomeVC is shown (so fast that it only seems to be a transition glitch), then the FlowVC2’s viewDidAppear is triggered a second time. 

Below, you can see the glitch, it is quite fast but happening. The white part is my HomeVC. 

![glitchwhitehd](https://user-images.githubusercontent.com/11411520/28669951-c053019a-72d6-11e7-9f90-cbfaa68e1470.gif)

A simple project recreating that same issue can be found [here](https://www.dropbox.com/sh/6ylxn8dapq5c7p4/AABs0AmgFOOnS3pDVr_Rv17da?dl=1). You'll need to run "carthage bootstrap --platform iOS" in order to build the project.

Any ideas ? Thoughts ?

Thanks,
Morgan

**Comment by lkzhao** [comment]
Yes, UIKit doesn't provide a way to actually replace a view controller in the view controller stack. The way that hero does it is the following
1. do the transition in-place first by inserting the next view controller's view into the view stack
2. the dismiss and present the view controller without any animation.

When the view is inserted in step 1. UIKit calls viewDidAppear. And during step 2, it does it again.

Something that I wanted to fix. but it cant be done without some method swizzing. I would recommend you to always use `present(viewController:animated:completion:)` to do the transition and use `hero_unwind` once you finished with these view controllers.

**Comment by morgan-legal** [comment]
Thank you for your response.

Do you plan to fix this issue any time soon ? If you had something in mind to fix this maybe I can help and try to implement it.

I don't really understand the use of present and unwind. If I do use present and only unwind at the very end then all my presented controllers triggers their viewDidAppear. 
Ex: 
``` 
HomeVC 
- HomeVC presents Flow1VC
  - Flow1VC presents Flow2VC
    - Flow2VC presents Flow1VC
      - Flow1VC unwindToRoot (HomeVC)
```
Doing it this way, the hero_unwindToRootViewController() triggers :
```
viewDidAppear of Flow2VC
viewDidAppear of Flow1VC
viewDidAppear of HomeVC
```
Maybe something that I'm doing wrong ? Any idea ?
