### ISSUE TITLE
Unable to Present View Controller modally with Hero animation

### ISSUE THREAD

**Issue by robmontesinos** [lkzhao/Hero#247]
I have been unable to perform Hero animation modally, i.e. present, but animation works well for pushViewController from navigationController.

```
            let searchVC = SearchVC(persons: self.persons)
            searchVC.isHeroEnabled = true
            
            present(searchVC, animated: true, completion: nil)
```

When I remove isHeroEnabled on searchVC, searchVC is presented with the standard UIKit animation. I am using iPhone 6s simulator to avoid iPhone 7 bug.

I don't know what I am doing wrong. A little help please with an example maybe? Thank you. This library rocks.

**Comment by tommyle** [comment]
Did you set the animation?
`searchVC.heroModalAnimationType = HeroDefaultAnimationType.zoom
`

**Comment by robmontesinos** [comment]
@tommyle Thank you sir. That did the trick. Is setting the AnimationType also required for navigationController pushes?
