### ISSUE TITLE
Custom NavigationController Delegate

### ISSUE THREAD

**Issue by felix-dumit** [lkzhao/Hero#25]
I have a custom segue class that instantiates a `UINavigationController` class like this:

```swift
class CustomNavSegue: UIStoryboardSegue {

    override func perform() {
        let nav = ModalNavigationController(rootViewController: destination)
        nav.isHeroEnabled = true
        nav.modalPresentationStyle = .overCurrentContext
        source.present(nav, animated: true, completion: nil)
    }
}
``` 

In the `ModalNavigationController`  `viewDidLoad` I set `delegate = self` since I need to perform a custom action on:

```swift
extension ModalNavigationController: UINavigationControllerDelegate {
    func navigationController(_ navigationController: UINavigationController,
                              willShow viewController: UIViewController,
                              animated: Bool) {
        //need to configure something on viewController.view
    }
}
```

However, when I set `nav.isHeroEnabled` I see that the navigationController's delegate gets set to `Hero.shared`. 
Basically both need to be the delegate even though they need different method callbacks.

Do you have any ideas for solutions? 
Maybe `Hero` could expose an extra `navigationDelegate:UINavigationControllerDelegate`  property that only replays the callbacks it receives (probaby worth doing for other delegates as well).

**Comment by lkzhao** [comment]
So you want to have your own navigation delegate while having hero enabled? It is doable if I expose some of the internal Hero methods. But can you use 'viewWillAppear' or 'viewDidAppear' instead?

**Comment by lkzhao** [comment]
You can probably do something like this:
```swift
extension ModalNavigationController: UINavigationControllerDelegate {
    func navigationController(_ navigationController: UINavigationController,
                              willShow viewController: UIViewController,
                              animated: Bool) {
        //need to configure something on viewController.view
    }

    func navigationController(_ navigationController: UINavigationController, animationControllerFor operation: UINavigationControllerOperation, from fromVC: UIViewController, to toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? {
        return Hero.shared.navigationController(navigationController, animationControllerFor:operation, from:fromVC)
    }
  
    func navigationController(_ navigationController: UINavigationController, interactionControllerFor animationController: UIViewControllerAnimatedTransitioning) -> UIViewControllerInteractiveTransitioning? {
        return Hero.shared.navigationController(navigationController, interactionControllerFor:animationController)
    }
}
```

**Comment by lkzhao** [comment]
`Hero.shared` is not avaliable on cocoapods and carthage yet. The current master contains a major API change. Will wait a few day before releasing the next version. In the mean time, you can use
```
pod "Hero", :git => 'https://github.com/lkzhao/Hero.git'
```

**Comment by felix-dumit** [comment]
I had to add `nav.transitioningDelegate = Hero.shared` instead of setting `isHeroEnabled`.
It turns out those two delegate methods are not being called at all. (even with setting `isHeroEnabled`) - is that expected?

**Comment by lkzhao** [comment]
Oh. I guess I didn't understand your question clearly. 

Yes, for the modal presentation you only have to set 'transitionDelegate'. Hero also sets the navigation controller's delegate for animating navigation controller's child view controllers. If you don't need that functionality then it is ok to just set the 'transitionDelegate'
