### ISSUE TITLE
crash when matched view width or height is 0

### ISSUE THREAD

**Issue by k-nar** [lkzhao/Hero#250]
caused by HeroCoreAnimationViewContext : setSize

subview.center = CGPoint(x: center.x / oldSize.width * newSize.width, y: center.y / oldSize.height * newSize.height)  

<- divide by 0 if oldSize or newSize width or height is 0

**Comment by CoderFenchHU** [comment]
the same crash as you.

**Comment by spensko** [comment]
any fixes for this?

**Comment by anatoliykant** [comment]
I had a similar problem. I spent more than 4 hours on it.
I looked at the logs that the fall occurs at oldSize.height: 0.0.
I use Story boards to work and decided to see what is wrong.
As a result, it turned out that the textLabel had no height construct.
