### ISSUE TITLE
Animation works only if heroModifiers in storyboard

### ISSUE THREAD

**Issue by Faisal-AlNeela** [lkzhao/Hero#252]
When I add modifiers in storyboard the animation works properly, but if I add heroModifiers programmatically it doesn't work!!
I triad with buttons and views the same problem!!!

**Comment by Narsail** [comment]
Can confirm that. In my current project i don't use the storyboard. Therefore I tried a lot of stuff to understand why my views don't animate as expected. The heroModifiers are not applied :(

**Comment by liueast** [comment]
Same problem here. Any workaround?
