### ISSUE TITLE
Hero causing issues with other 3rd party UI library to hang

### ISSUE THREAD

**Issue by WilliamHua** [lkzhao/Hero#256]
I'm not 100% sure if Hero is the root cause of the issue.

In my app I am using another 3rd party library [NVActivityIndicatorView](https://github.com/ninjaprox/NVActivityIndicatorView) as a loading indicator when making network requests.

Before enabling the usage of the Hero library, my NVActivityIndicatorView was working. 

After enabling the usage of Hero, my NVActivityIndicatorView hangs for some time (apx 1 - 5 seconds) before the animation begins. 

I believe the NVActivityIndicatorView only hangs AFTER I have used the Hero library for an animation.

For example, if I use my app, and only use the screens with only the default iOS transitions, the NVActivityIndicatorView works fine.

If I enter a screen using a Hero animation, the next time the NVActivityIndicatorView pops up, it starts hanging.

Another observation is that the hanging gets worse the more animations I use from Hero. If I only enter a screen once with the Hero animation, it hangs for a few hundred milliseconds. The longer I use the app, the more it the animation hangs. 

Relevant source files for the NVActivityIndicatorView is [here (the specific animation I use)](https://github.com/ninjaprox/NVActivityIndicatorView/blob/master/NVActivityIndicatorView/NVActivityIndicatorView/Animations/NVActivityIndicatorAnimationLineScalePulseOut.swift) and [here (the general view I am adding to my loading indicator container view)](https://github.com/ninjaprox/NVActivityIndicatorView/blob/master/NVActivityIndicatorView/NVActivityIndicatorView/NVActivityIndicatorView.swift)

I am currently testing this on an iPhone 7, iOS 10.3.3 compiled with Xcode 9 beta 5 / Xcode 8.3.3.

Does anyone have any ideas what might be causing this / where to begin looking to debug the issue?

**Comment by schrismartin** [comment]
I too am having this issue. I am using `MBProgressHUD` alongside `Lottie` as a progress indicator, and while we're experiencing less hang-time, we do experience some. The amount of hang time does appear to be contingent on the number of Hero transitions that have been performed up to that point.

**Comment by lakersr8ers** [comment]
I found a workaround for this issue, I was experiencing the same thing with UIActivityIndicatorView. The solution is to wait until the Hero animation you are performing has completed before attempting to call startAnimating. This is what solved the problem for me.

**Comment by pointspy** [comment]
The reason is animation.beginTime = CACurrentMediaTime(). If you remove this command , then the delay will be gone.

**Comment by lkzhao** [comment]
Your view is captured as a snapshot so any animation during the transition will not be shown. Use (.useNoSnapshot) might fix it

**Comment by zvonicek** [comment]
I confirm I have the same problem when I call `startAnimating` on `UIActivityIndicatorView` in `viewDidLoad`. If I disable the Hero for the transition the problem disappears. Still looking for a solution to this.
