### ISSUE TITLE
heroID transitions does not work fine with custom UICollectionViewFlowLayout

### ISSUE THREAD

**Issue by pchernovolenko** [lkzhao/Hero#257]
I have two labels with text "Series" on both controllers with the same heroID. While updating transition between two controllers I see [strange behavior](https://www.dropbox.com/s/9ejzmft80h1w64g/Hero_Custom_UICollectionViewFlowLayout.mov?dl=0) with these labels transition animation. 

Following code is used for updating transition state:

```
func handlePan(gestureRecognizer:UIPanGestureRecognizer) {
        
        let translation = panGR.translation(in: nil)
        let progress = abs(translation.y) / view.bounds.height
        
        switch panGR.state {
        case .began:
            dismiss(animated: true, completion: nil)
        case .changed:
            Hero.shared.update(progress: Double(progress))
        default:
            if progress + panGR.velocity(in: nil).y / view.bounds.height > 0.3 {
                Hero.shared.end()
            } else {
                Hero.shared.cancel()
            }
        }
    }
```

Please help me. It's really looks very strange, all works good only on the first cell

**Comment by omarthen3rd** [comment]
Did you find any solutions?

**Comment by mad102190** [comment]
I'm seeing the same exact issue on my end. Have you found a solution?
