### ISSUE TITLE
pan quickly and app seems dead

### ISSUE THREAD

**Issue by mahomealex** [lkzhao/Hero#259]
When we add panGesture to custom transaction progress to a single UIImageView, that's a probablity app seems dead if you pan fast. It happens like 10% in my  7PLUS. Your can try this on your demo: enter ImageViewController and just pan. By using Facebook's FLEX to move views away, and add some log, I found the problem and solved it. Here is the fixed code:
open func animate() {
// fullScreenSnapshot is general and add to subview. need to remove.
    guard let _ = toViewController, let _ = fromViewController else {
      fullScreenSnapshot?.removeFromSuperview()
      complete(finished: true)
      return
    }
    guard state == .starting else { return }
    state = .animating

**Comment by leeprobert** [comment]
Can you confirm what you are seeing here? Sometimes my app appears to completely freeze, although it doesn't crash. It is unrecoverable, and impossible to replicate. From what I can gather from your code above, it creates a fullscreen snapshot that in some circumstances isn't being removed?

**Comment by mahomealex** [comment]
Yep, it's the same situation I discribed.  Add FLEX. to check what's happenning. Or just copy my code at the right pisition and u will see problem solved.

**Comment by leeprobert** [comment]
I implemented your code and added a breakpoint with a log. I've caught a few potential freezes so I can confirm that this is an issue with interactive transitions. Fast swipes still behave strangely however; sometimes my next view appears complete without any animation. At least it isn't crashing though.

**Comment by HiroshiHorie** [comment]
I'm also having this issue, seems ok on the Simulator but freezes on the device if i do a quick pan, like a flick.

**Comment by yunzixun** [comment]
have same issue. HiroshiHorie's solution won't fix.  need help.

**Comment by HiroshiHorie** [comment]
@bradphilips Yes, but it's a really hacky(not-recommended) workaround. I hope this issue gets fixed so I don't have to use this workaround.

**Comment by pnecas** [comment]
@HiroshiHorie This works so fine. Thanks~
