### ISSUE TITLE
Slow on iOS 11

### ISSUE THREAD

**Issue by jvichub** [lkzhao/Hero#260]
I'm testing a project on an iPad with iOS 11 beta, and transitions are slow, kinda choppy. 

Is that a known issue? Anybody got any hints on what could I do?

The same project on a device with iOS 10 is running fine.

**Comment by AAAstorga** [comment]
Also on iOS 11, when transitioning from a collection view cell to a view controller, there is a brief flash of blackness. 
This is as of iOS 11 beta 9

**Comment by iosdevben** [comment]
I'm getting a crash (SIGABRT) in `HeroCoreAnimationViewContext.canAnimate` when trying to present modal view controllers in Xcode 9 beta 6.

**Comment by JohannesSteib** [comment]
I'm encountering the same problem as @jvichub. Using iOS 11 beta 9 and Hero 0.3.6 the the transition between ViewControllers is flickering.
On iOS 10.3 it is working smoothly.

**Comment by mwhitt** [comment]
I'm experiencing the same flickering as @jvichub when defining a hero modal animation type to a navigation controller in iOS 11 GM. The modal transition works fine, the flickering happens when pushing or popping onto the nav controller.

**Comment by mwhitt** [comment]
Someone mentioned about needing better cleanup for custom modal transitions in iOS 11 but I was unable to find examples or more information. Does anyone else know what he is talking about and where to look in Hero?

**Comment by baims** [comment]
I'm having the same problem on iOS 11 when trying to push/pop into a UINavigationController. Same code is working fine on iOS 10.3.3. Any thoughts ?

**Comment by NikKovIos** [comment]
Same problem(

**Comment by RayanSaeed** [comment]
Same problems here..

**Comment by jvichub** [comment]
I found out what was causing the slowdown was that I was doing a drop shadow operation on a UIView. I removed that and now it's back to normal.

**Comment by mwhitt** [comment]
I've added an example in a fork that demonstrates the custom navigation flash bug in iOS 11:
https://github.com/mwhitt/Hero

What is needed to re-create is a custom modal animation to a UINavigationController which sets the `heroModalAnimationType`. It also needs to hide the navigation top bar. Now anytime if you pop or push you will see a flash on iOS 11.

**Comment by NikKovIos** [comment]
![example_hero_bug](https://user-images.githubusercontent.com/16647690/30739431-f5852d8e-9f95-11e7-9d69-5f9581bceb95.gif)
Here is the bug in new ios with hero `fade` transition. The back button overlap another back button. In ios 10 everything was all right.

**Comment by konroj** [comment]
Yeah, iOS11 & iPhone 7 flashes after several pushes in UINavigationController.
iPhone 6s with iOS11 works fine.

**Comment by wassimseif** [comment]
is anyone still getting this flashing effects? i updated to Hero 1.0.0
