### ISSUE TITLE
Stuck Setting The Animation Type With Objective-C

### ISSUE THREAD

**Issue by OlyRice** [lkzhao/Hero#267]
Hello

I really like the framework but I'm a bit stuck trying to get it to work with Objective-C. I've installed through Coca without a problem and imported the headers. I am also using the following [tutorial](https://medium.com/the-code-community/hello-x-cool-swift-3-transition-framework-ddada37db819) as a reference point because I am trying to change the transitions between UIViewControllers within a UINavigationController.

Now using the tutorial I can get the following bit of code to work, it only however shows the transition moving in from right to left.

`- (IBAction)navigateToTaskList:(id)sender {
    
    UIStoryboard *sb = [UIStoryboard storyboardWithName:@"Main" bundle:nil];
    UIViewController *vc = [sb instantiateViewControllerWithIdentifier:@"TaskList"];
    
    //[vc setHeroModalAnimationTypeString:@"cover(up)"];
    
    [self heroReplaceViewControllerWith:vc];
     
}`

Can someone please show me how to set the animation type? I am not sure how to convert the following line of code into the Objective-C equivalent.

`heroModalAnimationType = .zoomSlide(direction: HeroDefaultAnimationType.Direction.left)`

I tried using the following but it doesn't seem to make a difference.

` //[vc setHeroModalAnimationTypeString:@"cover(up)"];`

**Comment by CavalcanteLeo** [comment]
@ilkzhao why did you close with any answer? 
I need this help too!
