### ISSUE TITLE
Apple rejects apps with Hero because plist has version 1.0.0-alpha.

### ISSUE THREAD

**Issue by imougy** [lkzhao/Hero#268]
Message from Apple
ERROR ITMS-90060: “This bundle is invalid. The value for key CFBundleShortVersionString ‘1.0.0-alpha.5’ in the Info.plist file must be a period-separated list of at most three non-negative integers.”

**Comment by lkzhao** [comment]
Will update Info.plist to be 1.0.0

**Comment by lkzhao** [comment]
master is updated. 
```
  pod 'Hero', :git => 'https://github.com/lkzhao/Hero.git', :commit => 'e52615f'
```

**Comment by imougy** [comment]
Thanks for the quick fix.
