### ISSUE TITLE
NavigationController dismiss gesture

### ISSUE THREAD

**Issue by felix-dumit** [lkzhao/Hero#269]
![ezgif-1-224cef39bc](https://user-images.githubusercontent.com/1863251/30409445-de73011c-98b9-11e7-92e2-0410314646e4.gif)

A couple things:

1) The default dismiss gesture is not working when hero is enabled. Is this expected?
Ideally, it would hook into the `navigationController.interactivePopGestureRecognizer` and perform an interactive transition (similar to how it does when HeroDebugPlugin is enabled).

2) Where does this black overlay over the rootVC come from when dismissing. I set the `heroNavigationAnimationType` to fade thinking it would disappear, but I guess I need to do something else as well?

Here is the example I used: https://github.com/felix-dumit/Hero/tree/nav-test (it's super simple -
 storyboard only).

EDIT: 

I found that 1) works If I do:
 ```swift
navigationController?.interactivePopGestureRecognizer?.delegate = nil`  //not exactly sure what are the consequences of this.
navigationController?.interactivePopGestureRecognizer?.addTarget(self, action: #selector(self.pan(panGR:)))

    @objc func pan(panGR: UIPanGestureRecognizer) {
        guard let view = panGR.view else { return }
        let translation = panGR.translation(in: nil)
        let progress = translation.x / 2 / view.bounds.width
        switch panGR.state {
        case .began:
            hero_dismissViewController()
        case .changed:
            Hero.shared.update(progress)
        default:
            if progress + panGR.velocity(in: nil).x / view.bounds.width > 0.3 {
                Hero.shared.finish()
            } else {
                Hero.shared.cancel()
            }
        }
    }
```

**Comment by felix-dumit** [comment]
@lkzhao Any ideas why this happens or if there are any fixes?

**Comment by remithaunay** [comment]
@lkzhao Hello, could you please reopen this issue, as it is still a current issue ? I also reproduced it easily. If you have any solutions/fixes, could you tell us ?
