### ISSUE TITLE
Update for Swift 4?

### ISSUE THREAD

**Issue by atalw** [lkzhao/Hero#271]
Getting errors while compiling in Swift 4. Any update in progress and/or any temporary fixes?

![image](https://user-images.githubusercontent.com/3257091/30431083-13d2eb58-997b-11e7-97ee-a14fb5f2e3ad.png)

**Comment by atalw** [comment]
Found a temporary fix.

In `Hero.swift`, adding `@objc` infront of the functions `animate()` and `complete()` removes the issues.

**Comment by saim80** [comment]
I thought Swift 4 has compatibility layer for Swift 3 emulation. I just imported Hero into my project which uses Swift 4. I don't seem to have any issue with it.

**Comment by atalw** [comment]
Swift 4 does have a compatibility layer for Swift 3 emulation. However, according to the documentation, extensions can add functionality to an existing type but they cannot override existing functionality.

https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Extensions.html

I think this error started popping up when I ran `pod update`.

**Comment by lonkly** [comment]
ping?

**Comment by RamblinWreck77** [comment]
Hello, any progress on this?

**Comment by Ignasihoo** [comment]
Hey!

**Comment by lonkly** [comment]
using alpha version in Podfile helps out:)

**Comment by RayanSaeed** [comment]
@lonkly Which version are you using exactly? and does it solve the flicker issue when replacing view controllers inside a UINavigationController?

**Comment by IEstfanous** [comment]
@atalw This fixed the problem, I appreciate it.

**Comment by stealdre** [comment]
@lonkly How do you use alpha version? Thx

**Comment by iOSDev33** [comment]
To use the alpha version simply put this in your Podfile

pod 'Hero', '1.0.0-alpha.4'
