### ISSUE TITLE
HeroViewControllerDelegate not firing

### ISSUE THREAD

**Issue by leeprobert** [lkzhao/Hero#272]
I'm using the latest Alpha release, and am building a very simple CollectionView prototype based off the Image gallery example. I have the delegate methods set in my code, and have a breakpoint set in 'heroWillStartAnimatingTo', but it is not stopping there. Am I missing something? Where do I set the delegate on my ViewController?

**Comment by wvabrinskas** [comment]
I can't seem to figure this out either =(

**Comment by leeprobert** [comment]
I may fork the code and add a delegation and notification engine for Hero. I think it needs it. Especially for interactive. There's no easy way to fire off a message when a transition ends.

**Comment by ssaylanc** [comment]
Did you find a soution for this issue?
