### ISSUE TITLE
Content appearing under UINavigationBar 

### ISSUE THREAD

**Issue by wvabrinskas** [lkzhao/Hero#274]
I have seen a couple of issues in the past with this same issue but it does not appear to be resolved. When I push in a view controller using `self.navigationController!.pushViewController(someVC, animated: true)` the nav bar flickers and then the content is under the navigation bar. I have yet to find a solution to this. I tried setting the nav bar to translucent and laying out if needed, nothing seems to work.

**Comment by cf-L** [comment]
Same issue. But when app enter background and reopen, the frame become correct. Any idea?

**Comment by mwhitt** [comment]
I believe the same flickering your seeing @wvabrinskas is what I described in this issue too:
https://github.com/lkzhao/Hero/issues/260

I've recreated the problem in the examples in my fork:
https://github.com/mwhitt/Hero

If you run the examples on the phone it is the first example and you will see a flickering. I am hiding the navigation top bar but if you enable it in nav controller in the storyboard I bet you might be able to re-create your issue too.

I'm trying to dig around the library to see what is causing it but no luck so far. 

My issue only happens on the device and in iOS 11 ... iOS 10 and simulator run fine.

**Comment by bolismauro** [comment]
same here.
Works fine in ios 10 but not 11

**Comment by konroj** [comment]
Check: https://github.com/lkzhao/Hero/pull/276

**Comment by wvabrinskas** [comment]
@konroj your hotfix worked for the nav bar flashing but the content still appears under the nav bar

**Comment by konroj** [comment]
I'm not experiencing this issue. Does it looks like a shadow on a part of navbar? If yes, then maybe `self.navigationController?.view.backgroundColor = UIColor.white` will help

**Comment by wvabrinskas** [comment]
So when pushing from a view controller that has the nav bar hidden to another view controller that doesn't have it hidden the content will appear under the nav bar as if the nav bar isn't there at all. A way to mitigate this is to either

- Never push from a view controller that has the bar hidden 
- Or, to hide the nav bar and then unhide it with animation set to false on both in the viewDidAppear. 

However the latter causes a visual shifting of the view. Putting the hide and unhide in any other method besides viewDidAppear does not seem to work.

**Comment by konroj** [comment]
Oh, I see. But it doesn't looks like as iOS11 problem. It appears also in 10.3.3

It's caused by 
`if let toView = toView, let fromView = fromView {`
`  toView.frame = fromView.frame`
`  toView.setNeedsLayout()`
`  toView.layoutIfNeeded()`
`}`

in `HeroTransition+Start.swift`

Changing this makes another problems (losing pop animation, wrong size of snapshot container..) :/

That may be weird workaround, but you can add top constraint with (status bar + navigation bar height, watch out for iPhoneX) offset to content in destination view controller.

Then it looks nice with for example 

`self.navigationController?.heroNavigationAnimationType = .selectBy(presenting: .zoom, dismissing: .zoomOut)`

with pull/push not really

**Comment by wvabrinskas** [comment]
That constraint seems like a hack to me though =(. i did consider it but then I have to have that constraint for ALL of my view controllers including the child view controllers of the newly pushed ones. I settled with just implementing a nav bar in all of my controllers. Hopefully this can be fixed soon.

**Comment by MatanGuttman** [comment]
Same issue here: Content is hidden below nav bar when the presenting VC's navbar is hidden. 
The content is laid out correctly only if I call : self.navigationController?.pushViewController(vc, animated: false)

but then, the presenting vc's view is misplaced when popping back.

**Comment by jayendra462** [comment]
Please write Translucent false in your controller did load method
