### ISSUE TITLE
Don't work iOS11 & Swift4 with UITabBar

### ISSUE THREAD

**Issue by devny** [lkzhao/Hero#275]
Hello, 
I used hero in my project.
This iOS 11 and Xcode9 update caused a bug.
I used custom UITabBar with hero.
After the view disappears, it does not touch.

**Comment by zipme** [comment]
It happens to me as well, after a hero modal transition the tab bar becomes non-interactive

**Comment by caihua** [comment]
How to fix?

**Comment by caihua** [comment]
I reproduce this bug in code https://github.com/caihua/Hero/commit/e961071d41417b1c8591fe8f3a412e9e5c8b21ee
No solution has been found yet.

**Comment by jbhav24** [comment]
I am having the same issue...I have a collection view with a hero transition that goes into a view controller. 
Once you open that view controller, then press the back button you are looking at the collection view once again. From this moment, the tab bar stops working.

**Comment by zacwest** [comment]
I'm not sure what the cause is yet, but it looks like there are dangling animations on the UITabBar. If you run `tabBar.layer.removeAllAnimations()` the tab bar will go back to working correctly.

**Comment by TwentyFlips** [comment]
Hello I still have the issue 

I used hero in my project.
I used UITabBar with hero.
After the view disappears, it does not touch.

            vc.hero.modalAnimationType = .selectBy(presenting: .slide(direction: .left), dismissing: .slide(direction: .right))


Event if I use tabBar.layer.removeAllAnimations()

Thank you very much
