### ISSUE TITLE
Conflicts with IQKeyboardManagerSwift, iOS 11

### ISSUE THREAD

**Issue by chitvan832** [lkzhao/Hero#279]
Hero is creating issues with IQKeyboardManagerSwift, as the keyboard constraints were getting disturbed.
After removing hero from the Project, the project runs smoothly.
hoping this to be fixed shortly

**Comment by ab-rdarts** [comment]
Here you can find a sample project to reproduct problem with IQKeyboardManager and Hero [https://github.com/hackiftekhar/IQKeyboardManager/issues/1020](url)

**Comment by protspace** [comment]
have same issue - animation "jumps" of KB

**Comment by gregoireLem** [comment]
same problem for me, only when Hero is enabled! 
Every time I push & pop the same VC, the keyboard appears with a gap that increase : 
![image uploaded from ios](https://user-images.githubusercontent.com/31652880/34870926-f79e60ec-f78b-11e7-8ff8-d0eb7f12f51a.jpg)
![image uploaded from ios](https://user-images.githubusercontent.com/31652880/34870930-fa8ea03c-f78b-11e7-8ea0-486a06cff38d.png)
![image uploaded from ios 1](https://user-images.githubusercontent.com/31652880/34870932-fca98c6a-f78b-11e7-91f0-01d828f1673b.png)

Thanks for helping 🙏

**Comment by gregoireLem** [comment]
The gap appear during the pop action

**Comment by RykerBay** [comment]
Same problem with me
I have tried using textfield's inputAccessoryView, turn out the same issue.
Please help
thx

**Comment by gregoireLem** [comment]
This is happening very often. The keyboard doesn't appear but if I touch where it should be, the keyboard input are responding. And if I press the button home & reopen the app, the keyboard is well displayed. The problem only appears when Hero is enabled

**Comment by gregoireLem** [comment]
Calling myTextField.becomeFirstResponder() in viewDidAppear seems to be a workaround for me
