### ISSUE TITLE
Interactive dismissal with nested subviews

### ISSUE THREAD

**Issue by BeamerCola** [lkzhao/Hero#282]
This is kinda hard to explain.  So I have a `cardView` that's floating in the middle of the screen.  It has an `imageView` inside of it.  Like so:

<img width="372" alt="screen shot 2017-09-29 at 7 38 41 pm" src="https://user-images.githubusercontent.com/8060/31041650-db989934-a54d-11e7-8dd7-328b4d200ddd.png">

When doing this:
```
Hero.shared.apply(modifiers: [.position(translation + cardView.center)], to: cardView)
Hero.shared.apply(modifiers: [.position(translation + imageView.center)], to: imageView)
```
When I begin to drag, the `imageView` jumps to this and then moves around with me as expected.

<img width="597" alt="screen shot 2017-09-29 at 7 38 17 pm" src="https://user-images.githubusercontent.com/8060/31041646-c589567e-a54d-11e7-8091-df100c74c391.png">

Full gesture callback:
```
    @objc func handlePan(gestureRecognizer:UIPanGestureRecognizer) {
        let translation = gestureRecognizer.translation(in: nil)
        let progress = translation.y / 2 / view.bounds.height

        switch gestureRecognizer.state {
        case .began:
            dismiss(animated: true, completion: nil)
        case .changed:
            Hero.shared.update(progress: Double(progress))
            
            Hero.shared.apply(modifiers: [.position(translation + cardView.center)], to: cardView)
            Hero.shared.apply(modifiers: [.position(translation + imageView.center)], to: imageView)
            Hero.shared.apply(modifiers: [.position(translation + titleLabel.center)], to: titleLabel)
        default:
            if progress + gestureRecognizer.velocity(in: nil).y / view.bounds.height > 0.3 {
                Hero.shared.end()
            } else {
                Hero.shared.cancel()
            }
        }
    }
```

Thanks!

**Comment by lkzhao** [comment]
If you are still experiencing this problem .Can you provide your heroModifier setup as well? during interactive transition, the imageView should move with the card view. You shouldn't need to update the position of the imageView.
