### ISSUE TITLE
Cannot build examples out of the box.

### ISSUE THREAD

**Issue by nimble99** [lkzhao/Hero#285]
Can anyone highlight how to get these examples to build OOB?
I downloaded from git, ran 'pod install' in the root - which succeeded, then tried to build the Examples target, and I just get a lot of:

AnimationSelectTableViewController.swift:25:8: error: no such module 'ChameleonFramework'
import ChameleonFramework

Thanks,

**Comment by sea516** [comment]
same step, No such module 'ChameleonFramework'

**Comment by bryanjclark** [comment]
Hello! This issue is reproducing for me from the top of the `master` branch as of February 27, 2019.

I download the source code, run `pod install`, try to run the Hero Examples target, and see:
`Error: no such module 'CollectionKit'`
