### ISSUE TITLE
overFullScreen Glitch?

### ISSUE THREAD

**Issue by keithmthunzi** [lkzhao/Hero#289]
Hi, thanks for the library it's really helping me create my animations, i cant imagine how long it would have taken to write everything myself.

I've ran into an issue though when using overFullScreen to present a view controller modally.

My setup is that I have a tableview in viewController A 

<img width="472" alt="screen shot 2017-10-05 at 17 25 56" src="https://user-images.githubusercontent.com/6878320/31238862-18d66b06-a9f3-11e7-9e41-14dd2d4ea544.png">

that when a user presses I want to show viewController B (a detailed view of the pressed cell) on top of viewController A.

This all works (animation/transparency etc) my problem is that the original fromViews in viewController A that were animated from are still visible (in their new position after animation) . i.e. if I scroll up/down in viewController B I can see the images (snapshots I believe?) of the fromViews in the place they animated to.

<img width="466" alt="screen shot 2017-10-05 at 17 26 25" src="https://user-images.githubusercontent.com/6878320/31238888-34b826f2-a9f3-11e7-9586-57822f0777d9.png">

 In the image above I've pulled the scroll view in viewController B down and you can see the image from viewController A that was animated from.

Is there any way for me to remove these and have hero recreate them when returning to viewController A (if they are needed?)

Because I thought that the underlying views were snapshots I tried setting the modifier .useNoSnapshot on the views that were animating but ended up with a complete mess

<img width="470" alt="screen shot 2017-10-05 at 17 45 51" src="https://user-images.githubusercontent.com/6878320/31239468-155b8cde-a9f5-11e7-9d23-ce99ba3cd5f3.png">

Note: (In case you're wondering the text in the images is not german or any language, it's just placeholder text)

**Comment by lkzhao** [comment]
Right, for you first approach, i purposely did not remove the snapshots from the original view controller because it would make animated views disappears. Your use case is something I haven't thought about. A hacky way to achieve what you want might be calling `Hero.shared.context.removeSnapshots(rootView: )` with your first view controller's image view at the end of the transition.

Your second approach didn't work because any layout code in your first view controller will end up controlling the view which will mess it up.

**Comment by ThoseGuysInTown** [comment]
`Hero.shared.context.removeSnapshots(rootView: )` _(and other functions like it)_ was moved to `internal` but here's another hacky way:

```
// 
let viewControllerA = UIViewController()
viewControllerB.present(vc, animated: true) {
	Hero.shared.context.container.isHidden = true
}
```
`Hero.shared.context.container` is the view containing all the snapshots so feel free to remove the view in any way you'd like.

**Comment by groupGahzz** [comment]
> Hi, thanks for the library it's really helping me create my animations, i cant imagine how long it would have taken to write everything myself.
> 
> 
> 
> I've ran into an issue though when using overFullScreen to present a view controller modally.
> 
> 
> 
> My setup is that I have a tableview in viewController A 
> 
> 
> 
> <img width="472" alt="screen shot 2017-10-05 at 17 25 56" src="https://user-images.githubusercontent.com/6878320/31238862-18d66b06-a9f3-11e7-9e41-14dd2d4ea544.png">
> 
> 
> 
> that when a user presses I want to show viewController B (a detailed view of the pressed cell) on top of viewController A.
> 
> 
> 
> This all works (animation/transparency etc) my problem is that the original fromViews in viewController A that were animated from are still visible (in their new position after animation) . i.e. if I scroll up/down in viewController B I can see the images (snapshots I believe?) of the fromViews in the place they animated to.
> 
> 
> 
> <img width="466" alt="screen shot 2017-10-05 at 17 26 25" src="https://user-images.githubusercontent.com/6878320/31238888-34b826f2-a9f3-11e7-9586-57822f0777d9.png">
> 
> 
> 
>  In the image above I've pulled the scroll view in viewController B down and you can see the image from viewController A that was animated from.
> 
> 
> 
> Is there any way for me to remove these and have hero recreate them when returning to viewController A (if they are needed?)
> 
> 
> 
> Because I thought that the underlying views were snapshots I tried setting the modifier .useNoSnapshot on the views that were animating but ended up with a complete mess
> 
> 
> 
> <img width="470" alt="screen shot 2017-10-05 at 17 45 51" src="https://user-images.githubusercontent.com/6878320/31239468-155b8cde-a9f5-11e7-9d23-ce99ba3cd5f3.png">
> 
> 
> 
> Note: (In case you're wondering the text in the images is not german or any language, it's just placeholder text)
> 
> 
> 
>
