### ISSUE TITLE
UITapGestureRecognizers are not working

### ISSUE THREAD

**Issue by IrvinKocan** [lkzhao/Hero#29]
I'm presenting view controller with one simple subview using heroReplaceViewController(with: myViewController) and everything is ok with animations. But UITapGestureRecognizer that's added to subview is not working. When I replace heroReplaceViewController method with present(myViewController, animated: true, completion: nil)  tap gesture recognizer is working normally.

Could this be some problem with library?

**Comment by lkzhao** [comment]
might be. Can you upload an example so that I can better help you.

**Comment by IrvinKocan** [comment]
[HeroDemo.zip](https://github.com/lkzhao/Hero/files/692421/HeroDemo.zip)

**Comment by lkzhao** [comment]
https://github.com/lkzhao/Hero/pull/30
Should be fixed with this PR. Can you checkout that branch and confirm?

```ruby
pod "Hero", :git => 'https://github.com/lkzhao/Hero.git', :branch => 'replace-fix'
```

Note: that branch's API is updated with the new Swift Enum `heroModifiers`, usage is a bit different.

**Comment by IrvinKocan** [comment]
It's working.
Thanks
