### ISSUE TITLE
Animation bug when matched background image

### ISSUE THREAD

**Issue by burgercode** [lkzhao/Hero#294]
Hi,

## The setup :wrench:
I have two ViewControllers A and B. We can navigate between the two by touching a button, this is a simple Segue transition with a Navigation Controller. 

I've set the same background image on both ViewController, I've done it by simply placing an image on the bottom of the hierarchy and by setting the constraints to stick the edge of the screen. 

The UIImageView have the same HeroID, I want that during the Push Segue, the background image stays in place and that the other elements animate like in a normal Push Segue (and some of them, like the title on A match the title B, but that works fine.)

## The problem :bug:
When the UIImageView on A and B don't have the same HeroID, everything works fine. My elements are correctly animated, but the background image also moves, which is not the wanted effect.

![OK](https://user-images.githubusercontent.com/26303997/31574024-edff4814-b0c6-11e7-83af-8ca3e5a792e2.gif)

When then both have the same HeroID, then the background image stays at the same place, which if fine, but the other elements don't animate in a Push Style. Only those with the same HeroID animates correctly. (You can see that the textFields appears suddenly and are not animated)

![Not OK](https://user-images.githubusercontent.com/26303997/31574046-3a6d967e-b0c7-11e7-800b-1010979d0d2b.gif)

## What I've tried :persevere:
- Reset constraints and set them again
- Play with the Hero Settings on both the ViewController, and the elements
- Set different images but still with the same HeroID
- Clean the directory, restart Xcode,...
- Test on multiple iPhone, not only iPhone X

## Conclusion :pray:
Does anybody ever had the same problem ? How to fox it ? Is it a Hero bug or is it my fault ?
Thank you :) 

### Versions
Project is in Swift 4.0, Xcode 9.0, Hero V.1.0.0-alpha4 and also tried on Hero V.0.3.6
(The TabBar is not finished in my project, but that's not the problem)

**Comment by burgercode** [comment]
Any ideas ?

**Comment by lkzhao** [comment]
Ok cool. I can tell you exactly how to fix it.

**Comment by lkzhao** [comment]
It is some set up problem.

**Comment by lkzhao** [comment]
The reason is because once your image view is given a heroId. it is not part of the parent view snapshot anymore. It is brought to the front of the parent view hence it is covering the rest of the UI inside your parent view.

**Comment by lkzhao** [comment]
To fix this. I suggest changing your parent view to a UIImageView and assign the image there.

**Comment by lkzhao** [comment]
or you can use `.forceAnimate` modifier to other UI Elements. This way hero will create a snapshot for those elements as well and bring them forward.

**Comment by lkzhao** [comment]
Let me know if it is still unclear to you.
