### ISSUE TITLE
Hero Modifiers not considered when presenting ViewController presents another

### ISSUE THREAD

**Issue by Tantalum73** [lkzhao/Hero#295]
Consider a view hierarchy of three UIViewController. The first one presents the second one, which presents the third one, modally.
During each transition, the presenting ViewController stays visible like a stack of cards.
I made an example project for demonstration.

<img width="559" alt="bildschirmfoto 2017-10-14 um 13 20 42" src="https://user-images.githubusercontent.com/9120168/31575250-8a1b7e14-b0e2-11e7-87ce-6a809dbc28ad.png">

The image above shows the first ViewController (orange) and the second one (yellow).
When now the 'Present Third' button gets pressed, Hero Modifiers for our first and second ViewController are adjusted, then the third ViewController animates its appearance.
During this animated presentation, the second ViewController (yellow) is animated, while the first one (orange) stays at its place without showing any animation.

![hero_issue](https://user-images.githubusercontent.com/9120168/31575316-11b7fbbc-b0e4-11e7-9f7b-319e54ecb96a.gif)

The sample project is attached to the issue.
I would like to ask if I am using the API incorrectly or stumbled over a bug.

Maybe you have an other idea how to implement this kind of transition.
In any case, I would love to hear your thoughts.

[CardLayoutTest.zip](https://github.com/lkzhao/Hero/files/1384615/CardLayoutTest.zip)

**Comment by chris-redbeed** [comment]
Same here.
iOS 113 (beta 2)
