### ISSUE TITLE
Is this project abandon ?

### ISSUE THREAD

**Issue by mosn** [lkzhao/Hero#297]
I can see there hasn't been any new releases and there are tons of open issues. 

Would be good to hear from devs

**Comment by gali8** [comment]
Nope but if you like to install the last version using CocoaPods, use 
`pod 'Hero', :git => 'https://github.com/lkzhao/Hero.git' #fix iOS 11 in UIView+Hero.swift, etc...`

**Comment by jusungTLX** [comment]
Thank you for the info @gali8 and this question @mosn .

**Comment by mosn** [comment]
I guess I'll leave this issue open for better visibility. Thanks @gali8

**Comment by wassimseif** [comment]
is anyone still getting these flashing animations in ios11 ? i updated to Hero 1.0.0

**Comment by lkzhao** [comment]
I will close all old issues and start keeping actively maintaining new ones. please feel free to re-open any issues if you have still having the problem.
