### ISSUE TITLE
.push and .cover interactive transitions start abruptly.

### ISSUE THREAD

**Issue by capt-hook** [lkzhao/Hero#299]
Instead of starting at the edge of the screen they start a bit off the edge. Issue happens only with interactive transitions (I was using a pan gesture recognizer).

![simulator screen shot - iphone 6s plus - 2017-10-17 at 00 20 59](https://user-images.githubusercontent.com/1716190/31637519-c12847f6-b2d7-11e7-996a-ae67430dc141.png)

**Comment by lkzhao** [comment]
I have to look into this. Did you use `Hero.shared.apply(...)` to control the interactive behaviour? or just `Hero.shared.update`?

**Comment by capt-hook** [comment]
@lkzhao Just update, I used exactly the same code that was in the example article on interactive transitions using Hero that you've wrote.

**Comment by lkzhao** [comment]
Ok, let me look.

**Comment by lkzhao** [comment]
Should be fixed in the latest master. I have added a left edge pan gesture recognizer to that screen that you showed.

**Comment by capt-hook** [comment]
@lkzhao Just tried it and can confirm that it works now. Thank you for taking the time to make a fix!
