### ISSUE TITLE
Crash in slowSnapshotView()

### ISSUE THREAD

**Issue by imougy** [lkzhao/Hero#300]
@lkzhao, hi!  It seems there is a crash in this line **layer.render(in: UIGraphicsGetCurrentContext()!)**, can't give you an example of how to reproduce, but if you look at the code, it makes sense to change it.  What do you think?
**Current Code:-** 
`  internal func slowSnapshotView() -> UIView {
    UIGraphicsBeginImageContextWithOptions(bounds.size, isOpaque, 0)
    layer.render(in: UIGraphicsGetCurrentContext()!)

    let image = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()

    let imageView = UIImageView(image: image)
    imageView.frame = bounds
    return SnapshotWrapperView(contentView: imageView)
  }
`

**Suggested Code**
`  internal func slowSnapshotView() -> UIView {
    UIGraphicsBeginImageContextWithOptions(bounds.size, isOpaque, 0)
    guard let currentContext = UIGraphicsGetCurrentContext() else {
        UIGraphicsEndImageContext()
        return UIView()
    }
    layer.render(in: currentContext)

    let image = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()

    let imageView = UIImageView(image: image)
    imageView.frame = bounds
    return SnapshotWrapperView(contentView: imageView)
  }
`
**Crash:-**

0   Hero                                 0x00000001086b3fcc (extension in Hero):__ObjC.UIView.slowSnapshotView () -> __ObjC.UIView (UIView+Hero.swift:82)
1   Hero                                 0x0000000108697638 function signature specialization <Arg[0] = Owned To Guaranteed> of Hero.HeroContext.snapshotView (for : __ObjC.UIView) -> __ObjC.UIView (HeroContext.swift:168)
2   Hero                                 0x00000001086eab5c Hero.HeroTransition.animate () -> () (HeroTransition+Animate.swift:0)
3   Hero                                 0x00000001086e5a60 Hero.HeroTransition.start () -> () (HeroTransition+Start.swift:156)
4   Hero                                 0x00000001086815e4 @objc Hero.HeroTransition.animateTransition (using : __ObjC.UIViewControllerContextTransitioning) -> () (HeroTransition+UIViewControllerTransitioningDelegate.swift:0)
5   UIKit                                0x00000001901f8e18 0x18fe9d000 + 3522072
6   UIKit                                0x000000019011d1b4 0x18fe9d000 + 2621876
7   UIKit                                0x0000000190110558 0x18fe9d000 + 2569560
8   UIKit                                0x000000018fe9fd08 0x18fe9d000 + 11528
9   CoreFoundation                       0x0000000186a1d848 0x186934000 + 956488
10  CoreFoundation                       0x0000000186a1b200 0x186934000 + 946688
11  CoreFoundation                       0x0000000186a1b7bc 0x186934000 + 948156
12  CoreFoundation                       0x000000018693bfb8 0x186934000 + 32696
13  GraphicsServices                     0x00000001887d1f84 0x1887c7000 + 44932
14  UIKit                                0x000000018ff10534 0x18fe9d000 + 472372

**Comment by imougy** [comment]
I am reopening this issue. I can make a PR but don't I need access?

**Comment by lkzhao** [comment]
you don’t need access to create a pr. Just fork the project and make your
changes.
