### ISSUE TITLE
Looking for a maintainer!

### ISSUE THREAD

**Issue by lkzhao** [lkzhao/Hero#309]
Hero helped me learned a lot about iOS over the last year. Fighting the iOS animation system and dealing with UI bugs has been quite a journey. But I am sorry to say that I do not have to time to maintain this project anymore. The scope of this project has become unmanageable for me to handle due to personal matter. Therefore, I am looking for a project maintainer to this project and I'm open to transfer this to a public organization instead of under my personal account.

I will still be using Hero in production, and contribute to critical bug fixes and new iOS release.

**Comment by lkzhao** [comment]
@jindulys :) do you want to take over?

**Comment by ooodin** [comment]
Hey, @lkzhao 
I'm active user of Hero, actually it's very useful library for me. If I can help you to continue support it, I will be happy to do it.

**Comment by adamdahan** [comment]
@lkzhao Hi, I am from CosmicMind team - we are creators of Material https://github.com/CosmicMind/Material with 8500+ Stars. Please contact me adam@cosmicmind.com - I would like to discuss take over. 

Thanks

**Comment by alvincrisuy** [comment]
I can also contribute 😄

**Comment by shivenios7262** [comment]
@IKzhao Hi, I want use "Hero",but pod is not supported in Xcode 9 unable to migrate swift 2.3 to swift 4. How can I use Hero???

**Comment by ooodin** [comment]
@shivenios7262 check that you use the latest version. Hero is support swift 4 now

**Comment by jindulys** [comment]
Definitely!

**Comment by shivenios7262** [comment]
thanks Ikzhao, for anticipation.
