### ISSUE TITLE
QUESTION: Extending Hero to support custom view properties?

### ISSUE THREAD

**Issue by GoldenJoe** [lkzhao/Hero#310]
Suppose I have a custom view which uses a CAShapeLayer to mask its contents. Is there any way I could use Hero to change the `path` property of that layer? Likewise, could I extend Hero to transition between images in a UIImageView, or text strings in a UILabel?

**Comment by lkzhao** [comment]
Yes, you can try writing a HeroPlugin. check out the example project for some examples. 
The way that I would do it is to extend HeroModifier and add your own modifier. then have you plugin handle the animation for the specific view.
