### ISSUE TITLE
A crash bug in file HeroCoreAnimationViewContext

### ISSUE THREAD

**Issue by caihua** [lkzhao/Hero#313]
in HeroCoreAnimationViewContext
line 158 
       subview.center = CGPoint(x: center.x / oldSize.width * newSize.width, y: center.y / oldSize.height * newSize.height)

here has a crash bug.I guess it's because there's no judgment about divisor 0, I am not sure this ,because crash is random occurrence.

I got some crash reports from client,like this image.
 
![https://github.com/caihua/bugimg/raw/master/bug1.png](https://github.com/caihua/bugimg/raw/master/bug1.png)

 ![https://github.com/caihua/bugimg/raw/master/bug2.png](https://github.com/caihua/bugimg/raw/master/bug2.png)

![https://github.com/caihua/bugimg/raw/master/bug3.png](https://github.com/caihua/bugimg/raw/master/bug3.png)

**Comment by saranonuan** [comment]
I found division by zero crash too.

In my case, I have blank UILabel (size 0,0) in the source view controller that has heroID same with another view at destination controller.

**Comment by lkzhao** [comment]
Hey @caihua  @saranonuan, Thanks for reporting this. If you guys have the bandwidth, can you guys help me create a PR? that will be really great.

**Comment by lkzhao** [comment]
fixed in latest master.
