### ISSUE TITLE
Hero.shared.end() and update()

### ISSUE THREAD

**Issue by caesss** [lkzhao/Hero#317]
in xcode 9.1 I'm getting these two errors in interactive animation

1. ---Extraneous argument label 'progress:' in call
Hero.shared.update(progress: Double(progress)) 

should this be?
Hero.shared.update(progress) 

2. ---Value of type 'HeroTransition' has no member 'end'
Hero.shared.end() 

should this be?
Hero.shared.finish() or Hero.shared.cancel()?

below is my original code:
    func pan() {
        let translation = panGR.translation(in: nil)
        let velocityX = panGR.velocity(in: nil).x
        let progress = translation.x / 2 / view.bounds.width
        switch panGR.state {
        case .began:
            if  velocityX > 0 {
                hero_dismissViewController()
            }
        case .changed:
            Hero.shared.update(progress: Double(progress))
        default:
            if progress + panGR.velocity(in: nil).x / view.bounds.width > 0.3 {
                DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 0.01, execute: {
                    Hero.shared.end()
                })
            } else {
                Hero.shared.cancel()
            }
        }
    }

**Comment by lkzhao** [comment]
1. should be `Hero.shared.update(progress)`
2. should be `Hero.shared.finish()`

This API change is made in v1.0.0
