### ISSUE TITLE
Cascade can be used in ViewController.view?

### ISSUE THREAD

**Issue by riki-dexter** [lkzhao/Hero#321]
Hi,
Cascade hero modifier can be applied to a ViewController's view to get cascade effect applied to all subviews added to the view?
Example pseudocode:
````
class MyViewController: UIViewController {
     override func viewDidLoad() {
     super.viewDidLoad()
     self.view.backgroundColor = .white
     self.isHeroEnabled = true

     let label = UILabel()
     .....
     label.heroModifiers = [.fade, .scale(0.5)]
     self.view.addSubview(label)
     
     let anotherLabel = UILabel()
     .....
     anotherLabel.heroModifiers = [.fade, .scale(0.5)]
     self.view.addSubview(anotherLabel)

     self.view.heroModifiers = [.cascade]
     }
}
````
Thank you

**Comment by ooodin** [comment]
> all subviews added to the view?
`self.view.subviews.forEach {
       $0.heroModifiers = [.cascade]
 }`
but I'm not sure that it's great idea)

**Comment by lkzhao** [comment]
Applying .cascade to the root view should work. Are you experiencing any issue?
