### ISSUE TITLE
Transition only working on first show in NavigationController

### ISSUE THREAD

**Issue by kanstraktar** [lkzhao/Hero#326]
It's obviously working inside a NavigationController, but it's only working once. If I pop and call show/push again on the first ViewController, there is no animation. Any ideas?

Thanks

**Comment by apeman021** [comment]
same issue :'(

**Comment by lkzhao** [comment]
Did you set `isHeroEnabled` on the navigation controller?

**Comment by kanstraktar** [comment]
Yes. Found a workaround though: in order to make it work I have to do this:
```
navController?.isHeroEnabled = false 
navController?.isHeroEnabled = true 
```
Just setting it to `true` doesn't work, but setting it to `false` and to `true` on the next line makes it work, so possibly a bug?
