### ISSUE TITLE
Cannot set self as observer for progress updates due to internal protection level

### ISSUE THREAD

**Issue by mad102190** [lkzhao/Hero#328]
Hi @lkzhao,

I'm trying to observe for progress updates by implementing the `HeroProgressUpdateObserver` protocol and then calling `Hero.shared.observeForProgressUpdate(observer: self)` in my `viewDidLoad()`, but Xcode is complaining that 

> 'observeForProgressUpdate' is inaccessible due to 'internal' protection level

and will not let me compile. The class is `open` and the protocol is `public` but there's no protection level specified for the method explicitly, so it's defaulting to `internal`. I'd be happy to submit a PR to change this, unless it was intentional, in which case I'd appreciate it if you could point me in the right direction for how to observe progress in the intended way.

Thanks!

**Comment by jindulys** [comment]
Your CL looks good and has been merged, I will close this issue now.

Please keep an eye on whether observer could be dealloced correctly. If you find something incorrect, please open a new issue. Thx!

**Comment by petard** [comment]
I currently have VC1, VC2 and VC3, I'm transitioning from VC1 to VC2 first. Depending on a specific state, VC2 might immediately present VC3.

I wanted to use `Hero.shared.observeForProgressUpdate(observer: self)` in VC2 to detect whether the transition from VC1 to VC2 is still going, and then present VC3 if necessary. However, `progress` never reaches the value of `1` but something like `0.881....`.

I tried using `Hero.shared.finish()` before performing the segue to VC3 but I would still get an error from Hero that another transition is in progress.
