### ISSUE TITLE
Doesn't work transition from Collection view cell

### ISSUE THREAD

**Issue by EgorkZe** [lkzhao/Hero#331]
I have cell with image in collectionview on first screen (heroId = dayView) and one more image on another screen, heroId is the same. Transition between screen works as usual present(), not as hero transition. Second screen has isHeroEnabled  = true. And there is no navigation controllers.
Thanks

**Comment by EgorkZe** [comment]
Found the problem, my bad. Its needed to use different heroId for each cell in collection view. Now it is working proper way.

**Comment by jindulys** [comment]
Thx for feedback, I will close this issue now.
