### ISSUE TITLE
Crash sometimes in this line

### ISSUE THREAD

**Issue by imougy** [lkzhao/Hero#333]
https://github.com/lkzhao/Hero/blob/1c8c3e5804041115eea9d64d1f27ea919a909056/Sources/Animator/HeroCoreAnimationViewContext.swift#L220

Fix:-
` 
				if let fromSize = fromValue as? NSValue, let toSize = toValue as? NSValue {
`

**Comment by lkzhao** [comment]
Thanks! fixed in the latest master.

**Comment by imougy** [comment]
Awesome!
I can contribute a bit to the project after you leave. You did a fantastic job.

**Comment by lkzhao** [comment]
That will be great! Actually I will have some time to take care of this repo from now on. What Hero needed the most is some nice tutorial/documentation to get started. As the framework author I don't know what are the parts that are confusing for new comers. If you can help writing some tutorial/documentation that will be awesome! You will definitely get acknowledged on the README.

**Comment by imougy** [comment]
I would contribute more on the coding side, I am not the best tutorial person myself, also, you did fantastic with your tutorials, as a user, this is the best framework documentation I have seen. Developers don't read tutorials as you know :)
