### ISSUE TITLE
When Hero enabled, self.view.alpha is always 1

### ISSUE THREAD

**Issue by Tibb** [lkzhao/Hero#34]
I wanted to add some Hero beautiful transitions between 2 controllers. The destination controller isn't completely opaque (alpha = 0.9), to let you see the original controller behind.
In this case, here are segue parameters:
**Kind**: `present modally`
**Presentation**: `Over current Context`
**Transition**: `Default`

But using Hero set `self.view.alpha` to `1.0` at the end of the transition.
I just added Hero on a button, with the following modifier: `zPosition(2)`

Is it possible to keep some transparency using Hero?
Thanks!

**Comment by lkzhao** [comment]
Hero shouldn't have set the view's alpha to 1. But might be a bug. Nonetheless, it is complicated. The current cross fade strategy doesn't work with alphas. I have to spent some time experimenting with other way of creating cross fade effects.

**Comment by lkzhao** [comment]
This is fixed in 0.3.0.

**Comment by Tibb** [comment]
Great news, thanks a lot!
