### ISSUE TITLE
Can this library be used to replicate the iOS 11 Appstore Card animation?

### ISSUE THREAD

**Issue by cyrilzakka** [lkzhao/Hero#346]
Looking to use an all inclusive animation library in my project. Can this be used to replicate the iOS 11 Appstore Card opening/closing animation?

**Comment by lkzhao** [comment]
Should be able to. I don't see any significant problem. But it is a very complicated transition requiring some time to tweak. 

I will try to build an example of App store transition using this week. stay tuned.

**Comment by lkzhao** [comment]
I would also suggest you take a look at: https://github.com/PaoloCuscela/Cards

**Comment by RomeHein** [comment]
Almost able to reproduce iOS 11 App Store card animations. Still have issues to handle corner radius and shadows of the tiles. These are not animated correctly: they disappear before each animation, and reappear after animation is finished (when dismissing the controller)

**Comment by lkzhao** [comment]
Not sure if you have seen this. Just FYI that I made a example a month ago and I totally forgot about it.
https://github.com/lkzhao/AppStoreTransition

**Comment by cyrilzakka** [comment]
Works great thanks!!

**Comment by freemansion** [comment]
@RomeHein I having same issue with animating corner radius. How did you solved it?
