### ISSUE TITLE
Issue with backwards transition

### ISSUE THREAD

**Issue by CeceXX** [lkzhao/Hero#362]
Hey Luke,

thanks for the great library. I'm using it to animate a specific transition inside an app. As you can see there's a little view at the top of the collection view (highlighted in black):

![simulator screen shot - iphone 8 plus - 2018-01-01 at 16 26 49](https://user-images.githubusercontent.com/10504710/34468804-e3619a64-ef10-11e7-955f-f265de0a294c.png)

When the user taps on an element and then goes back, though, the little bar gets hidden (probably behind the navigation bar), while the collection view "adjusts" itself to the top. Any hints on what's going on? Thanks

![simulator screen shot - iphone 8 plus - 2018-01-01 at 16 26 57](https://user-images.githubusercontent.com/10504710/34468815-1568a318-ef11-11e7-91f0-522e97d05ef8.png)

**Comment by lkzhao** [comment]
hmm, weird. Does your view have the same parent view as the collection view? and what kind of transition and modifiers are you using?

**Comment by CeceXX** [comment]
@lkzhao thanks for the response. I'm using a `.fade` transition but this issue can be reproduced with any transition style. I'm using `heroID`s of the collection view cell (like the logos, cell content view and labels). The 2nd view controller is a lot different than the first one you're seeing (not sure if that's what you meant). This issue appears with or without the little bar at the top. Even if I put a 500 top layout constraint to the collection view (like a lot of empty space at the top), I still get that issue.

**Comment by CeceXX** [comment]
This is happening with literally every collection view in the app, like the [JTAppleCalendar](https://github.com/patchthecode/JTAppleCalendar) framework below (it's a subclass of a UICollectionView).
![simulator screen shot - iphone 8 plus - 2018-01-05 at 19 11 56](https://user-images.githubusercontent.com/10504710/34622182-6d92251c-f24c-11e7-8b8f-160d8add0d4b.png)

**Comment by CeceXX** [comment]
Closing this. This is not a problem with Hero.
