### ISSUE TITLE
I can't get it work...

### ISSUE THREAD

**Issue by XRadevFRT** [lkzhao/Hero#368]
I have 2 Storyboards, with single ViewController in each.
The code in vc1 is:
`let VC2 = UIStoryboard(name: "VC2", bundle: nil).instantiateViewController(withIdentifier: "VC2") as! VC2
        VC2.isHeroEnabled = true
        VC2.heroModalAnimationType = .zoomOut
        self.hero_replaceViewController(with: VC2)`

The code in vc2 is:
`let VC1 = UIStoryboard(name: "VC1", bundle: nil).instantiateViewController(withIdentifier: "VC1") as! VC1
        VC1.isHeroEnabled = true
        VC1.heroModalAnimationType = .uncover(direction: HeroDefaultAnimationType.Direction.up)
        viewController?.hero_replaceViewController(with: VC1)`

...I really don't understand whats going on. Each VC is sliding from the right like the default navigation transition. There is no navigation controller in either storyboard and there are no views connected with the same heroId. I've tested it in another project with exact same code and it worked  but the two ViewController were in the same storyboard. I really want to use Hero in my project but this gives me a headache...

**Comment by XRadevFRT** [comment]
Ok I fixed it...The projects initial VC was initialized within UINavigationController...I changed it to just UIViewController and it worked.

**Comment by XRadevFRT** [comment]
But hey...can you give some more examples of how to use Hero? Something cool that you've used in your projects. I've looked around the Hero Example project put its seems its just scratching the surface  of the framework. I'll really appreciate it. Thank you!

**Comment by Graystripe17** [comment]
There's an examples folder in the repo. If you figured out your issue then don't forget to close it!
