### ISSUE TITLE
OverCurrentContext Support.

### ISSUE THREAD

**Issue by lkzhao** [lkzhao/Hero#37]
Hero doesn't have support for these modal presentation styles yet. Would be a bit tricky to implement since Hero needs to keep track of the presented view controllers.

Related to #34 #26

**Comment by fruitcoder** [comment]
Could you point out how the community could help you with this issue? I love your framework but for context transitions it's sometimes necessary to show "where you come from", because it's better to understand the context. Isn't it sufficient to store a snapshot of the presenting view controller instead of a pointer to it?

**Comment by lkzhao** [comment]
@fruitcoder Yes, we can start working on this now. For the past few week I have been trying to clean up the existing API and drop the zPosition modifier that was needed to make Hero transitions.

About your suggestion with keeping a snapshot of the presentingVC. The problem is that it doesn't work when the screen rotates on the presented VC. Ideally the presentingVC should also rotate and re-layout its subviews.

There are 2 problems to be solved:
1. Hero currently doesn't store any state information after the transition. This makes it far easy to debug and also make view controller transitions independent. You can transition from any VC to any other VC without knowing which VC presented what. Many of the navigation helpers like `hero_replaceViewController` & `hero_unwindToViewController` depend on this.

2. The snapshots that Hero takes have to stay after the transition. Theses snapshots are in a container view during the transition. Which VC should we insert these snapshot into? Who should keep track of them? Any still, when the screen rotates, these snapshots won't be updated. 

I am also not very familiar with UIPresentationController. I have to spend some time on that and see if that is something we can use to maintain state information.

**Comment by lkzhao** [comment]
.overFullScreen support is implemented in 0.3.0

**Comment by fuxlud** [comment]
Thank a lot for this amazing library! 

This issue is still happening to me - I can still see black background when transition finished. 
```

       let vc = MyViewController(...)
        vc.hero.isEnabled = true
        vc.hero.modalAnimationType = .selectBy(presenting: .pull(direction: .left), dismissing: .pull(direction: .right))
        vc.modalPresentationStyle = .overCurrentContext
        vc.view.backgroundColor = .clear
        present(vc2, animated: true, completion: nil)
```


When I set animated property to false `present(vc2, animated: false, completion: nil)` the background is transperent, but then I do not see the transition

**Comment by szoszig** [comment]
Any news on this?
