### ISSUE TITLE
Freezing Interactive transition in combination with UINavigationController

### ISSUE THREAD

**Issue by amosavian** [lkzhao/Hero#371]
Hi, Thanks for this great library ❤️

An issue has been introduced by [this commit](https://github.com/lkzhao/Hero/commit/21763ad850a7dfe804167749ab9fb9a665cbdce5) which took an entire day of mine.

Step to reproduce:

1. Implement interactive transition [according to this sample](https://github.com/lkzhao/Hero/blob/master/Examples/Examples/ImageGallery/ImageViewController.swift#L53-L73) in a detail viewcontroller in an navigation controller

2. open the detail viewcontroller from the root (my settings are animation = .fade with some transitions of image and texts from root view to detail's corresponding ones via heroID)

3. try to pop detailVC via gesture, but reverse it to cause 'Hero.shared.cancel()` being called.

4. Pop child viewcontroller, This time for real. (I couldn't get animation this time, after and before that commit. But I'm ok with that 😀)

5. Try to open detail viewcontroller again. UI would freeze in the middle of transition (created by that commit)

Regards

**Comment by lkzhao** [comment]
There might be a setup problem in your project. If seem strange that you cannot get animations for #4. can you provide an example project for me to better help you.

**Comment by amosavian** [comment]
This is my setup:

```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    //...
    cell.textLabel?.heroID = "title_\(playlistName)_\(indexPath.row)"
    cell.detailTextLabel?.heroID = "artist_\(playlistName)_\(indexPath.row)"
    cell.textLabel?.heroModifiers = [.arc]
    cell.detailTextLabel?.heroModifiers = [.arc]
    cell.imageView?.heroID = "artwork_\(playlistName)_\(indexPath.row)"
    //...
}

override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    navigationController?.isHeroEnabled =  !Utility.UI.isRegularPad(self)
    navigationController?.heroNavigationAnimationType = .fade
    playerView.view.layoutIfNeeded()
    playerView.artworkImageView.heroID = "artwork_\(playlistName)_\(selectedrow.row)"
    playerView.titleLabel.heroID = "title_\(playlistName)_\(selectedrow.row)"
    playerView.artistLabel.heroID = "artist_\(playlistName)_\(selectedrow.row)"
}
```

**Comment by amosavian** [comment]
You were right. The problem was destination view controller set navigation bar to hidden while it was not hidden on parent.

Now I try to figure out how to solve it. I think there is no problem with platform. Thanks

**Comment by metisdev** [comment]
@amosavian  Have you found a solution? I experience same problem as a flicker in first VCs navigation bar title :(

**Comment by amosavian** [comment]
@metisdev my last answer didn't worked for you?

**Comment by metisdev** [comment]
"Now I try to figure out how to solve it." I had the same problem my main VC has navigation bar but modal has no navigation bar.

**Comment by metisdev** [comment]
I understood that so i tried to ask, how did you solve the problem of flicker with one view having navigation bar and the other not having navigation bar?
Also in my case it is not a push animation but a modal presentation

**Comment by amosavian** [comment]
Aha, I didn't have a flicking issue, but the animation caused app freezing and unresponsiveness. Maybe you have a different issue and it worths to open a new issue with sufficient details.
