### ISSUE TITLE
Crash while dismissing the "ImageViewer" interactively

### ISSUE THREAD

**Issue by proactive-solutions** [lkzhao/Hero#38]
I am using Xcode 8.2.1 with Mac OS version 10.12

![crash](https://cloud.githubusercontent.com/assets/13619716/21837746/20c61860-d7f4-11e6-86af-896b920b0d5d.png)

**Comment by lkzhao** [comment]
Does this happen every time?

**Comment by proactive-solutions** [comment]
It happened to me 2 times, but I was not able to reproduce it every time.

**Comment by lkzhao** [comment]
Will look into this. Thanks for reporting

**Comment by lkzhao** [comment]
Should be fixed with this: https://github.com/lkzhao/Hero/commit/5c83f43773afa87c2afb0df9702839dd8b6e186e

I think it is a race condition caused when the gestureRecognizer fired before the transition have started. Let me know if you still catch this problem.
