### ISSUE TITLE
Forward UINavigationController Delegate Methods

### ISSUE THREAD

**Issue by tooolbox** [lkzhao/Hero#396]
# The Problem

When you enable `isHeroEnabled` on a UINavigationController, Hero takes over as the delegate for that VC, and saves a reference to its previous delegate in the property `previousNavigationDelegate`.  I've encountered a situation where I want Hero to control the animations of my UINavigationController, but I also want to make another VC aware of these delegate calls.

# The Proposal

Whenever Hero receives delegate methods from a UINavigationController, it should call those same methods on the `previousNavigationDelegate`, if there is one.

I'm working on a PR for this.

**Comment by tooolbox** [comment]
Interesting, related to https://github.com/lkzhao/Hero/issues/25

**Comment by tooolbox** [comment]
I was able to solve what I was running into by turning on Hero for the Nav Controller, and then having my own View Controller set itself as the delegate and then forward transition methods to Hero.  This way is perfectly workable so I am closing the PR.

**Comment by paulpopiel** [comment]
FYI fixed in the following:
https://github.com/HeroTransitions/Hero/pull/430
