### ISSUE TITLE
support layer.cornerRadius while animating

### ISSUE THREAD

**Issue by wipnick** [lkzhao/Hero#40]
While animating a view to a destination view where both views set layer.cornerRadius = x, hero always ignores that value and animates a rect.

**Comment by lkzhao** [comment]
Should be supported. But the implementation is not that robust. Can you try turning on maskToBounds and see if that works?

**Comment by lkzhao** [comment]
I will reimplement cornerRadius support when I have time.

**Comment by lkzhao** [comment]
Is cornerRadius still not working for you?

**Comment by jaroslavas** [comment]
At the moment it doesn't work. View becomes square, animates and then becomes round again.

**Comment by hussc** [comment]
Yeah me too :D

**Comment by Namedix** [comment]
Do we have any solution?

**Comment by hussc** [comment]
I've just got it..
on the view, make sure to check clipToBounds is equal to true.

**Comment by Namedix** [comment]
@hussc 
Unfortunately, it does not work in my case, maybe it is because I adds a shadow to View :/

**Comment by kylebrowning** [comment]
Same.

**Comment by thomers** [comment]
I'm having the same problem - I'm setting a CACornerMask on a plain UIView with a background color, within a custom UITableViewCell.

The rounded corners are only showing AFTER the hero transition, during the transition they are square.

Setting setMasksToBounds:YES on the UIView or the cell's contentView does not fix it.

**Comment by iAmNaz** [comment]
The same issue is happening with me where I am using CACornerMask on many views. Before transitioning only the bottom are rounded as I expect it to be but during transition all corners becomes rounded. I think the masks somehow goes away for a bit then back. 

My work around for the mean time is to put my rounded view in another view as subview then set the superview color to default. This worked for me and let me know if it worked for you.

Just guessing, during transition perhaps Hero does something on the view that affects or ignores some properties such as our case.

**Comment by pcjbird** [comment]
what about this? the same problem.

**Comment by pcjbird** [comment]
https://github.com/HeroTransitions/Hero/pull/593/files/d76949135880e2dbc08f57a7ea987b297192c380

great!!!!!!!!!!
