### ISSUE TITLE
How to animate cell inside a single view controller between Table View and Collection View?

### ISSUE THREAD

**Issue by khoren93** [lkzhao/Hero#402]
Hi. Thanks for this amazing library :)
After selecting Contact cell from TableView, I want to move cell to top Collection with animation.
Is this possible with this library?
Thank you so much!

![28709959-9e0389f0-7382-11e7-899c-bdc816c093c0](https://user-images.githubusercontent.com/11523360/36313391-d3fd51fe-134a-11e8-9a1e-f09cacd6787c.png)

**Comment by zhengbomo** [comment]
any idea?
