### ISSUE TITLE
ipad 1x, 2x mode

### ISSUE THREAD

**Issue by anestis1000** [lkzhao/Hero#411]
Hello, 
In my login view controller i have the following code in viewDidLoad() func:

```
        headerTitle.hero.modifiers = [.translate(x:400), .delay(0.1), .whenDisappearing(.translate(x:-400), .delay(0.1))]
        usernameTextField.hero.modifiers = [.translate(x:400), .delay(0.12), .whenDisappearing(.translate(x:-400), .delay(0.12))]
        passwordTextField.hero.modifiers = [.translate(x:400), .delay(0.12), .whenDisappearing(.translate(x:-400), .delay(0.12))]
        forgotPasswordButton.hero.modifiers = [.translate(x:400), .delay(0.14), .whenDisappearing(.translate(x:-400), .delay(0.14))]
        termsLabel.hero.modifiers = [.translate(x:400), .delay(0.14), .whenDisappearing(.translate(x:-400), .delay(0.14))]
        termsButton.hero.modifiers = [.translate(x:400), .delay(0.14), .whenDisappearing(.translate(x:-400), .delay(0.14))]
        termsCheckboxButton.hero.modifiers = [.translate(x:400), .delay(0.14), .whenDisappearing(.translate(x:-400), .delay(0.14))]
```

My app has iphone specific design. I don't have any problem with these animations. My problem is when I use the app on ipad. In 1x mode everything is ok, on 2x mode all the animation elements appear in the beginning of animation very big, and then zoom out with a glitch. This happen only in 2x mode (the circle button at the bottom-right corner of the ipad screen)

**Comment by lkzhao** [comment]
What do you mean by 1x and 2x mode. It is the scaling on retina iPads? It would be best if you  give me an example project so that I can help you debug.

**Comment by lkzhao** [comment]
Latest master branch should have the fix. Please help me check if it actually fixed the issue. Thanks.

**Comment by lkzhao** [comment]
Are you sure you are using the latest master branch? it is not live on cocoapods yet.
I tested the example app by changing it to an iPhone only app and the issue seems to be fixed.
If the issue still exist, I will need you to provide me an example project.

**Comment by anestis1000** [comment]
Ok, you are right
I use now in the pod file the pod 'Hero', :git=>'https://github.com/lkzhao/Hero', :branch=>'master'

Bug fixed

Thank you
Anestis
