### ISSUE TITLE
image animation 

### ISSUE THREAD

**Issue by jackpaster** [lkzhao/Hero#42]
@pborreli @e28eta @mRs- @sgl0v @CalebeNP  I have an image animation where an image inside a cell goes to fill the entire view of the view controller. Do you mind helping me. Because it almost looks like the images overlaps the image of the detail page view controller and then disappears.

**Comment by jackpaster** [comment]
it looks off

**Comment by JustinM1** [comment]
check https://github.com/lkzhao/Hero/issues/31, might have to do with the zPosition.

**Comment by jackpaster** [comment]
@JustinM1 it didn't help. could i please Skype with you to show you

**Comment by jackpaster** [comment]
@JustinM1 I'm using this with dynamic cells, and the animation is not working properly if i set it with dynamic cells. I tried using the basic hero animation from your project in mine, but how would i use hero with dynamic cells

**Comment by lkzhao** [comment]
@jackpaster Are you still having this problem. I got time today, I can take a look at your problem.

**Comment by lkzhao** [comment]
Close due to inactivity.

**Comment by jackpaster** [comment]
@lkzhao Yes I am could you please take a look at it

**Comment by jackpaster** [comment]
@lkzhao sorry I couldn't talk to you sooner, I was away

**Comment by lkzhao** [comment]
Can you post a screenshot or upload a example project? Others might be able to benefit if they experiences the same problem.

**Comment by jackpaster** [comment]
@lkzhao sure, I'm still away on vacation with my family, and I will have access to my computer tomorrow. Is it fine if I post the example project tomorrow.

**Comment by jackpaster** [comment]
@lkzhao Thank you so much, I've been struggling with this problem for a month now and I've had no solution

**Comment by lkzhao** [comment]
Yes, no rush.

**Comment by jackpaster** [comment]
@lkzhao Thank you

**Comment by jackpaster** [comment]
@lkzhao I am so sorry, my flight was delayed and I only got back last night. I will send it to you by tonight. I hope I didn't scare you off from helping me. Thanks hope you understand

**Comment by lkzhao** [comment]
Yea np

**Comment by jackpaster** [comment]
@lkzhao How should i show it to you. Do you want me to email the project to you or what should I do.

**Comment by lkzhao** [comment]
Upload it to github and sent me the link would be the best way.

**Comment by jackpaster** [comment]
[Example.zip](https://github.com/lkzhao/Hero/files/764878/Example.zip)
Here is my zip file of the project. My Skype is jackpaster22. I would like to sit down with you and have a quick conversation. what I'm looking to do is have a the same animation as the basic view controller you have in your hero. I want to have the image expand the way it does in snapchat. And what I'm looking for is when you hold down on a cell for more than two seconds. The cell shrinks to 4/5 the size its at the way it does on snapchat. You can definitely do both with your project but the project is not working with me. Can you help me and Skype with me please.

**Comment by jackpaster** [comment]
@lkzhao the project is up. Would you like me to take a video about the cell animation of it shrinking and expansion to a detail view controller, to show exactly what I'm talking about.

**Comment by jackpaster** [comment]
What do you think about skyping and did you take a look at the project

**Comment by lkzhao** [comment]
Yes, I have. Unfortunately I couldn't skype with you. It is a bit inconvenient.

For the expanding transition, it looks weird because you have multiple views with the same `heroID`  `blue` inside your table view controller. You should only have one. It should be set during `tableView(_:didSelectRowAt:)`

For you shrink animation, you have to do some custom UIView animation. There are plenty of tutorials available online, here is one: https://www.raywenderlich.com/2454/uiview-tutorial-for-ios-how-to-use-uiview-animation

I have also noticed some autolayout constraints issues in your TableViewCell2.xib. Ideally you shouldnt have fixed height constraint on cell's subviews. They should be determined by the cell's height.

**Comment by jackpaster** [comment]
could you fix it and show me what it would look like

**Comment by lkzhao** [comment]
ExampleTableViewController.swift 
```swift
    // MARK: - Table view data source
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
      let cell = tableView.dequeueReusableCell(withIdentifier: "TablesIdentifier", for: indexPath) as! TableViewCell2
      cell.Image2.heroID = "\(indexPath.item)"
      return cell
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let controller = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "yes23") as! ViewController2
        controller.view.heroID = "\(indexPath.item)"
        present(controller, animated: true, completion: nil)
    }
```
