### ISSUE TITLE
New logo for Hero

### ISSUE THREAD

**Issue by reallinfo** [lkzhao/Hero#424]
![hr](https://user-images.githubusercontent.com/36298335/37401478-d25c16c8-2790-11e8-923b-93f9112587af.png)
Hello, I designed a logo for Hero . If you like it, I will give you this logo as a gift.

**Comment by lkzhao** [comment]
Thank you very much for spending the time designing a logo. Changing the logo will require a lot works replacing it through out the project and different documentation sites. Which is not something I would like to do at this time.
