### ISSUE TITLE
Presenting view controller with .fade is not working

### ISSUE THREAD

**Issue by beloso** [lkzhao/Hero#426]
I am trying to dismiss a modal view controller and present a new modal view controller. Both with the fade transition. But I keep seeing the regular transition when presenting the second view controller

Here is a summed up version of my code:

```swift
let nextViewController = NextViewController()

currentViewController.hero.isEnabled = true
currentViewController.presentedViewController?.hero.isEnabled = true
nextViewController.hero.isEnabled = true

currentViewController.hero.modalAnimationType = .fade
currentViewController.presentedViewController?.hero.modalAnimationType = .fade
nextViewController.hero.modalAnimationType = .fade

currentViewController.dismiss(animated: true, completion: nil)
currentViewController.present(nextViewController, animated: true, completion: completionHandler)
```

**Comment by dudihisine** [comment]
i dont think that put the present after the dismiss is fine but if i figure out what you wanted to to your should use something like this:

`
        let src : UIViewController = self
        let dst : UIViewController = NextViewController()
        
        src.isHeroEnabled = true
        dst.isHeroEnabled = true
        
        dst.heroModalAnimationType = .fade

        src.hero_replaceViewController(with: dst)
`

**Comment by lkzhao** [comment]
The following two lines don't do anything
```swift
currentViewController.presentedViewController?.hero.isEnabled = true
currentViewController.presentedViewController?.hero.modalAnimationType = .fade
```
Also, like what @dudihisine said.
```
currentViewController.dismiss(animated: true, completion: nil)
currentViewController.present(nextViewController, animated: true, completion: completionHandler)
```
is not ideal.

Either user `hero.replaceViewController` or call `present` after `dismiss` has completed
```swift
let parent = presentingViewController!
currentViewController.dismiss(animated: true) {
    parent.present(nextViewController, animated: true, completion: completionHandler)
}
```
