### ISSUE TITLE
import Hero module in Objective c  project

### ISSUE THREAD

**Issue by beladiya** [lkzhao/Hero#44]
When i add Hero Library manually or using Pod , Hero module not find error generate.Is this solution for import Hero in C project instead of Swift project?

**Comment by lkzhao** [comment]
I have never tried it myself. But it should work with Objective c projects. The only downside is that you won't be able to subclass swift classes in objc. Not a big problem if you don't need custom animation. 


So is it working for you? When using cocoapods?

**Comment by FlorianBasso** [comment]
You can import `#import <Hero/Hero-Swift.h>` and it should works

**Comment by MagicNew** [comment]
@FlorianBasso @lkzhao @
I've got the same issue with @beladiya . Using cocoapods to include Hero, the <Hero/Hero-Swift.h> file not found.

**Comment by RandallWang** [comment]
use `@import Hero;` instead

**Comment by umairhassanbaig** [comment]
You can create a wrapper swift extension with @objc attribute. e.g

```
@objc extension UIView {
    public var _heroID: String? {
        set {
            self.hero.id = newValue
        }
        get {
            return self.hero.id
        }
    }
    
    public var _heroEnabled: Bool {
        set {
            self.hero.isEnabled = newValue
        }
        get {
            return self.hero.isEnabled
        }
    }
}

@objc extension UIViewController {
    public var _heroEnabled: Bool {
        set {
            self.hero.isEnabled = newValue
        }
        get {
            return self.hero.isEnabled
        }
    }
}

```
