### ISSUE TITLE
[Hero 1.1.0] [iOS11] Modifiers on UINavigationController's navigationBar have no effect when prefersLargeTitles is true

### ISSUE THREAD

**Issue by gh123man** [lkzhao/Hero#442]
In iOS 11+ where `prefersLargeTitles` is enabled I am unable to control the "slide up" animation of the large text when a new controller is pushed. 

In the navigation controller, prior to push `prefersLargeTitles` is set to `true`.
Then it is disabled on push to collapse the view in the next view controller: 
```swift
override func pushViewController(_ viewController: UIViewController, animated: Bool) {
     super.pushViewController(viewController, animated: animated)
     navigationBar.prefersLargeTitles = false
}
```

The slide up animation appears to be in control of iOS instead of hero (modifiers have no effect). 

What is odd is that the animation appears to be a mix of a system animation and something hero is doing (speeds change in an unpredictable way). It seems the nav slide up animation lasts the duration of the longest subview animation.

My goal is to change the duration of the "slide up" animation in the navigation bar. I have been unable to find any hero docs that target a scenario like this. 

Is it possible that this is simply not possible? Doing further research it appears the navigation bar transitions (at least the crossfade) cannot be customized: https://stackoverflow.com/a/21614376/1152375

**Comment by lkzhao** [comment]
Yep, there is no way to customize the animation behaviour of the navbar.
