### ISSUE TITLE
Broken (Auto) Layout, all frames of pushed/presented controller are 0

### ISSUE THREAD

**Issue by TadeasKriz** [lkzhao/Hero#45]
Hi,

I wanted to use these awesome animations in our project, however I'm having problems with layout. Are there any requirements for when should constrains be created in order to work with Hero correctly?

If you'd need any more details, let me know.

Thanks

**Comment by TadeasKriz** [comment]
It seems that if I manually run `controller.view.layoutIfNeeded()` after I create the controller and before I push/present it, it does work.

**Comment by lkzhao** [comment]
Weird. I call layoutIfNeeded every time before starting the transition. You shouldn't have to call that yourself. Can you provide me with an example project so I can debug this?

**Comment by lkzhao** [comment]
Closing due to no response. Feel free to reopen if the problem persist.
