### ISSUE TITLE
problem with view during transition

### ISSUE THREAD

**Issue by ivanvorobei** [lkzhao/Hero#469]
Attached the GIF.
For one view set hero ID, for the others views nothing is set

![ex](https://user-images.githubusercontent.com/10995774/40879609-64d85706-66ab-11e8-92c0-069fca8be50c.gif)

**Comment by GarthSnyder** [comment]
Ah, that forceAnimate part is the secret I was looking for... :-) And it _is_ a secret - it doesn't seem to be mentioned anywhere in the docs or wiki, or even in the blog post linked above. 

My use case is a label inside a view with a colored background. The view changes size, which I want to animate. However, I want the label to just stay in the same place and not be distorted as the superview stretches.

forceAnimate + useGlobalCoordinateSpace does work, but from the perspective of the API, is it really necessary to have a separate forceAnimate modifier? useGlobalCoordinateSpace doesn't seem to have any effect at all on its own; why not just assume forceAnimate if it appears by itself? And if you apply additional animation modifiers, well, then you're going to be animating anyway, so it's the same as if you had assumed forceAnimate anyway, isn't it?
