### ISSUE TITLE
Hero modifiers don't affect transition

### ISSUE THREAD

**Issue by vkaramov** [lkzhao/Hero#47]
I have removed Hero modifiers from the Demo App, one-by-one and didn't notice any difference in the App behavior running in iPhone 5(iOS 9.0) Simulator.

**Comment by lkzhao** [comment]
They should. Are you still experiencing this?

**Comment by vkaramov** [comment]
Yes. Could you please give me an example where can I see the difference?

**Comment by lkzhao** [comment]
In the first example: Basic. if you remove the `arc` modifier, you will see that the squares go directly to their destination. Note that you will have to remove the destination views' modifier.

**Comment by vkaramov** [comment]
Are you going to provide some documentation regarding modifiers? I'm wondering how, how example, zPosition works.

**Comment by lkzhao** [comment]
You can alt+click on the modifier in code to see the header doc. Or you can checkout the usage guide. https://github.com/lkzhao/Hero/wiki/Usage-Guide#zposition-modifier
