### ISSUE TITLE
Doesn't work correctly with nested vc and unwind segue.

### ISSUE THREAD

**Issue by lastcc** [lkzhao/Hero#470]
https://developer.apple.com/library/content/samplecode/SegueCatalog/Introduction/Intro.html

download and open Detail.storyboard.

find Nested View Controller.

setup Hero, add matched views. 

launch the app, tap `modal present within here`

then tap `dismiss modal via unwind`

the vc's appearance will collapse. tested on iOS 11.4.

**Comment by lkzhao** [comment]
Nested VC and unwind segue are not supported ATM.
Try to see if `hero.unwindToViewController` or `hero.replaceViewController` suits your need.

**Comment by lastcc** [comment]
Thanks for your reply. Another issue is that the keyboard animation curve has 'bugs' @lkzhao ? can I change system keyboard curve back to normal?
