### ISSUE TITLE
Pod can not find Hero libary

### ISSUE THREAD

**Issue by sishenyihuba** [lkzhao/Hero#48]
my CocoaPods version is 1.20rc.

When run pod search 'Hero',telling that no this libary,Is there any help?  

Hope for your replay.

**Comment by XHQFighting** [comment]
I can search it ,but if I input "pod install", pod shows error
the error information is “Unable to satisfy the following requirements:

- `Hero` required by `Podfile`

Specs satisfying the `Hero` dependency were found, but they required a higher minimum deployment target.”
my CocoaPods version is 1.1.1, other lib is can install

**Comment by NilStack** [comment]
Maybe you need to run 'pod update' to update your local specs repositories.

**Comment by sishenyihuba** [comment]
I tryed, but failed.    Is that   -----    pod 'Hero'?

**Comment by NilStack** [comment]
right. you can try --verbose to get more debugging information.

**Comment by sishenyihuba** [comment]
<img width="722" alt="pod search result" src="https://cloud.githubusercontent.com/assets/7836659/22133430/1d0503c2-defb-11e6-86aa-31075950a1f9.png">

Can u help watching the pod search result pic?    Hero lib is not found ...

**Comment by NilStack** [comment]
Hero is in my search result. can't figure out the issue in your scenario without more info.

**Comment by lkzhao** [comment]
try pod repo update

**Comment by sishenyihuba** [comment]
<img width="664" alt="2017-01-21 22 55 46" src="https://cloud.githubusercontent.com/assets/7836659/22175273/c0e4980e-e02c-11e6-8ab8-459a7961ab4c.png">
After I tried 'pod repo update',the result is here.But hero can not be found too. Too Blue.

**Comment by lkzhao** [comment]
@sishenyihuba Did you fix it yet?

**Comment by sishenyihuba** [comment]
It is  a pity ... I tried many ways but failed.

**Comment by lkzhao** [comment]
@sishenyihuba 我在新的一台电脑上也试了。`pod search Hero` 和 `pod install` 都正常。你试试重新装一下cocoapods，或者删掉cocoapods的spec文件夹？

**Comment by sishenyihuba** [comment]
Fix it！Thanks  so much for response, I will try to make some smoth and seamless animation with Hero!
