### ISSUE TITLE
Tabbar animation doesnt work

### ISSUE THREAD

**Issue by EgorkZe** [lkzhao/Hero#482]
Hi , @lkzhao !
I enabled hero for all tabs screen in TabBarViewController, but it doesn't work.
Any ideas how to solve it? Maybe someone has an example tabbar usage with hero?

**Comment by khoren93** [comment]
Hi, @EgorkZe 
Try to create a subclass of UITabBarController and add this lines in viewDidLoad
hero.isEnabled = true
hero.tabBarAnimationType = .autoReverse(presenting: .slide(direction: .left))

**Comment by EgorkZe** [comment]
Hi, @khoren93 It didn't help( 
FYI i created tabbar view controller programmatically
