### ISSUE TITLE
Can only be used in Present ViewController?

### ISSUE THREAD

**Issue by XHQFighting** [lkzhao/Hero#50]
In the Demo, I put the “present(vc, animated: true, completion: nil)” replaced with “self.navigationController?.pushViewController(vc, animated: true)”,the view's animation effects disappear

**Comment by lkzhao** [comment]
https://github.com/lkzhao/Hero/wiki/Usage-Guide#uinavigationcontroller--uitabbarcontroller

**Comment by deepaksuthar** [comment]
@XHQFighting did you get it working as I am facing the same problem.
with works with “present(vc, animated: true, completion: nil)” 
but not with “self.navigationController?.pushViewController(vc, animated: true)”

@lkzhao can you please elaborate ?

Thank you

**Comment by kostapappas-Desquared** [comment]
best solution is here 
https://github.com/HeroTransitions/Hero/issues/25#issuecomment-271123483
