### ISSUE TITLE
Is this lib support swift 2.3?

### ISSUE THREAD

**Issue by sishenyihuba** [lkzhao/Hero#51]
Hi lkzhao:

If there any help ,I want to use your lib into my Swift2.3 Project?

**Comment by lkzhao** [comment]
No it doesn't. It is developed directly on swift 3. I don't plan to backsupport 2.3. The conversion should be easy but tedious. If you need the support, you can also help others by creating a PR.

**Comment by sishenyihuba** [comment]
Ou,that is really a pity?   Thanks all the way for opening source such a gorgeous library.
May be  I can try to do that tedious work.

**Comment by mRs-** [comment]
2.3 is deprecated soon, maybe you should move your project to swift 3 fast ;)
