### ISSUE TITLE
No such module Hero

### ISSUE THREAD

**Issue by lijoraju** [lkzhao/Hero#54]
After installing the pod file when I try to import Hero I'm getting a No such module Hero error. Why is it so? Can you help me on this?

**Comment by tikipatel** [comment]
@lijoraju Are you opening the `.xcworkspace`?

**Comment by lijoraju** [comment]
yeah I'm opening .xcworkspace

**Comment by lkzhao** [comment]
Did you run the app? Pods will build the first time you run the app.

**Comment by lijoraju** [comment]
No it failed to build 
![screen shot 2017-01-24 at 11 24 54 am](https://cloud.githubusercontent.com/assets/22126574/22235834/e0a71dd6-e227-11e6-9e32-0341577af795.png)

**Comment by lkzhao** [comment]
update your xcode

**Comment by pepito87** [comment]
Had the exact same error. I was on xcode 8.0. 

Updating to 8.2 did the trick. @lijoraju
