### ISSUE TITLE
wrong extend edges effect

### ISSUE THREAD

**Issue by imnak0** [lkzhao/Hero#56]
I have UITabBarController, and first tab displays NavigationController.
The Root ViewController shows fine.
But if I push the second ViewController with hero enabled, then it extends edges under Tabbars, even though I unchecked the "Under Bottom Bars" in the Storyboard Option.

![image](https://cloud.githubusercontent.com/assets/1219732/22246620/f7f7bbb6-e278-11e6-8111-b4db01272f79.png)

The weird thing is that if I select other tab and comes back to previous tab, then the viewcontroller shows correctly, not under-the-bottom-bars.

![ezgif com-1e06c4e359](https://cloud.githubusercontent.com/assets/1219732/22246850/304988ae-e27a-11e6-9ab7-4ca6ad554127.gif)

Any advice is greatly appreciated,

**Comment by lkzhao** [comment]
I am sick this week so won't be able to help you quickly. Could be a bug with Hero. Don't worry about it for now. I will see what I can do when I get better.

In the mean time you can hack a fix by setting the frame on your second view controller's view manually during viewWillAppear.

**Comment by lkzhao** [comment]
To make sure. You have a nav controller inside the first view controller of your tab bar controller, correct?

**Comment by lkzhao** [comment]
I am not seeing this when using auto layout. I pinned the square to the bottom edge. Not sure what your setup is. Can you upload a small demo? Are you laying out the views programmatically?

**Comment by imnak0** [comment]
here's demo for you
https://github.com/imnak0/HeroDemo

I'm not familiar with storyboard so please let me know if there's something wrong in my side, not on the hero code
Thanks a lot,

**Comment by lkzhao** [comment]
Should be fixed on the latest master, try:

```ruby
pod "Hero", :git=>"https://github.com/lkzhao/Hero.git"
```

This is related to https://github.com/lkzhao/Hero/issues/60. Hero didn't set the frame correctly.
