### ISSUE TITLE
Combine with Pop

### ISSUE THREAD

**Issue by magorik** [lkzhao/Hero#58]
Hi, may somebody combine this framework with Facebook pop?

**Comment by javiSwift** [comment]
Is it possible to push the controller with transition or only works with present?

**Comment by lkzhao** [comment]
@javiSwift push is supported. https://github.com/lkzhao/Hero/wiki/Usage-Guide#uinavigationcontroller--uitabbarcontroller

**Comment by lkzhao** [comment]
@magorik What do you want to achieve with Hero+Pop? You can write a HeroPlugin that uses Pop to do your custom animations.

**Comment by lkzhao** [comment]
Close due to inactivity.
