### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by rodolfoconde** [lkzhao/Hero#59]
Hi,
I can not install the library. i Install podfile and after ?? Is there any video tutorial? I'm starting with swift. 

Thank you

**Comment by lkzhao** [comment]
Checkout https://guides.cocoapods.org/

**Comment by rodolfoconde** [comment]
![captura de tela 2017-01-30 as 20 51 42](https://cloud.githubusercontent.com/assets/4187401/22445307/fd974ed8-e72d-11e6-84a4-9f69515af15e.png)
![captura de tela 2017-01-30 as 20 51 19](https://cloud.githubusercontent.com/assets/4187401/22445306/fd92da38-e72d-11e6-8e4f-6464e769388c.png)


Look

**Comment by lkzhao** [comment]
You need to open the xcworkspace file. And also make sure your Xcode version is 8.2
