### ISSUE TITLE
System Swipe to back disabled after Hero is enabled

### ISSUE THREAD

**Issue by bishalg** [lkzhao/Hero#62]
How to enable *Swipe to Back* on pushed view-controller where Hero is enabled ?

**Comment by lkzhao** [comment]
This is expected. You can create a interactive Hero transition yourself to
mimic the behavior. Or you can disable Hero immediately after completing
the transition.

**Comment by bishalg** [comment]
@lkzhao : thks for the suggestions. But do you have any sample code or example for - *creating a interactive Hero transition* ?

**Comment by lkzhao** [comment]
Checkout the video player, apple homepage, or the image viewer example
inside the example project. I will have a guide about interactive
transition soon.

**Comment by lkzhao** [comment]
Checkout http://lkzhao.com/2017/02/05/hero-interactive-transition.html. More coming soon.
