### ISSUE TITLE
Second view controller offset incorrect in navigation controller when navigationBar.isTranslucent is set to false

### ISSUE THREAD

**Issue by saeros** [lkzhao/Hero#63]
Hello,

First, thank you for this amazing library \o/

I've noticed that when I push a controller on a navigation controller stack with hero enabled, the new view controller appears with an incorrect offset (below the navigation bar) when the `navigationBar.isTranslucent` property is set to `false`.

Regards.

**Comment by lkzhao** [comment]
When you disable Hero, does this problem go away? Can you give me two screenshot? One with Hero enabled and one with it disabled

**Comment by saeros** [comment]
Yes, disabling Hero or setting the `isTranslucent` property back to `true` solves the problem.

I can't provide you comparative screenshots right now, as I'm working with on a project with sensitive data but basically the content of the second view controller appears below the navigation bar.

I'll try and make a demo project ASAP.

**Comment by lkzhao** [comment]
@saeros Can you try the latest master? Your problem might be fixed by https://github.com/lkzhao/Hero/issues/60

```ruby
pod "Hero", :git=>"https://github.com/lkzhao/Hero.git"
```

**Comment by saeros** [comment]
Thanks @lkzhao I'll give it a go and report back the result.

**Comment by saeros** [comment]
It appears the issue is fixed! Cheers :thumbsup:

**Comment by metisdev** [comment]
First of all awesome library 👍 

I have a tabbar (with 5 tabs) in a navigation controller. 
Last view controller of tabbar hides navigationbar. 
This causes the last view having a space below the view and the tabbar. 
If i disable hero it works without any problems. 
Also while hero is active, if a push another view (while last tab is active) and pop back, view displays correctly. 
Hero version 1.0.1
