### ISSUE TITLE
Unwind Segues not triggering Hero transitions

### ISSUE THREAD

**Issue by tditchek** [lkzhao/Hero#64]
When I navigate via an Unwind Segue my Hero-based transition doesn't work. Instead of abiding by the "Source(<component>)" modifier I set in the storyboard, it just uses the default vertical sliding transition animation. However, it works perfectly for other segues, just not Unwind segues. Does anybody know how to fix this issue?

**Comment by lkzhao** [comment]
Unwind segue is not officially supported. 

To make it work you will have to set isHeroEnabled on the viewController presented by the VC that you are unwinding to. 
For example,
A -> B -> C
To unwind from C to A requires B to be heroEnabled. 

Also with unwind segue, you will see C jumps to B instantly then animate from B -> A. Ideally it should be animating directly from C -> A. That is something I am working on, maybe in the form of a custom segue.

**Comment by lkzhao** [comment]
With 0.1.4, there are some new helper functions on UIViewController. You can use these to perform the unwind action. These provide a smooth unwind animation that goes directly from C -> A. Let me know if you find any bugs with these helpers.


  * **func hero_dismissViewController()**

     Dismiss the current view controller with animation. Will perform a navigationController.popViewController 
     if the current view controller is contained inside a navigationController.
  * **func hero_replaceViewController(with:UIViewController)**

     Replace the current view controller with another VC on the navigation/modal stack.
  * **func hero_unwindToRootViewController()**

     Unwind to the root view controller using Hero.
  * **func hero_unwindToViewController(_ toViewController:)**

     Unwind to a specific view controller using Hero.
  * **func hero_unwindToViewController(withSelector: Selector)**

     Unwind to a view controller that responds to the given selector using Hero.
  * **func hero_unwindToViewController(withClass: AnyClass)**

     Unwind to a view controller with given class using Hero.
  * **func hero_unwindToViewController(withMatchBlock: (UIViewController) -> Bool)**

     Unwind to a view controller that the match block returns true on.
