### ISSUE TITLE
UIImageView

### ISSUE THREAD

**Issue by cre8it** [lkzhao/Hero#65]
Hi, great library!

I face an issue, is there a possible reason why I cant set the HeroId for an UIImageView? Checked the code and the extension is set to UIView, so I don't see any obvious reason why the UIImageView doesn't use the Hero extension...

Any help appreciated 

Edit: The UIImageView I'm using is a custom subclass with a bunch (lots) of IBInspectable, it seems to me like XCode can only display a certain amount of Inspectables and drops the others ...

**Comment by lkzhao** [comment]
Try import Hero to your file.

**Comment by cre8it** [comment]
Well yes it works programatically but not as IBInspectable

**Comment by lkzhao** [comment]
Weird. It should appear. The example project also uses heroID in storyboard on UIImageView.

**Comment by cre8it** [comment]
The UIImageView I'm using is a custom subclass with a bunch (lots) of IBInspectable, it seems to me like XCode can only display a certain amount of Inspectables and drops the others ...

**Comment by cre8it** [comment]
But while I'm at it, another question / issue... that UIImageView Subclass I'm using gives me the ability to define a circular mask. When Hero animates the transition between the two UIImageViews with Circular mask, Hero seems to drop the mask for a fraction of a second and displays the image in a square frame... Ultimately the image is displayed correctly with that circular mask, but just during the transition it reverts to his square state ...

Any idea how I can overcome this behavior?

**Comment by lkzhao** [comment]
@cre8it It is because Hero does an optimization with UIImageView. Instead of taking a snapshot, it just uses a regular UIImageView when it sees a UIImageView being animated. This provide smoother animation & works great with a default UIImageView, but doesn't support subclass or masking. I will have a new modifier in the next version to disable this level of optimization for a specific view.

**Comment by cre8it** [comment]
Thank you for the detailed explanation. any idea when this next release will be available, or how I could circumvent this problem for now, even if I have to adapt something in the library?

**Comment by lkzhao** [comment]
Should be out soon. Either today or tmr.

**Comment by cre8it** [comment]
That's awesome!

**Comment by lkzhao** [comment]
0.1.4 is out now. You can use the new `.useNormalSnapshot` modifier to request a normal snapshot instead of the optimized one.

**Comment by lkzhao** [comment]
@cre8it Let me know how it goes.

**Comment by cre8it** [comment]
Absolutely amazing @lkzhao, just updated, implemented the modifier and it works perfectly. Your library is worth gold and makes app development even more compelling ;) 

Your support is definitely A class as well, thank you
