### ISSUE TITLE
iPhone 7 simulator - the animations do not work

### ISSUE THREAD

**Issue by inforeqd512** [lkzhao/Hero#68]
Hero example works in all simulators except for the iPhone 7 and above. the animations do not work in them.. the attached video shows the issue. 
[hero.zip](https://github.com/lkzhao/Hero/files/753566/hero.zip)

**Comment by onevcat** [comment]
It's a known issue and already mentioned in README. According to README.md, it is related to [this](https://forums.developer.apple.com/thread/63438).
