### ISSUE TITLE
Use Hero Transitions with Custom Segues?

### ISSUE THREAD

**Issue by air6199** [lkzhao/Hero#69]
I'm trying to use a custom segue to slide a view from the bottom of the screen up to around 80 points from the top. This view then has a next button at the bottom, which when pressed will hopefully utilise Hero transitions. 

Issue:
I can only get the transitions to work if I use hero_replaceViewController(). However, when i do use this, my view is no longer 80 points from the top but instead it is full screen again. I've tried to transform the view again at various points with no luck. 

If i don't use hero_replaceViewController(), then the transitions do not work but the destination view frame is the correct size. I was thinking this may be down to me using custom storyboard segues instead of the standard push, etc? 

Any thoughts?

**Comment by lkzhao** [comment]
If your view is 80 points from the top. Are you displaying the previous VC underneath? If yes, then you are probably using overCurrentContext or overFullScreen modal presentation. Hero doesn't support these two types of modal presentation at the moment. This is something that I would also like to support, but quite hard to implement.

**Comment by lkzhao** [comment]
A workaround is to add your short VC into your top VC by using `addChildViewController` and manually add the view in to your topVC's view. Then do a sliding animation. After this, Hero will treat this as a single VC.

**Comment by lkzhao** [comment]
#37

**Comment by lkzhao** [comment]
.overFullScreen support is implemented in 0.3.0
