### ISSUE TITLE
run the demo,result in "  Xcode a declaration cannot be both 'final' and 'dynamic'   "

### ISSUE THREAD

**Issue by sishenyihuba** [lkzhao/Hero#7]
I run the demo,result in "  Xcode a declaration cannot be both 'final' and 'dynamic'   "

I search on stackoverflow,find out that do not let static class property in extension class. Is there any solution?

**Comment by lkzhao** [comment]
Could you give me more context? Which line are you getting this error on?

**Comment by yongseongkim** [comment]
same event happened to me. When just run the examples project in Xcode 8.0, build failed.
it is swift compile error. `a declaration cannot be both 'final' and 'dynamic'`

**Comment by lkzhao** [comment]
@yongseongkim Can you give me a screen shot or line number?

**Comment by yongseongkim** [comment]
Xcode 8.0, OSX El Capitan
![2017-01-05 3 44 25](https://cloud.githubusercontent.com/assets/8086744/21671323/f6e039e4-d35d-11e6-85cf-c6d49cf254b7.png)

**Comment by yongseongkim** [comment]
![2017-01-05 3 44 25](https://cloud.githubusercontent.com/assets/8086744/21671333/0656c316-d35e-11e6-9196-c28591fd4c90.png)

**Comment by lkzhao** [comment]
Somehow I am not getting this. If you change all `static` keyword to `class` in **CAMediaTimingFunction+Hero.swift**. Do you still get this error?

**Comment by lkzhao** [comment]
i.e.

```swift

  static let linear = CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear)
  static let easeIn = CAMediaTimingFunction(name: kCAMediaTimingFunctionEaseIn)
  //...
```

to 

```swift
  class let linear = CAMediaTimingFunction(name: kCAMediaTimingFunctionLinear)
  class let easeIn = CAMediaTimingFunction(name: kCAMediaTimingFunctionEaseIn)
  //...
```

**Comment by lkzhao** [comment]
Nvm that shouldn't work.

**Comment by lkzhao** [comment]
@yongseongkim This is probably just a Xcode version issue. Please update your Xcode to 8.2 and above. Your source change will be overridden the next time you do a 'pod install'.


Thank you all for reporting this. 😆 I have updated Xcode version the README.

**Comment by sishenyihuba** [comment]
Hi lhzhao,Thanks for all that .

It came out  fun when I update the Xcode version.

Best Wishes.
