### ISSUE TITLE
Breaking changes since v0.1.8

### ISSUE THREAD

**Issue by pblondin** [lkzhao/Hero#70]
In v0.1.8, some UI gliches appear when transitioning using matched views. In my case i'm doing a transition using matched views where width of both views are not exactly the same. The glitch seems to happen when removing the snapshot view. Flickering happens since width of both views do not match. This glitch didn't happen in v0.1.7.

In v0.1.9, transition using paired views only seems to work in one direction. When presenting the view controller, it seems only the default cross-fade transition occurs. On the other side, when dismissing the view controller the matched views transition works properly.

**Comment by lkzhao** [comment]
Are you using the zPosition modifier in 0.1.7?

**Comment by lkzhao** [comment]
Is the glitches you saw in 0.1.8 still happening in 0.1.9?

**Comment by lkzhao** [comment]
0.1.8 introduced a new way of controlling draw order. Hero should be able to handle draw orders much better now. the zPosition modifier is not needed.

In 0.1.9 the zPosition modifier behaves differently. Similar to the `.position` modifier, `.zPosition` now animates the layer's zPosition from/to the give value.

If you are still using the zPosition modifier, it might result in some unintended zPosition animation.

**Comment by lkzhao** [comment]
0.1.9 should be good now. I just published it. The problem your are seeing with 0.1.9 is indeed a bug. Thanks for reporting!
