### ISSUE TITLE
Entire UI flashes white on transitions in newest update

### ISSUE THREAD

**Issue by nathanlanza** [lkzhao/Hero#72]
Completely programmatic app. Using a collection view with a navigation controller that calls "show" to a simple detail view controller upon selecting a cell. Immediately after hitting a cell the entire screen flashes and then the smooth transition works as expected.

**Comment by lkzhao** [comment]
Are you using zPosition modifier? Can you provide an example project for me to better help you? I am not seeing the flicker in my testing.

**Comment by lkzhao** [comment]
Are you on 0.1.9?

**Comment by nathanlanza** [comment]
Nevermind, this was just the iPhone 7 simulator bug (which I assume the bug is flashing at the start of a transition).
