### ISSUE TITLE
Perform animation when application starts

### ISSUE THREAD

**Issue by gorozco58** [lkzhao/Hero#73]
I am trying to make the next animation when application starts,
I want to animate collection view cell and show them in cascade but I don't know how to do it, modifier only works when a transition is performed.
is it posible without view controller transition ?

![ezgif com-556ffd625d](https://cloud.githubusercontent.com/assets/6413687/22713352/090dad56-ed56-11e6-96da-e600e17e82e9.gif)

**Comment by lkzhao** [comment]
Hero only work with VC transitions. You can create an empty VC and set it as the initial view controller. Inside `viewDidAppear` immediately run `hero_replaceViewController` with your collection view VC.

**Comment by lkzhao** [comment]
Nice use of the cascading effect!

**Comment by gorozco58** [comment]
Thank you @lkzhao for the answer I am gonna try your advice 👍
