### ISSUE TITLE
examples have some errors.

### ISSUE THREAD

**Issue by arden** [lkzhao/Hero#75]
when i'm run exampes on xcode 8.2.1 can't work fine.
some errors:
/Users/arden/data/source/swift/动画/Hero/Examples/HeroExamples/Examples/AppleHomepage/AppleProductViewController.swift:59:10: error: Type Name Violation: Type name should start with an uppercase character: 'normal' (type_name)

**Comment by lkzhao** [comment]
I am not seeing this. Maybe it is SwiftLint. Are you using an old version of it?

**Comment by arden** [comment]
Because my SwiftLint version is to low.

**Comment by lkzhao** [comment]
Cool, glad we got this solved.
