### ISSUE TITLE
zPositionIfMatched Removed

### ISSUE THREAD

**Issue by Rozariozaro** [lkzhao/Hero#76]
Shared transition of views were working perfectly fine while push and pop from one viewController to another using zPositionIfMatched. Please add this functionality again.. Now this type of animation can only be added while using presentViewController.

**Comment by lkzhao** [comment]
zPosition is now a animatable property. If you want it set the zPosition. Hero will now read the layer's zPosition instead.

**Comment by lkzhao** [comment]
Also with the introduction of coordinate space. you might need the 'useGlobalCoordinateSpace' modifier to make some animation functions. Check out the usage guide on coordinate space.

**Comment by lkzhao** [comment]
you can use the new `.beginWithIfMatch` modifiers in your case.

Here is how:
```swift
.beginWithIfMatched(modifiers:.zPosition(5))
```
This should behave the same way as `.zPositionIfMatched(5)` in the previous versions.
