### ISSUE TITLE
setValue:forUndefinedKey error But only when running through Xcode.

### ISSUE THREAD

**Issue by mplaczek** [lkzhao/Hero#77]
Hi, 
First off I just wanted to say this is a fantastic library. Thank you for your awesome contribution to the community!

I have just updated to 0.1.8... previously hero was working as expected. Now I have an odd crash that only presents itself when navigating to a hero enabled scene and when I'm running the application on a real device connected to Xcode: 

[<UIImageView 0x119ad3840> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key heroModifiers.

When the same device is disconnected from Xcode the application runs fine and hero scenes work as expected.
Is it possible I have missed something during the installation of the new version?

**Comment by lkzhao** [comment]
That's odd. Try updating to the newest 0..2.0

**Comment by mplaczek** [comment]
Now updated, I seem to be having the same problem. Is there anything else you can suggest I look at?

**Comment by lkzhao** [comment]
Oh, did you have `heroModifiers` set in storyboard. That property has been renamed to `heroModifierString` in storyboard.
Check here and make sure you don't have `heroModifiers` set to any of the views:
<img width="261" alt="screen shot 2017-02-11 at 10 35 00 am" src="https://cloud.githubusercontent.com/assets/3359850/22854954/c991b774-f045-11e6-84f7-324a680acf95.png">

You can do a project wide search for `heroModifiers` and see if any storyboard contains it.

**Comment by mplaczek** [comment]
That sounds very likely to be the problem. I'll only be able to verify tomorrow. Thank you for your help 👍

**Comment by mplaczek** [comment]
Working perfectly now. Thanks
I'm really looking forward to seeing what I can do with this!
