### ISSUE TITLE
Animation Flicker since update

### ISSUE THREAD

**Issue by cre8it** [lkzhao/Hero#80]
Hi, since the update, one of the animation is not behaving as smooth as before. I have three elements which get animated during the transition, a username and an avatar image (which work perfectly) and a header bar (which doesn't work smoothly anymore -> See AniGif). 

I have tried all possible modifiers on the header but can't get it to work smoothly... any help?

![ezgif com-optimize](https://cloud.githubusercontent.com/assets/10096944/22827357/b3403e86-ef97-11e6-8f65-3dae62e1faac.gif)

The header in the first View is a simple View with BackgroundColor, the second header is a custom view where things get drawn (draw: rect)... 

Any hint highly appreciated, this library is awesome and brings apps to life ;)

**Comment by lkzhao** [comment]
Can I play around with this project somehow? It might be that the view's isOpaque property is set to true, and Hero is assuming that the view isn't transparent.

**Comment by cre8it** [comment]
@lkzhao is your email correct in your github profile?

**Comment by cre8it** [comment]
@lkzhao just tried to set the isOpaque to false on both views and it transitions smoothly again. Does that mean that we do have to set it to false by default in the future?

**Comment by lkzhao** [comment]
Yes, thats my email. 

If your view has transparent element, then you should set isOpaque to false, Hero will do a cross fade if any of the source/destination view is not opaque. Otherwise, Hero will overlay the destination view on top of the source view. Since the destination view is opaque, it should completely cover the source view after the transition finishes. This also eliminates the temporary see-through effect when crossfading.

Your case requires crossfading because one of you view cannot fully cover the other.

**Comment by cre8it** [comment]
OK that kinda makes sense, although it's weird it only happened after the update. But anyway as long as I can circumvent this by switching the opacity, I'm the happiest chap ;) thanks @lkzhao again for your fast response...

PS: Unfortunately the app is already very advanced and connected to a backend with OAuth. In order to share this project with you I'd have to recreate a backend with individual credentials so you play around with it. If it is important to you to be able and test, let me know, I'd for the sake of your great library  spend the time and efforts ;)

**Comment by lkzhao** [comment]
That change was made in 0.1.9 I think, before most of the views are crossfading. 

Sorry for the trouble. I have been making a lot of changes to the library lately. So it might not be very stable. 0.1.7 was more a stable version to be used. 

Thank you for testing these out. Definitely let me know if you encountered other issues.

**Comment by cre8it** [comment]
No need to apologize @lkzhao, you're not causing any troubles, in contrary you're contributing greatly to us building great apps! It's up to us to thank you for that...
