### ISSUE TITLE
Backward animation is broken after 0.1.7 ?

### ISSUE THREAD

**Issue by spensko** [lkzhao/Hero#81]
Hello. Just updated pod 0.1.7 -> 0.2 and all backward animations suddenly stop working.

I'm using nav controller with hero enabled and make push/pop transitions between two simple controllers

with hero 0.1.7 https://youtu.be/sMF85XaBjCQ
with hero 0.2.0 https://youtu.be/h6Ni3zgPrdQ

**Comment by lkzhao** [comment]
You probably have zPosition modifier used. Try removing those. the zPosition modifiers in the new versions is an animatable property just like position.

**Comment by spensko** [comment]
Nope, this is empty test project. Just one nav controller and two view controllers on storyboard without any Hero modifiers (without classes at all).

[HeroTest.zip](https://github.com/lkzhao/Hero/files/767054/HeroTest.zip)

**Comment by lkzhao** [comment]
Thanks for reporting. There is probably a regression with UINavigationController support. When presenting modally, the problem is gone. I will fix it in the next version. Please use 0.1.7 for now then.

**Comment by spensko** [comment]
Thanks!
Hero is great and saving a lot of time

**Comment by JegnuX** [comment]
@lkzhao Is this issue have been fixed ? I think I have this problem with a sample project. I use a UINavigationController. On push I have a view with `.translate(y:-50)`. It works great, but on pop, the animation doesn't work. The view just disappears without any animation.

**Comment by schmitzoide** [comment]
Same here.
