### ISSUE TITLE
Flashing problems

### ISSUE THREAD

**Issue by adellibovi** [lkzhao/Hero#82]
I'm having problem executing the example Music Player, it flashes at each animations. Is it because I'm running on simulator? Should I try anything?

**Comment by lkzhao** [comment]
iphone 7 simulators doesn't work. If you are not using iphone 7 simulators, then that might be a bug.

**Comment by adellibovi** [comment]
I'm closing this issue. I though it was only for 7, I was using 7 Plus simulator :) Thanks
