### ISSUE TITLE
Animations don't work in the simulator

### ISSUE THREAD

**Issue by kylebshr** [lkzhao/Hero#9]
First — thanks for this awesome library! It'll make so many tasks so much easier. 

Apologies if this a known issue, or something that can't be fixed, but I just wanted to point out that animations aren't working for me in the simulator (though they work fine on the device).

[Here](https://vid.me/Insp) is a video of it working on my iPhone 6s Plus.

[Here](https://vid.me/6OLH) is a video of how it behaves in the simulator (iPhone 7).

**Comment by lkzhao** [comment]
Checkout #2 😁

**Comment by kylebshr** [comment]
Ayyyy, thanks! I thought I was smart and looked first, but didn't check the closed issues 🙃

**Comment by lkzhao** [comment]
No problem! We all make that mistake.
