### ISSUE TITLE
Using cocoapods to install gets stuck

### ISSUE THREAD

**Issue by worchyld** [lkzhao/Hero#92]
I'm wanting to use cocoapods to install Hero, however it always seems to get stuck

I tried the following pod include:

pod 'Hero', :git => 'https://github.com/lkzhao/Hero.git'

as per the podspec

But it always gets stuck on `Pre-downloading: `Hero` from `https://github.com/lkzhao/Hero.git`

Any assistance on this would be helpful

**Comment by lkzhao** [comment]
The Hero repo is quite large. It might just be taking a long time to download.

**Comment by worchyld** [comment]
Ok, many thanks I will try again another time and report issues or close ticket
