### ISSUE TITLE
Use in CollectionView chat Environment

### ISSUE THREAD

**Issue by otymartin** [lkzhao/Hero#95]
@lkzhao 

This is more of a question.

Is it possible to leverage these transition effects to animate sending of messages like iMessage app? I use [JSQMessagesViewController](https://github.com/jessesquires/JSQMessagesViewController) which uses a collectionView and was wondering if I can put this lib to use in that environment

**Comment by lkzhao** [comment]
We will have this feature implemented adter v1.0.

Hero will be able to transition within a single VC via a 3 step process.

1. Ask hero to snapshot the VC's view hierarchy.
2. Perform any modification to your views.
3. Ask Hero to perform the transition.

In step 1, Hero will make a snapshot view to cover your changes in step 2. All of your modification in step 2 will be hidden.

Hero will also need to implement a way to query heroID and heroModifier via a view controller delegate. Would involve some work on the framework and some testing to be done.

**Comment by otymartin** [comment]
@lkzhao 
Nice thanks for the detailed answer.

Whats your timeline for `1.0`?

**Comment by lkzhao** [comment]
mid march probably.

**Comment by abbasmousavi** [comment]
@lkzhao Is there any timeline for this feature?

**Comment by aalenliang** [comment]
has this feature implemented? 
it there any document or example?
