### ISSUE TITLE
Issue when using with Tableview while search

### ISSUE THREAD

**Issue by Rozariozaro** [lkzhao/Hero#97]
I am using a custom textfield and I'm filtering the tableview using the text from the textfield.
When pushing from the table didselect method the shared view transition is transitioning from the wrong view.

when Poping back to viewController the shared view goes to two different places.

I am using the modifier of `[.beginWithIfMatched(modifiers: [.zPosition(3)]), .arc]`
The vewControllers are in a navigationController.

If you want more info i can share a screenshot in private.

**Comment by lkzhao** [comment]
You probably have two views with the same heroID. Remember to reset the heroID to nil on cell reuse. Otherwise the reused cell will still maintain the heroID previously assigned.

**Comment by Rozariozaro** [comment]
I'm passing a model to custom cell class. I'm setting the heroID for imageview when the model is set in cell class.
`didSet{
            guard let model = songDetail else {return}
            songImgView.heroID = model.name + model.album
            songImgView.heroModifiers = [.beginWithIfMatched(modifiers: [.zPosition(3)]), .arc]
}`

Can you help me where to reset heroID

**Comment by lkzhao** [comment]
You can override the prepareForReuse() method and set it to nil there.

**Comment by lkzhao** [comment]
Can you show me why you had to use the .beginWithIfMatched(.zPosition()) modifiers? Just want to see if there is something we can do inside the framework to eliminate confusing usages like this. You can send screenshot to my email if you need this to be private.

**Comment by Rozariozaro** [comment]
I have tried using `override func prepareForReuse() {
        super.prepareForReuse()
        songImgView.heroID = nil
    }`
the same issue persists

**Comment by lkzhao** [comment]
Then it might be something else. Send me some screenshots or an example
project would be nice.

**Comment by Rozariozaro** [comment]
I have mailed you at me@lkzhao.com with some screenshots,  Please check out.

**Comment by lkzhao** [comment]
ok. finally have some idea after an hour of debugging. 

<img width="1090" alt="screen shot 2017-02-16 at 3 07 50 pm" src="https://cloud.githubusercontent.com/assets/3359850/23038920/be571710-f459-11e6-8ad0-1f727b592637.png">

Apparently, the collection view keeps these cells around as its subviews with the isHidden property set to true. Therefore you have two views in your view hierarchy with the same heroID. I will have Hero check isHidden in the next version.

**Comment by lkzhao** [comment]
Pushed into latest master.

**Comment by lkzhao** [comment]
Your beginWithIfMatched is not needed anymore. You can safely remove it.
