### ISSUE TITLE
TabBar Transition since Version 3.0

### ISSUE THREAD

**Issue by cre8it** [lkzhao/Hero#98]
Hi, since version 3.0 and above I experience a new unwanted effect when transitioning via a TabBar. As you can see on the Image, although the backgrounds on the two viewcontrollers are exactly the same, the isOpaque is set to false and the center views have a clear background color, it displays this vertical line which doesn't make it look seamless anymore... any idea or help?

<img width="661" alt="screen shot 2017-02-16 at 14 24 00" src="https://cloud.githubusercontent.com/assets/10096944/23023159/7698bfe6-f454-11e6-8084-73f3f952e3cb.png">

**Comment by lkzhao** [comment]
From what I can see. Your background is a diagonal gradient. The default .slide animation is sliding the background from left to right. But your background image's left and right edge doesn't match up.

There are two ways to solve this.

First, set the default animation to fade before transitioning.

Second, give the background view a heroID.

If you wait for today's update, you can set the default animation on the tabbar controller, too.

**Comment by lkzhao** [comment]
Also if you change the diagonal gradient to a vertical one solves the problem too

**Comment by lkzhao** [comment]
With 0.3.2:
you can also use:
```swift
tabbarController.heroTabBarAnimationType = .fade
```

**Comment by cre8it** [comment]
thanks @lkzhao I will try with the fade transition... nonetheless the gradient is rather radial if not vertical actually... the weird thing is I never noticed it before updating to 0.3.x... but let me try with fade and 0.3.2 and I let you know

**Comment by cre8it** [comment]
do i need to subclass the tabbar or can I do it in either viewcontroller (before and after transition)?

**Comment by lkzhao** [comment]
Anywhere is fine. This is a persistent value. You can do it in your VC's `viewDidLoad`.

**Comment by cre8it** [comment]
just tried it and it works like a charm, I had to put the background back to Opaque though... but as usual, it's funny you always just release a version which solves my little issues ;) thanks mate!
