### ISSUE TITLE
Trouble with DefaultAnimation 

### ISSUE THREAD

**Issue by BilalReffas** [lkzhao/Hero#99]
Hi ! :)

I think I'm doing something working right? the presenting transition works great but however the dismissing transition don't work for me :/ ?

I set the values in  `viewDidLoad()` is this correct? Btw I'm trying to implement a interactive transition :) 

```swift 
self.isHeroEnabled = true  
Hero.shared.setDefaultAnimationForNextTransition(HeroDefaultAnimationType.selectBy(presenting:.cover(direction: .right), dismissing:.cover(direction: .left)))
```

Greetings :) 🎉

**Comment by fruitcoder** [comment]
You have to set `isHeroEnabled` on the presented view controller (the view controller you want to transition to). Are you doing that?

**Comment by BilalReffas** [comment]
@fruitcoder yes I'm doing it right. The problem is that the dismiss transition doesn't work for me.

**Comment by fruitcoder** [comment]
Can you send a small example project that illustrates the issue?

**Comment by BilalReffas** [comment]
My ViewController who will present the second VC where I want to transition to has one button. After the action I run this 

```swift
Hero.shared.setDefaultAnimationForNextTransition(HeroDefaultAnimationType.selectBy(presenting:.cover(direction: .right), dismissing:.cover(direction: .left)))
```
In my second VC has I enable Hero `viewdidLoad()`
```swift 
self.isHeroEnabled = true  
```
When I try to close my second VC I dismiss the VC using   
```swift
dismiss(animated: true, completion: {
          ...
        })
```
😕

**Comment by fruitcoder** [comment]
So both of your view controllers have `isHeroEnabled = true`?

**Comment by BilalReffas** [comment]
Yes

**Comment by lkzhao** [comment]
Not enough context here. Can you send us an example project?

Or try using these properties for specifying default animation.

```swift
extension UIViewController {
  /// default hero animation type for presenting & dismissing modally
  public var heroModalAnimationType: HeroDefaultAnimationType
}
extension UINavigationController {
  /// default hero animation type for push and pop within the navigation controller
  public var heroNavigationAnimationType: HeroDefaultAnimationType
}
extension UITabBarController {
  /// default hero animation type for switching tabs within the tab bar controller
  public var heroTabBarAnimationType: HeroDefaultAnimationType
}
```
